### ISSUE TITLE
load models from database

### ISSUE THREAD

**Issue by lntseu** [openscenegraph/OpenSceneGraph#1004]
I am trying to store some oblique photogrammetry data (in osgb format) in database. 

Could you please give some advices on how to load osgb models from database?

Do I need to create a new plugin ? Or just override some classes would do the job ?

Thank you for your time.

**Comment by robertosfield** [comment]
Please use the osg-users googlegroup for support question.  When you ask question make sure you explain what you mean terms like "database" as it's too open ended to know what you mean.
