### ISSUE TITLE
Rendering errors with collada using Qt's QOpenGLWidget and QGLWidget

### ISSUE THREAD

**Issue by unelsson** [openscenegraph/OpenSceneGraph#1007]
I also made a bug report to Qt5 - https://bugreports.qt.io/browse/QTBUG-89140 and uploaded a few screenshots there to show the problem.

When Qt5/QOpenGLWidget is integrated with OpenSceneGraph, some models load in a wrong fashion. Screenshots are attached. OpenSceneGraph alone renders the same models correctly. This may be a Qt5 bug, but I'm reporting it here, because it may be related to OSG, perhaps OSG's dae-plugin setting some variable in a wrong fashion that is not compatible with Qt4 and Qt5.

This was tested using a modified version of osgQt ( https://github.com/openscenegraph/osgQt ), which uses QOpenGLWidget along with osgViewer::CompositeViewer. The same bug however occurs with Qt4 and Qt5 using QGLWidget as well (which is clearly visible in OpenMW-CS, free software using OSG, osgQt and Qt4/Qt5).

The problem exists, when loading dae/collada models. When tested with fbx-model and osgt-model, the rendering is correct (although the model itself has a minor problem with non-applied mirror modifier).

An example code along with modifier osgQt for CompositeViewer is at https://gitlab.com/unelsson/osgqt_tests/

This line (and the ones next to it) are for testing models in different formats: https://gitlab.com/unelsson/osgqt_tests/-/blob/master/osgViewerQt_CompositeViewer.cpp#L157

Sidenote: A related issue at osgQt is https://github.com/openscenegraph/osgQt/issues/37 . Note thought that the bug is confirmed to be present also in the old osgQt::GraphicsWindowQt, using CompositeViewer and QGLWidget with Qt4. This is confirmed in project OpenMW-CS.

**Comment by unelsson** [comment]
This OpenMW-issue shows screenshots in OpenMW/OpenSceneGraph and in OpenMW-CS/OSG via OsgQt. All three collada models are corrupted with osgQt.
https://gitlab.com/OpenMW/openmw/-/issues/5713

**Comment by unelsson** [comment]
While investigating this, I converted dae-plugin's osg::Geode to osg::Group https://github.com/unelsson/OpenSceneGraph/tree/daeplugingeodetogroup . It's based on OpenMW's fork, so it won't merge directly, but in case this is needed, I can make another PR later.

The original issue still exists. It's seems to be specific to dae-plugin with Qt.

**Comment by robertosfield** [comment]
I am neither an Qt or Collanda expert but when seeing odd interactions between things that should be entirely decoupled like Qt usage and Collada the areas I'd suggest looking at are:
  1) Could there be a io sensitivity to local being applied by Qt, ie. Collada loader assumes default C locale but Qt sets a non default C locale.   One way to test this would be to use osgconv to convert the .dae file to .osgt then, compare the same model loaded and written to .osgt from within the Qt application.

  2) Qt is changing OpenGL modes so that the state when the OSG gets called is an indeterminate sate that the OSG is completely unaware of. Use of the osg::State::haveApplied*() methods or osg::State::dirtyAllModes() are ways to tell the OSG that modes have changed externally to the OSG.

**Comment by unelsson** [comment]
>     1. Could there be a io sensitivity to local being applied by Qt, ie. Collada loader assumes default C locale but Qt sets a non default C locale.   One way to test this would be to use osgconv to convert the .dae file to .osgt then, compare the same model loaded and written to .osgt from within the Qt application.

Comparing the files written to .osgt from Qt application and the file created by osgconv, I see that all decimals are missing. That might indeed be a locale problem, but the problem persists even when setting the QT locale to C, with `QLocale::setDefault(QLocale::C);`. Something is nonetheless going bad with the string/stream handling. This is a very useful find, there's now a clue what to look for.
 
>     2. Qt is changing OpenGL modes so that the state when the OSG gets called is an indeterminate sate that the OSG is completely unaware of. Use of the osg::State::haveApplied*() methods or osg::State::dirtyAllModes() are ways to tell the OSG that modes have changed externally to the OSG.

I tested calling `osg::State::dirtyAllModes()`, but it doesn't seem to fix this particular problem.

**Comment by unelsson** [comment]
Solution was found here: https://doc.qt.io/qt-5/qcoreapplication.html
"On Unix/Linux Qt is configured to use the system locale settings by default. This can cause a conflict when using POSIX functions, for instance, when converting between data types such as floats and strings, since the notation may differ between locales. To get around this problem, call the POSIX function setlocale(LC_NUMERIC,"C") right after initializing QApplication, QGuiApplication or QCoreApplication to reset the locale that is used for number formatting to "C"-locale."

Phew! Thanks a lot @robertosfield .

**Comment by robertosfield** [comment]
It may be appropriate to set the local in the Collada plugin or in Collada
itself.  The OSG handles this issue by doing for input:

           fin.imbue(std::locale::classic());

And for writing:

                fout.imbue(std::locale::classic());

You could try adding this into the OSG's dae plugin to see if it works.  I
can't test the problem so it'd be worth you doing it.  If it works generate
a PR for the OSG.
