### ISSUE TITLE
Texture cropping

### ISSUE THREAD

**Issue by BillVicky** [openscenegraph/OpenSceneGraph#1008]
I used OSG to crop a 3D model, and I have deleted the unnecessary triangulation and reconstructed the boundary triangulation. But how to deal with redundant texture information?

**Comment by robertosfield** [comment]
Please use the osg-users googlegroup for general support.  When you do post your question to osg-users please provide enough information to allow others to help you, the above "how to deal with redundent texture information" is essentially meaningless.

**Comment by BillVicky** [comment]
> Please use the osg-users googlegroup for general support. When you do post your question to osg-users please provide enough information to allow others to help you, the above "how to deal with redundent texture information" is essentially meaningless.

thank you
