### ISSUE TITLE
Why osg::Text3D changed it's behaviour for osg::TriangleFunctor?

### ISSUE THREAD

**Issue by marcobeninca71** [openscenegraph/OpenSceneGraph#1009]
Hello everybody,
I switched recentely to osg 3.6.5 from 3.6.3 and I noticed a change of behaviour of osg::Text3D when accepted by osg::TriangleFunctor

In 3.6.3 the code below

```
osg::ref_ptr<osgText::Text3D> text3d = new osgText::Text3D;
text3d->setFont(fontFile);
text3d->setCharacterSizeMode(osgText::Text3D::CharacterSizeMode::OBJECT_COORDS);
text3d->setCharacterSize(height);
text3d->setCharacterDepth(extrusionLength);
text3d->setAxisAlignment(osgText::TextBase::AxisAlignment::XY_PLANE);
text3d->setAlignment(osgText::TextBase::AlignmentType::CENTER_CENTER);
text3d->setText("Test");
text3d->setPosition(osg::Vec3d(0.0, 0.0, 0.0));

osg::Matrix tras = text3d->getMatrix();

// Convert drawable to geometry
osg::TriangleFunctor<TextGeometry> tf;
tf.vertices = textGeometry->getOrCreateVertexArray();
tf.normals = textGeometry->getOrCreateNormalArray();
tf.matrix = tras;
text3d->accept(tf);

```

creates a text with "Test" centered on the origin with size equal to ```height``` and extruded by a distance equal to ```extrusionLength```. To get the real world coords of the verticies  inside the operator () of my TextGeometry class I need to apply the transformation obtained by ```text3d->getMatrix();```

```
struct TextGeometry
{
	osg::Matrix matrix;

	osg::ref_ptr<osg::Vec3Array> vertices;
	osg::ref_ptr<osg::Vec3Array> normals;
	inline void operator () (const osg::Vec3f& _v1, const osg::Vec3f& _v2, const osg::Vec3f& _v3)
	{
		osg::Vec3f vV1V2 = _v2 - _v1;
		osg::Vec3f vV1V3 = _v3 - _v1;
		osg::Vec3f normal = vV1V2.operator ^(vV1V3);
		normal.normalize();
		osg::Vec3f vv1 = (_v1 * matrix);
		osg::Vec3f vv2 = (_v2 * matrix);
		osg::Vec3f vv3 = (_v3 * matrix);
		if (vertices)
		{
			vertices->push_back(vv1);
			vertices->push_back(vv2);
			vertices->push_back(vv3);
		}
		if (normals)
		{
			normals->push_back(normal);
			normals->push_back(normal);
			normals->push_back(normal);
		}
	}
};

```
Now in osg 3.6.5 to get the same values for the verticies I have not to apply the transformation, otherwise I get wrong coords which are scaled and offset along Z axis (the text is not on Z = 0)

This is a behavior that breaks the backward compatibility. Is it a aware choice?

Regards
Marco

**Comment by openscenegraph** [comment]
I consider this a bug fix.  Having to account for an internal
implementation details of a Drawable breaks encapsulation.

>

**Comment by marcobeninca71** [comment]
Sorry but I don't understand if the new behaviour fixes a bug (so it isn't going to be changed) or it is a bug (so it's going to be changed back to the 3.6.3 version)
thanks
Marco

**Comment by robertosfield** [comment]
On Thu, 10 Dec 2020 at 06:59, Marco Benincà <notifications@github.com>
wrote:

> Sorry but I don't understand if the new behaviour fixes a bug (so it isn't
> going to be changed) or it is a bug (so it's going to be changed back to
> the 3.6.3 version)
>
It's working correctly in 3.6.5.
