### ISSUE TITLE
std::atomic backend

### ISSUE THREAD

**Issue by glebm** [openscenegraph/OpenSceneGraph#1022]
Would it make sense to add an std::atomic backend? Or even replace all the existing ones with it?

`std::atomic` is standard in C++11 and above

**Comment by robertosfield** [comment]
So far I've kept the OSG working against older C++ version as some users are stuck on systems that won't support C++11.

It may be that for future stable releases we could just make C++11 a minimum and just replace use of OpenThreads completely.  For the VulkanSceneGraph I've used C++11 threading and it works really nicely.

However, right now my focus is getting VulkanSceneGraph to 1.0, with the OSG in maintenance mode so am avoid new significant feature development in the OSG.

**Comment by glebm** [comment]
Noted.

If someone decides to revive this, here is a patch that replaces all backend implementations except Mutex with `std::atomic`: https://gitlab.com/OpenMW/openmw-android/-/blob/841887fc55bccb75f9de6a968035bbcd8aaca0ac/buildscripts/patches/osg/0001-Replace-Atomic-impl-with-std-atomic.patch
