### ISSUE TITLE
glRenderbufferStorageMultisampleCoverageNV used on Mesa, despite not having NV_framebuffer_multisample_coverage

### ISSUE THREAD

**Issue by AnyOldName3** [openscenegraph/OpenSceneGraph#1028]
`glRenderbufferStorageMultisampleCoverageNV` is provided by the [`NV_framebuffer_multisample_coverage`](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_framebuffer_multisample_coverage.txt) extension for implementing what Nvidia call [Coverage Sampled Antialiasing](https://developer.download.nvidia.com/SDK/9.5/Samples/DEMOS/Direct3D9/src/CSAATutorial/docs/CSAATutorial.pdf). It's used in OSG by [`osg::RenderBuffer::getObjectId`](https://github.com/openscenegraph/OpenSceneGraph/tree/40bddd8d9532620dc704adce0d2fb0c854d62d0f/src/osg/FrameBufferObject.cpp#L138-L145) following a check to `osg::GLExtensions::isRenderbufferMultisampleCoverageSupported()` in favour of the non-vendor-specific `glRenderbufferStorageMultisample`.

`osg::GLExtensions::isRenderbufferMultisampleCoverageSupported()` just checks whether or not the function pointer is null, which fails on Mesa as it exports the function, despite not implementing the relevant extension, and OSG doesn't check before setting the function pointer [here](https://github.com/openscenegraph/OpenSceneGraph/tree/40bddd8d9532620dc704adce0d2fb0c854d62d0f/src/osg/GLExtensions.cpp#L1097). It seems that on Mesa, the call is a no-op, as I get incomplete FBO errors when OSG uses that path, but not if I replace the call with the non-coverage variant, and I can't find an actual implementation in the Mesa source, but can for the regular variant.

I expect that the most sensible solution would be to check for the presence of the actual extension, either before setting the function pointer or in `isRenderbufferMultisampleCoverageSupported`.

**Comment by glebm** [comment]
@robertosfield I can work on a PR for this if you have a preferred solution in mind

Should this be another boolean field or two in https://github.com/openscenegraph/OpenSceneGraph/blob/master/include/osg/GLExtensions, like the other extension checks are done?
