### ISSUE TITLE
Possible data race in the Geometry::setTexCoordArray()

### ISSUE THREAD

**Issue by akortunov** [openscenegraph/OpenSceneGraph#1036]
Hello. In OpenMW we use arrays, shared between different geometries:

```
// Main thread, initialization:
osg::ref_ptr<osg::Vec2Array> texArray (new osg::Vec2Array);
texArray->setVertexBufferObject(new osg::VertexBufferObject);
texArray->setBinding(osg::Array::BIND_PER_VERTEX);

// Fill texArray elements and store it in the threadsafe cache, launch background threads.
...

// Background thread #1
geometry1->setTexCoordArray(0, texArray);

// Background thread #2
geometry2->setTexCoordArray(0, texArray);
```

The issue is that `setTexCoordArray` [always writes to the array binding variable](https://github.com/OpenMW/osg/blob/ecedf3232c2f1b3b6a2f06f77ea37a9afb6a93f5/src/osg/Geometry.cpp#L247). Even if an  old value is the same as the new value, it is still an undefined behaviour to modifly the same variable from different threads in the same time, and thread sanitizers complain about it. Is it possible to modify the binding only of it was actually changed?

**Comment by openscenegraph** [comment]
The OSG doesn't not support multi-threading writing to the same data
structures.  There are circumstances where you can get away with it but
it's not general, and not officially supported.

As for adding an extra if statement to only make a change when it happens,
this is added extra CPU work and extra code complexity for us to maintain
to just shut up a thread sanitizer that is complaining about an unsupported
use of the OSG.  Yeah.. that's not a valid thing to do.

Robert.

**Comment by AnyOldName3** [comment]
I don't think the snippet here is *trying* to write to the same data structure from multiple threads. `texArray` is wholly set up from a single thread, and `geometry1` and `geometry2` are each being set up on a single thread. They're just both referencing `texArray`, which is normal for a sensibly-written application trying to avoid redundant state switches, and the OSG's doing the writing to that multiple times even though it's unwanted and unnecessary here.

I think I see a way around the problem, though. The equivalent call isn't present in `setTexCoordArrayList`, so if only the one set of texture coordinates is used, `geometry1->setTexCoordArrayList({texArray})` should do what akortunov wants without the same data being written to multiple times, no matter how many threads are in play.

**Comment by akortunov** [comment]
This particular use case is worked around from OpenMW side.
