### ISSUE TITLE
Without fixed functionality osgText::Text wont show, but osgText::Text3D works

### ISSUE THREAD

**Issue by deping** [openscenegraph/OpenSceneGraph#1060]
Hi OSG guys,
  I compiled OSG-3.6.2 x64 without fixed functionality.
  I tested example osgtext, osgText::Text is invisible.
  When I replace Text with Text3D, osgText::Text3D is visible.

Thanks for your work!
Regards.

**Comment by robertosfield** [comment]
Could you please try 3.6.5 as this is the latest supported release, or try the 3.6 branch these include improvements of osgText.

**Comment by deping** [comment]
I use OSG 3.7.0, the bug still exist.

**Comment by robertosfield** [comment]
osgText::Text now has shaders that is no longer reliant on the fixed function pipeline.  You must have configured your build of the OSG or how you set things up at runtime to break it.  You don't provide any details of what you mean by "without fixed function" so we can't speculate on what you have done that is causing problem.
