### ISSUE TITLE
osg::ClipPlane has wrong behaviour.

### ISSUE THREAD

**Issue by fililili** [openscenegraph/OpenSceneGraph#1061]
ClipPlane will be influenced by previous matrix, here is an example.

#include <osgViewer/Viewer>
#include <osg/ClipPlane>
#include <osg/MatrixTransform>
#include <osgDB/ReadFile>
int main()
{
	osgViewer::Viewer viewer;

	osg::ref_ptr<osg::Group> group = new osg::Group;
	group->addChild(osgDB::readNodeFile("cow.osg"));

	osg::ClipPlane* clipPlane = new osg::ClipPlane;
	clipPlane->setClipPlane(0.0f, 1.0f, 0.0f, 0.0f);
	clipPlane->setClipPlaneNum(0);
	group->getOrCreateStateSet()->setAttributeAndModes(clipPlane);

	osg::ref_ptr<osg::MatrixTransform> matrixNode1 = new osg::MatrixTransform;
	matrixNode1->setMatrix(osg::Matrix::translate(5.0f, 5.0f, 5.0f));
	//matrixNode1->setMatrix(osg::Matrix::translate(5.0f, 15.0f, 5.0f));

	// if we use this line, the group under matrix2 and matrix3 will disappear,
	// however, change matrix1 should not influence group under matrix2 and
	// matrix3 for they have no relationships. I think this is a bug.
	matrixNode1->addChild(group);

	osg::ref_ptr<osg::MatrixTransform> matrixNode2 = new osg::MatrixTransform;
	matrixNode2->setMatrix(osg::Matrix::translate(-5.0f, 5.0f, 5.0f));
	matrixNode2->addChild(group);

	osg::ref_ptr<osg::MatrixTransform> matrixNode3 = new osg::MatrixTransform;
	matrixNode3->setMatrix(osg::Matrix::translate(-15.0f, 5.0f, 5.0f));
	matrixNode3->addChild(group);

	osg::ref_ptr<osg::Group> root = new osg::Group;
	root->addChild(matrixNode1);
	root->addChild(matrixNode2);
	root->addChild(matrixNode3);

	viewer.setSceneData(root);

	return viewer.run();
}

**Comment by robertosfield** [comment]
glClipLane/osg::ClipPlane is positional state should be placed into the
scene with a osg::ClipNode.  It should not be used independently by just
attaching to an osg::StateSet as this defeats any controlling of the
modelview matrix when it's applied.  See the osgclip example for proper
usage of osg::ClipPlane.
