### ISSUE TITLE
After loading a large model, the first rotation of camera in the scene will cause the frame rate to drop from 60fps to 10fps

### ISSUE THREAD

**Issue by youmeiyounicheng** [openscenegraph/OpenSceneGraph#1068]
After loading a large model, the first rotation of camera in the scene will cause the frame rate to drop from 60fps to 10fps.
How to solve this problem?

**Comment by robertosfield** [comment]
On Mon, 7 Jun 2021 at 04:57, youmeiyounicheng ***@***.***>
wrote:

> After loading a large model, the first rotation of camera in the scene
> will cause the frame rate to drop from 60fps to 10fps.
> How to solve this problem?
>
The Issue tracker is really for bugs in the OSG not helping users with
optimizing their applications.  Could you please use the osg-users google
group for general support.

https://groups.google.com/g/osg-users
