### ISSUE TITLE
How can I write out high level of details obj

### ISSUE THREAD

**Issue by HappyKuTou** [openscenegraph/OpenSceneGraph#1077]
I use objreaderwriter to convert osgb to obj, but I get not enough details, how can I convert all sub pagedLod

**Comment by robertosfield** [comment]
On Fri, 6 Aug 2021 at 10:08, HappyKuTou ***@***.***> wrote:

> I use objreaderwriter to convert osgb to obj, but I get not enough
> details, how can I convert all sub pagedLod
>
You can't.

.obj is a very old and simple format, it can't possibly handle all the
capabilities of a full featured scene graph.

The best you can do is pick out subgraphs that will convert across for you
needs, as long as those needs are very minimal.
