### ISSUE TITLE
overloaded isinf at src/osgPlugins/osgjs/json_stream

### ISSUE THREAD

**Issue by proyan** [openscenegraph/OpenSceneGraph#108]
Hi

When installing osg version 3.4, I get the following error:

`~/git/misc/osg/src/osgPlugins/osgjs/json_stream: In member function 'double json_stream::to_valid_float(double)':
~/git/misc/osg/src/osgPlugins/osgjs/json_stream:98:18: error: call of overloaded 'isinf(const double&)' is ambiguous
~/git/misc/osg/src/osgPlugins/osgjs/json_stream:98:18: note: candidates are:
/usr/include/i386-linux-gnu/bits/mathcalls.h:203:1: note: int isinf(double)
/usr/include/c++/4.6/cmath:534:3: note: bool std::isinf(long double)
/usr/include/c++/4.6/cmath:530:3: note: bool std::isinf(double)
/usr/include/c++/4.6/cmath:526:3: note: bool std::isinf(float)`

My system information is:
gcc 4.6.4
Ubuntu 12.04 32bit
cmake 2.8.7

I have edited the source to std::isinf instead for now in my system

**Comment by openscenegraph** [comment]
I have checked in a change to the code so that it explicitly uses std:: which referenes the isinf and isfinite function.  See commit 78300f7..912e4f8
