### ISSUE TITLE
mouse click event overlap

### ISSUE THREAD

**Issue by HappyKuTou** [openscenegraph/OpenSceneGraph#1085]
I write a node picker, after pick a object, I enable a TranslateAxisDragger, but when I click the dragger, the pick event is working at the same time, how can I make this 2 events mutually exclusive, disable one event when I trigger another event

**Comment by robertosfield** [comment]
Events have a handled flag that you can set when it's been handled, but
it's up to an event handler to check the handled flag.

**Comment by HappyKuTou** [comment]
thanks, is there a code example that I can learn, I don't know how to check the flag

**Comment by HappyKuTou** [comment]
I understand how to use it, thank you very much
