### ISSUE TITLE
Profiler/FPS Overlay Change

### ISSUE THREAD

**Issue by calhix** [openscenegraph/OpenSceneGraph#1108]
Hello, I want to thank every one of you that make this engine possible. Without it we wouldn't have OpenMW as it is today which is why I'm coming here. Would it be possible to change the FPS display when pushing F3 so instead of it saying Frame Rate: XX, it would just have the number there? Even better, it would be nice if it was just the whole number (no decimal to the hundredths place, unless maybe under 10 FPS or something). Thank you.

**Comment by sbrkopac** [comment]
You'd probably just be better suited to implement your own StatsHandler. If it's just a label change what is the win there?

**Comment by calhix** [comment]
> You'd probably just be better suited to implement your own StatsHandler. If it's just a label change what is the win there?

I would just prefer the extra real estate, I'm not too proficient at coding so I'm unsure how I would go about it. I've talked with a few others that agreed so thought I would come here. If you don't agree that's cool but I thought it would be nice to at least make it so it just says XX FPS instead if you want it to be clear what the number is for.

**Comment by robertosfield** [comment]
If you don't like the core StatsHandler then simply create your own one.
The StatsHandler code is all open source so you can use it as an example of
how to do it, or even subclass from it and customise to your own needs.
