### ISSUE TITLE
osg::Viewer stops rendering (FlightGear 2020.4)

### ISSUE THREAD

**Issue by legoboyvdlp** [openscenegraph/OpenSceneGraph#1112]
I've been having an issue with FlightGear 2020.4 with OpenSceneGraph 3.6 for some time. I'm the only user -- so far -- to reproduce this so it must be hardware specific. I'm running FlightGear 2020.4 on Windows 11 - however, the issue occurred on Windows 10 as well.

Essentially what happens, is that FlightGear 2020.4 will stop rendering. The program doesn't freeze. It keeps responding to commands (e.g. keyboard). However, it will not render the next frame; what's displayed on the screen just stays the same.

I've done a fairly extensive debugging session with breakpoints and as best I can tell all of FlightGear's code is running normally.
My best guess is that something is going wrong within osg::Viewer - either in osg's own code, or in the part where FlightGear talks to OSG.

I would appreciate any suggestions as to how to debug this or any ideas.

Hardware: Intel(R) Iris(R) Xe Graphics
Open GL: 4.6.0 - Build 27.20.100.8439

**Comment by robertosfield** [comment]
Given other FlightFear users aren't seeing this problem it may well not be a problem with either FlightGear or the OSG.

I would start with trying different OpenGL drivers and if possible different hardware combinations to see if there is any change in behavior.  As a general note, Intel's OpenGL hasn't enjoyed a great reputation over the years and could easily just be falling over all by itself.
