### ISSUE TITLE
cirtical bug found in 3.6.5 or earlier 

### ISSUE THREAD

**Issue by XDinEuro** [openscenegraph/OpenSceneGraph#1130]
I was using openscenegraph 3.4 before, it was super smooth. Recently I am migrating my project to osg 3.6.5 and I found a weird bug about not being able to zoom in or out when wheeling mouse.

And I locate the issue to minimum example.

```
#include <osg/Group>
#include <osg/Node>
#include <osgDB/ReadFile>
#include <osgViewer/Viewer>
#include <osgGA/TrackballManipulator>

int main(int argc, char** argv)
{
    osg::ref_ptr<osgViewer::Viewer> viewer = new osgViewer::Viewer();
    viewer->setUpViewInWindow(0, 0, 640, 480);
    viewer->setCameraManipulator(new osgGA::TrackballManipulator());
    osg::Node* modelNode = osgDB::readNodeFile("cow.osg");
    osg::ref_ptr<osg::Group> root = new osg::Group();
    viewer->setSceneData( root );
    root->addChild(modelNode);
    viewer->realize();
    while(true){
        viewer->frame();
    }
    return 0;
}
```

This will give u a all black view, which is inside the cow. and you can't zoom out... But if you put `root->addChild(modelNode)` one line before,  which means before `viewer->setSceneData(root)`, everything works good. 

If I remove ` viewer->setUpViewInWindow(0, 0, 640, 480); ` , this works again..

Bad View:
![Screenshot from 2022-04-12 12-37-24](https://user-images.githubusercontent.com/51153761/162942329-1289338d-5a47-4092-b571-b112cc59ba01.png)

Normal View;
![Screenshot from 2022-04-12 12-37-47](https://user-images.githubusercontent.com/51153761/162942359-8e6ddc1d-9f71-4355-a457-0a1303ef0f09.png)

I didn't have time to try out in which version it turned out like this. I hope someone can give me some feedback if u know the solution.

**Comment by nmielcarek** [comment]
This is based on memory, but if you assign the scene data with an empty scene, it doesn't know where to place the camera based on the bounding boxes of the not-yet-loaded objects.

If you press spacebar, it re-calculates the scene and places the camera at a new default location. This can also be accomplished using the viewer->home() function.

**Comment by XDinEuro** [comment]
> 

Thanks for the quick reply. It helps.
