### ISSUE TITLE
cow.osg error

### ISSUE THREAD

**Issue by vishwanath377** [openscenegraph/OpenSceneGraph#1137]
osgviewer cow.osg
void StateSet::setGlobalDefaults() ShaderPipeline disabled.
void StateSet::setGlobalDefaults() ShaderPipeline disabled.
Error reading file cow.osg: file not found
osgviewer: No data loaded

I am getting this error when trying to run osgviewer.

**Comment by robertosfield** [comment]
On Tue, 10 May 2022 at 06:40, vishwanath377 ***@***.***>
wrote:

> osgviewer cow.osg
> void StateSet::setGlobalDefaults() ShaderPipeline disabled.
> void StateSet::setGlobalDefaults() ShaderPipeline disabled.
> Error reading file cow.osg: file not found
> osgviewer: No data loaded
>
> I am getting this error when trying to run osgviewer.
>

Ignore the "void StateSet::setGlobalDefaults() ShaderPipeline disabled."
message, this is benign message reported from some experimental code in OSG
master.

The file not found suggests that OpenSceneGraph-Data isn't in your local
directory or not on your OSG_FILE_PATH env var.
