### ISSUE TITLE
Load .obj's texture.png file fail:  Error reading file texture.png: not implemented

### ISSUE THREAD

**Issue by HWZen** [openscenegraph/OpenSceneGraph#1142]
platform: windows10

osg version: 3.6.5 get from vcpkg

Can load obj model but without texture, osg show
`Error reading file path/to/texture.png: not implemented`
`Error reading file texture.png: not implemented`
2 lines

Process load osgdb_obj.dll
It needs other plugins?

**Comment by LaurensVoerman** [comment]
Did you manage to build the plugins? To get the plugins that depend on
other libs to build, you need to tell vcpackage not only to build osg , but
also the plugins.
command seems to be something like:
vcpkg install osg[plugins,tools]
Laurens.

**Comment by HWZen** [comment]
Yes, It needs libpng and libjpeg, but vckpg did not build them automated.
I rebuild osg when I install libpng and libjpeg, it works fine now.
