### ISSUE TITLE
load cow.osg has no texture

### ISSUE THREAD

**Issue by xuqingquan1995** [openscenegraph/OpenSceneGraph#1143]
I run osg3.7 on Android, but failed to load the texture successfully

**Comment by LaurensVoerman** [comment]
Just a wild guess: reflection mapping (as used by the cow) doesn't work on OpenGL ES. To get the cow to show up as intended you will have to provide a shader.
Laurens.

**Comment by vsg-dev** [comment]
When building for OpenES that shader util class that maps a subset of the GL 1.x fixed function pipeline to shaders doesn't include support for spherical tex gen that cow.osg uses.  So not seeing cow.osg appear is normal and expected.  When working with OpenES you'll need to provide your own GLSL shaders for you application/data needs.

**Comment by xuqingquan1995** [comment]
I am running osgAndroidExampleGLES3. It seems that there are shaders in the code

**Comment by robertosfield** [comment]
These shaders won't have support for fixes function spherical texgen. You could add it to your own application if you really needed it.  FYI, cow.osg dates back to the early 2000's.
