### ISSUE TITLE
OSG3.6.5 GDAL dependency library?

### ISSUE THREAD

**Issue by dragonwl737** [openscenegraph/OpenSceneGraph#1159]
I now need to compile 3.6.5, where can I find the version of the dependency library,(etc GDAL)

**Comment by robertosfield** [comment]
I'm afraid we haven't maintained version requirements for all optional dependencies.

This is what I have on my Kubuntu 21.10 system and have just done a test build of OSG-3.6.5:

$ gdal-config --version
3.2.2

**Comment by dragonwl737** [comment]
> I'm afraid we haven't maintained version requirements for all optional dependencies.
> 
> This is what I have on my Kubuntu 21.10 system and have just done a test build of OSG-3.6.5:
> 
> $ gdal-config --version 3.2.2
thanks reply
