### ISSUE TITLE
osg3.6.5 build osgqt 

### ISSUE THREAD

**Issue by dragonwl737** [openscenegraph/OpenSceneGraph#1160]
When I compile osgqt, the system prompts that the string atmoic cannot be found. It is not a complete type. Maybe the case of the file name cannot be correctly distinguished under Windows. After manually modifying the file name, it seems to work (is there any way to distinguish the file name). Then, there is an error osgQOpenGL\__\__\include\osgQOpenGL\moc_osgQOpenGLWidget.cpp:64:6: error: 'osgQOpenGLWidget' has not been declared. How to modify the reference path with CMAKE-GUI?

**Comment by robertosfield** [comment]
Please post this Issue on the osgQt github Issue tracker.
