### ISSUE TITLE
build 3.6 branch by cmake with OSG_GL3_AVAILABLE

### ISSUE THREAD

**Issue by KaiTang2** [openscenegraph/OpenSceneGraph#1161]
when I set OSG_GL3_AVAILABLE true ,the example(like osgbillboard)  not display, only purple background.Set GL3 false,GL1 and GL2 true,it can display normally. How should I do.(Other configurations in cmake use the default configuration. 
OS:windows11-x64
OpenGL version:4.6
Graphics card: NVIDIA 1650 SUPER )

Thanks

**Comment by robertosfield** [comment]
GL3 core profile does not supoort fixed function pipeline so can't render all scenes.  You have to just use scene graphs built for shaders.

**Comment by KaiTang2** [comment]
Is there any example ? I don't understand what "You have to just use scene graphs built for shaders" means.(Maybe it's my translation) @robertosfield

**Comment by openscenegraph** [comment]
On Mon, 15 Aug 2022 at 08:47, KaiTang2 ***@***.***> wrote:The

> Is there any example ? I don't understand what "You have to just use scene
> graphs built for shaders" means.(Maybe it's my translation)
>

osgsimplegle3 is one place to start.

There has been lots of discussions on vsg-users about shaders and GL core
profile.

The Issue tracker is for bugs not teaching so subscribe to osg-users group
and post your question there.

**Comment by KaiTang2** [comment]
I'm sorry. It won't happen again. @openscenegraph
