### ISSUE TITLE
Openscenegraph has few files with GPL-2.0 and GPL-2.0+

### ISSUE THREAD

**Issue by nikitha-kiran** [openscenegraph/OpenSceneGraph#1162]
Hi,

Can I know how the GPL-2.0 and GPL-2.0+ files are being used inside openscenegraph  ?
Does it impact the license of openscenegraph?

Thanks

**Comment by nikitha-kiran** [comment]
I see that you closed the ticket without response. Would you prefer this question over mailing list ?

**Comment by robertosfield** [comment]
I replied, but it seems github ate it, this is what I wrote:

On Thu, 25 Aug 2022 at 08:14, nikitha-kiran <[notifications@github.com](mailto:notifications@github.com)> wrote:

    can I know how is it being used inside openscenegraph is it separate work or linked in any way ?

It's just specific plugins, you needn't use of compile then.  The license is in the local plugin source directly.

**Comment by nikitha-kiran** [comment]
Hi Thanks for information but I see few files in other folders as well which have GPL-2.0 and GPL-2.0+ please let me know?

OpenSceneGraph-OpenSceneGraph-3.6.5.zip/OpenSceneGraph-OpenSceneGraph-3.6.5/src/osgPresentation/SlideShowConstructor.cpp


OpenSceneGraph-OpenSceneGraph-3.6.5.zip/OpenSceneGraph-OpenSceneGraph-3.6.5/examples/osganimationviewer/AnimtkViewerKeyHandler
OpenSceneGraph-OpenSceneGraph-3.6.5.zip/OpenSceneGraph-OpenSceneGraph-3.6.5/examples/osganimationviewer/AnimtkViewerGUI
OpenSceneGraph-OpenSceneGraph-3.6.5.zip/OpenSceneGraph-OpenSceneGraph-3.6.5/examples/osganimationviewer/AnimtkViewerKeyHandler.cpp

**Comment by nikitha-kiran** [comment]
Any update please?

**Comment by robertosfield** [comment]
src/osgPresentation/SlideShowConstructor.cpp should be OSGPL, I've checked in a fixed this into the OpenScneneGraph-3.6 and MeshShaders branches and master.

The example isn't written by me so I can't change the Copyright notice, but it's just an example that has no impact on the OpenScneneGaph libraries that applications may link to so it's a non issue.

**Comment by robertosfield** [comment]
On Thu, 25 Aug 2022 at 08:14, nikitha-kiran ***@***.***>
wrote:

> can I know how is it being used inside openscenegraph is it separate work
> or linked in any way ?
> Message ID: ***@***.***>

It's just specific plugins, you needn't use of compile then.  The license
is in the local plugin source directly.
