### ISSUE TITLE
Why allow Geode to call Goup::addChild()

### ISSUE THREAD

**Issue by jingjianjie** [openscenegraph/OpenSceneGraph#1163]
I'm curious about the public method `addChild()` of `Gourp` class.
It can be called by `geode` instance which defined as "leaf"

why allow this ambiguous semantic (i.e. `geode->addchild()` )？
why not prevent this behaviour？
why the framework of `Node-group-child` is designed as so?
thanks if anyone help me!~

**Comment by openscenegraph** [comment]
Please search the osg-users group for an explanation,
