### ISSUE TITLE
The problem of random crashes when creating osg::Text with multiple threads

### ISSUE THREAD

**Issue by sosopop** [openscenegraph/OpenSceneGraph#1168]
platform: windows10
osg version: 3.6.5

when I use multithreading to create multiple osg::Text nodes, it will cause random crashes. I found the following URL and the same problem occurs
https://www.mail-archive.com/osg-users@lists.openscenegraph.org/msg77845.html

Finally I found an operation on shared statesets in the Text::createStateSet method, but without locking. It will cause multiple threads to create osg::Text at the same time for the first time after startup, which will cause a crash.
`
    if (!statesets.empty())
    //...............
    osg::ref_ptr<osg::StateSet> stateset = new osg::StateSet;
    stateset->setDefineList(defineList);

    statesets.push_back(stateset.get());
    //crash ^^^^^^^^^^^

    stateset->setRenderingHint(osg::StateSet::TRANSPARENT_BIN);
    stateset->setMode(GL_LIGHTING, osg::StateAttribute::OFF);
    stateset->setMode(GL_BLEND, osg::StateAttribute::ON);
`

**Comment by magnetic-eagle** [comment]
The flight simulator FlightGear has the same problem with it's canvas Text - so it would be really great if this could finally be looked into ! :)

**Comment by robertosfield** [comment]
osgText is not designed to work with multi-threaded creation.

**Comment by magnetic-eagle** [comment]
Oh, I meant multi-threaded rendering - in my case, the text elements are created single-threaded but setting the OSG threading mode to anything but SingleThreaded results in the same type of crashes.
