### ISSUE TITLE
Where have osgText::Text::GlyphQuads::LineNumbers gone ?

### ISSUE THREAD

**Issue by magnetic-eagle** [openscenegraph/OpenSceneGraph#1197]
Before OSG 3.6.5, I was using the following code: 
```
    _quads = &text->_textureGlyphQuadMap.begin()->second;

    GlyphQuads::LineNumbers const& line_numbers = _quads->_lineNumbers;
    GlyphQuads::LineNumbers::const_iterator begin_it =
      std::lower_bound(line_numbers.begin(), line_numbers.end(), _line);

    if( begin_it == line_numbers.end() || *begin_it != _line )
      // empty line or past last line
      return;

    _begin = begin_it - line_numbers.begin();
    _end = std::upper_bound(begin_it, line_numbers.end(), _line)
         - line_numbers.begin();
```
where `text` is an `osgText::Text`. The goal of the above code is to find out the first and last characters that are on a given line (lines are indexed by 0, of course).

Now I'm adding compatibility for OSG >= 3.6.5, and a grep through /usr/include/osgText for "LineNumbers" yielded no results. So, how would I port this code ?

**Comment by TheFGFSEagle** [comment]
The goal of the above code is to find out the first and last characters that are on a given line (lines are indexed by 0, of course).

**Comment by magnetic-eagle** [comment]
If there is no replacement, I could hack a solution together (for the project I'm working on) if someone could tell me which part of a letter the coordinates in osgText::Text::getCoords refer to - top-left, center ?

**Comment by robertosfield** [comment]
Relying upon internal implementation details will generally be open to breaks when the internal implementation is changes.

What is the end result that you want?

**Comment by magnetic-eagle** [comment]
The end result is to get the index of the first and last character of a line, to then be able to find out at which position (in pixels) the cursor of a text editing field needs to be placed, which - once the index of the first and last letters are known - is done with the following code:

```c++
  osg::Vec2 TextLine::cursorPos(size_t i) const
  {
    osg::Vec2 pos(0, _text->_offset.y() + _line * _text->lineHeight());

#if OSG_VERSION_GREATER_OR_EQUAL(3,5,6)
      osgText::TextBase::Coords refCoords = _text->getCoords();
      osgText::TextBase::Coords::element_type &coords = *refCoords.get();
#else
      GlyphQuads::Coords2 refCoords = _quads->_coords;
      GlyphQuads::Coords2::element_type &coords = *refCoords.get();
#endif

      size_t global_i = _begin + i;

      if (global_i == _begin)
          // before first character of line
          pos.x() = coords[_begin * 4].x();
      else if (global_i == _end)
          // After Last character of line
          pos.x() = coords[(_end - 1) * 4 + 2].x();
      else
      {
          float prev_l = coords[(global_i - 1) * 4].x(),
              prev_r = coords[(global_i - 1) * 4 + 2].x(),
              cur_l = coords[global_i * 4].x();

          if (prev_l == prev_r)
              // If previous character width is zero set to begin of next character
              // (Happens eg. with spaces)
              pos.x() = cur_l;
          else
              // position at center between characters
              pos.x() = 0.5 * (prev_r + cur_l);
      }
    return pos;
  }
```
where `i` is the index of a character in that line to get the cursor position for, `_begin` and `_end` are the indices of the first and last character of the line respectively, and `_text` is an `osgText::Text` member (actually a subclass, but that doesn't matter here).

**Comment by robertosfield** [comment]
It's many years since I worked on osgText so can't provide exact answer off the top of my head.  In general what you'll want to do to render a cursor is step through the coord array that is computed for glyph positions that are passed to OpenGL.  

Try stepping through the coord array to find the coords of the glyph you want to mark the cursor at and render the cursor at the same coords.  

There shouldn't be any need to worry about pixel coords, just work from the object coords that text is computing for the glyphs.

You'll need to figure out the details by reviewing the Text.cpp source.
