### ISSUE TITLE
Multi-color osg::Text

### ISSUE THREAD

**Issue by magnetic-eagle** [openscenegraph/OpenSceneGraph#1206]
I want to draw multicolor text - like, the first word is red, the next blue, etc, but without using multiple text objects. Is that possible yet ? If not, how would I override osg::Text::drawImplementation to do this ?

**Comment by magnetic-eagle** [comment]
The start and stop positions for each color are saved in an array.

**Comment by robertosfield** [comment]
osg::Text only supports a single colour per text object.

If you want to implement what you want then you'll need to implement your own text.

With the VulkanSceneGraph you can write a custom vsg::TextLayout that allows you to control  the positions and colours of text glyphs.

**Comment by magnetic-eagle** [comment]
> If you want to implement what you want then you'll need to implement your own text.

And … how would I do that ?

**Comment by robertosfield** [comment]
You'll need to figure out how to do it yourself as I can't provide fine grained support for free to everyone.
