### ISSUE TITLE
Crash when calling dirtyGLObjects()

### ISSUE THREAD

**Issue by ChenKe404** [openscenegraph/OpenSceneGraph#1218]
![image](https://user-images.githubusercontent.com/75658944/231038446-0c8fcf0a-8e91-4351-bc1b-49ab4c0b0ce7.png)
I calling dirtyGLObjects() after vertex data changed ,but sometime program will crash at here:
![image](https://user-images.githubusercontent.com/75658944/231038802-ac0177c7-fd24-423a-8c80-58f383f2670b.png)
pointer "osg::VertexArrayState*" not null and not accessible.
i don't know why

**Comment by ChenKe404** [comment]
my class sc::Vertex is subclass of osg::Geometry
![image](https://user-images.githubusercontent.com/75658944/231039944-7555f0c3-1d54-4191-8437-4f6d32c495cc.png)
this is constructor

**Comment by robertosfield** [comment]
The the bug is likely caused by the subclass setup that is breaking the rules that osg::Geometry follows.  What this might be we won't be able to say as we don't have your code, your data or how it's used.  You have all this information so you'll need to step through yourself and investigate.

If you care create a stand alone example the reproduces the issue then we will be able to investigate.

**Comment by ChenKe404** [comment]
I found out that it was because I calling “dirtyGLObjects()” before setup vertext array and primitive set. Is that the reason?
Besides, I want to know 0 count "DrawArrays" will be release by osg::ref_ptr ? 
sorry, my english not good.

**Comment by robertosfield** [comment]
On Tue, 11 Apr 2023 at 08:46, ChenKe ***@***.***> wrote:

> I found out that it was because I calling “dirtyGLObjects()” before setup
> vertext array and primitive set. Is that the reason?
> Besides, I want to know 0 count "DrawArrays" will be release by
> osg::ref_ptr ?
> sorry, my english not good.
>
If any class subclass from osg::Object that are allocated on the heap and
managed by ref_ptr<> the object will be deleted automatically once the
referenceCount() goes to zero.

**Comment by ChenKe404** [comment]
this is my class main code.
sorry,i can't create example, because project file too much,create example is difficulty

#include "Vertex.h"

#include <osg/Point>

sc::Vertex::Vertex(osg::Vec3Array* vertices)
    : _highlight(-1),
      _vertices(vertices)
{
    //the var "vertices" is parent's vertex array pointer.
    //vertex array is empty (not null pointer) on construct.
    //this class must use parent's vertex array,because this class need to control parent's vertex
    setVertexArray(_vertices);
    setDataVariance(osg::Object::DYNAMIC);

    _colors = new osg::Vec4Array();

    setColorArray(_colors);
    setColorBinding(osg::Geometry::BIND_PER_VERTEX);

    //if I do this right here , will crash at getPrimitiveSet(0),cause Drawable member "_primitives[0]" pointer is 0x3f8000003f800000.
    //it's mean when i set PrimitiveSet count is zero,then osg will release this PrimitiveSet ?
    //but why pointer value is 0x3f8000003f800000 ? and why _primitives not empty ?
    // addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::POINTS, 0, 0));

    _size = new osg::Point(10);

    setColor(DEFAULT_LIGHT);
}

void sc::Vertex::highlight(int index)
{
    if((index < 0 && _highlight < 0) || index == _highlight || index >= count())
        return;
    else if(index < 0 && _highlight >= 0)
    {
        setColor(_color);
        _highlight = -1;
    }
    else
    {
        setColor(_color);
        _colors->at(index) = HIGHLIGHT(_color);
        _highlight = index;
    }

    //avoid calling dirtyGLObjects() before vertex array is empty,if not,will crash at "dirtyGLObjects() > getDrawElementsList() case itr._ptr = 0x3f8000000x3f800000"
    if(getVertexArray() && getVertexArray()->getNumElements() > 0)
        dirtyGLObjects();
}

int sc::Vertex::count()
{
    return getVertexArray()->getNumElements();
}

void sc::Vertex::add(const osg::Vec3d & point)
{
    _vertices->push_back(point);
    _colors->push_back(_color);

    if(getPrimitiveSetList().empty())
    {
        //I need do this right here not constructor,if not,will crash at "addPrimitiveSet() > dirtyGLObjects()" like function "highlight()" .
        //or crash at getPrimitiveSet(0),cause Drawable member "_primitives[0]" pointer is 0x3f8000003f800000 .
        //but i do this right here, sometime will crash at "addPrimitiveSet() > Drawable::dirtyGLObjects() > vas->dirty() case vas = 0x3f8000000x3f800000"
        addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::POINTS, 0, count()));
        getOrCreateStateSet()->setAttribute(_size);
        setCullingActive(false);    //当只有一个点时取消裁剪,否则会被osg裁剪而不显示
    }
    else
    {
       auto da = dynamic_cast<osg::DrawArrays*>(getPrimitiveSet(0));
       if(da)
           da->setCount(count());
       if(count() > 1 && !getCullingActive())
            setCullingActive(true);    //多于一个点时启用裁剪
        dirtyGLObjects();
    }
}

**Comment by ChenKe404** [comment]
this is parent class main code , it's subclass by osg::MatrixTransform

sc::Face::Face(const Attribute &att)
    : sc::Entity(att)
{
    setType(sc::Type::FACE);

    auto colors = dynamic_cast<osg::Vec4Array*>(_geo->getColorArray());
    colors->push_back(att.fill);
    _fill = &colors->back();

    //create empty vertex array
    osg::ref_ptr<osg::Vec3Array> vetx = new osg::Vec3Array();
    _geo->setVertexArray(vetx);
    _geo->setDataVariance(osg::Object::DYNAMIC);
    _linewidth = new osg::LineWidth();

    _points = new Vertex(vetx);
}

//add vertex
void sc::Face::add(const osg::Vec3d &p)
{
    if(_children.empty())
    {
        addChild(_geo);
        addChild(_points);
    }

    //add vertex calling Vertex::add to update vertex array
    _points->add(p);

    if(_geo->getPrimitiveSetList().empty())
    {
        //same like class Vertex
        _geo->addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::LINE_LOOP,0,vertexCount()));
        _geo->addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::POLYGON,0,vertexCount()));
        _geo->getOrCreateStateSet()->setAttribute(_linewidth);
        _geo->getOrCreateStateSet()->setMode(GL_BLEND, osg::StateAttribute::ON);
    }
    else
    {
        auto da = dynamic_cast<osg::DrawArrays*>(_geo->getPrimitiveSet(0));
        if(da)
            da->setCount(vertexCount());
        auto da1 = dynamic_cast<osg::DrawArrays*>(_geo->getPrimitiveSet(1));
        if(da1)
            da1->setCount(vertexCount());

        _geo->dirtyGLObjects();
        _geo->dirtyBound();
    }
}

**Comment by ChenKe404** [comment]
I think I found the reason,thanks for your help and patience

**Comment by ChenKe404** [comment]
I think I found the reason,thanks for your help and patience

**Comment by robertosfield** [comment]
Great to hear you've resolved the issue.
