### ISSUE TITLE
Link error with SDL on OSX 10.11

### ISSUE THREAD

**Issue by jbltx** [openscenegraph/OpenSceneGraph#126]
I can't finish the build of osgPlugins/sdl because of linking error.

```sh
[100%] Linking CXX shared module ../../../lib/osgPlugins-3.5.4/osgdb_sdl.so
Undefined symbols for architecture x86_64:
  "_SDL_JoystickNameForIndex", referenced from:
      JoystickDevice::JoystickDevice() in JoystickDevice.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins-3.5.4/osgdb_sdl.so] Error 1
make[1]: *** [src/osgPlugins/sdl/CMakeFiles/osgdb_sdl.dir/all] Error 2
make: *** [all] Error 2
```

It seems SDL is not well linked, but cmake has found it before using `make` command.

Here's the interesting part of CMakeCache.txt

```js
//Path to a file.
SDL2_INCLUDE_DIR:PATH=/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers

//Where the SDL2 Library can be found
SDL2_LIBRARY:STRING=/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa

//Path to a file.
SDL_INCLUDE_DIR:PATH=/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers

//Where the SDL Library can be found
SDL_LIBRARY:STRING=/usr/local/lib/libSDL.dylib;-framework Cocoa

[...]

//Dependencies for the target
osgdb_sdl_LIB_DEPENDS:STATIC=general;OpenThreads;general;osg;general;osgDB;general;osgUtil;general;osgGA;general;/usr/local/lib/libSDL.dylib;general;-framework Cocoa;


[...]


//Details about finding SDL
FIND_PACKAGE_MESSAGE_DETAILS_SDL:INTERNAL=[/usr/local/lib/libSDL.dylib;-framework Cocoa][/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers][v2.0.4()]
//Details about finding SDL2
FIND_PACKAGE_MESSAGE_DETAILS_SDL2:INTERNAL=[/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa][/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers][v()]

[...]

SDL2_LIBRARY_TEMP:INTERNAL=/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa;-framework Cocoa;-framework Cocoa
SDL_LIBRARY_TEMP:INTERNAL=/usr/local/lib/libSDL.dylib;-framework Cocoa;-framework Cocoa;-framework Cocoa

```

I think CMake mixes SDL 1 and 2 but I'm not sure...

**Comment by robertosfield** [comment]
I don't have a OSX system to test against so can only provide a best guess as to what might be wrong. The line: "ld: symbol(s) not found for architecture x86_64" is probably the most crucial one.  Have a look at the binaries type you are building the OSG with and check what is available for SDL.  OSX has support for building for multiple architectures, but not all libs that you link to support both, all depends how they were built. 

The best place to resovle build issues like these is on the osg-users mailing list/forum as this is the official route for support and the place where you get the widest exposure to other members of the community that may have similar systems to yourself and able to help.

**Comment by openscenegraph** [comment]
Revisiting this issue.  SDL not having x86_64 symbols suggest this framework is out of date and should probably be updated.  If not updating it then one should simply disable the SDL vars via ccmake so the SDL plugin doesn't build.  I'm going to close this issue as it looks to be a specific issue to an install of SDL frameworks rather than the OSG itself.  Others can successful using SDL+OSG under OSX suggesting it's not a general problem.

**Comment by podborski** [comment]
> I can't finish the build of osgPlugins/sdl because of linking error.
> 
> ```shell
> [100%] Linking CXX shared module ../../../lib/osgPlugins-3.5.4/osgdb_sdl.so
> Undefined symbols for architecture x86_64:
>   "_SDL_JoystickNameForIndex", referenced from:
>       JoystickDevice::JoystickDevice() in JoystickDevice.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/osgPlugins-3.5.4/osgdb_sdl.so] Error 1
> make[1]: *** [src/osgPlugins/sdl/CMakeFiles/osgdb_sdl.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> It seems SDL is not well linked, but cmake has found it before using `make` command.
> 
> Here's the interesting part of CMakeCache.txt
> 
> ```js
> //Path to a file.
> SDL2_INCLUDE_DIR:PATH=/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers
> 
> //Where the SDL2 Library can be found
> SDL2_LIBRARY:STRING=/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa
> 
> //Path to a file.
> SDL_INCLUDE_DIR:PATH=/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers
> 
> //Where the SDL Library can be found
> SDL_LIBRARY:STRING=/usr/local/lib/libSDL.dylib;-framework Cocoa
> 
> [...]
> 
> //Dependencies for the target
> osgdb_sdl_LIB_DEPENDS:STATIC=general;OpenThreads;general;osg;general;osgDB;general;osgUtil;general;osgGA;general;/usr/local/lib/libSDL.dylib;general;-framework Cocoa;
> 
> 
> [...]
> 
> 
> //Details about finding SDL
> FIND_PACKAGE_MESSAGE_DETAILS_SDL:INTERNAL=[/usr/local/lib/libSDL.dylib;-framework Cocoa][/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers][v2.0.4()]
> //Details about finding SDL2
> FIND_PACKAGE_MESSAGE_DETAILS_SDL2:INTERNAL=[/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa][/Users/mickaelb/Library/Frameworks/SDL2.framework/Headers][v()]
> 
> [...]
> 
> SDL2_LIBRARY_TEMP:INTERNAL=/Users/mickaelb/Library/Frameworks/SDL2.framework;-framework Cocoa;-framework Cocoa;-framework Cocoa
> SDL_LIBRARY_TEMP:INTERNAL=/usr/local/lib/libSDL.dylib;-framework Cocoa;-framework Cocoa;-framework Cocoa
> ```
> 
> I think CMake mixes SDL 1 and 2 but I'm not sure...

@jbltx did you find a solution to this problem?
