### ISSUE TITLE
how to build the example program  by cmake tools?

### ISSUE THREAD

**Issue by daxue2017** [openscenegraph/OpenSceneGraph#1280]
when i download the source-3.6.4, and use cmake tools config it , then use vs2017 comile it , but then fount the example program in the dir examples have not compile, so how to config it and the compile it ?

**Comment by xarray** [comment]
add -DBUILD_OSG_EXAMPLES=ON to commandline arguments, or check the option BUILD_OSG_EXAMPLES in cmake-gui
