### ISSUE TITLE
Fontconfig error: Cannot load default config file: No such file: (null)

### ISSUE THREAD

**Issue by shaozhihua** [openscenegraph/OpenSceneGraph#1282]
my computer X64 intel
Qt5 MSVC2019 compiler
and my code is:
![2584](https://github.com/openscenegraph/OpenSceneGraph/assets/18071679/c3ae6cb7-a64e-4a38-85f1-b39fadf7e1f7)
I tried many methods ,but no works,
so I come here,and ask the author and distributers.
I really appreciate you guys!thanks!

**Comment by shaozhihua** [comment]
I used vcpkg command to install the x64 osg lib;

**Comment by robertosfield** [comment]
I have never used FontConfig personally and the error message looks like it's being emitted from FontConfig rather than the OSG/vsgEarth so the issue may lie with FontConfig setup, in which case you'll need to read up about FontConfig.

**Comment by shaozhihua** [comment]
@robertosfield  oh，I found the solution about this error:
create a new ENVIRNMENT variable：FONTCONFIG_PATH
and the value of this ENV Variable is the path of "fonts.conf".
