### ISSUE TITLE
osgdb::readNodeFile()读文件陷入死循环

### ISSUE THREAD

**Issue by xiahai** [openscenegraph/OpenSceneGraph#1308]
readNodeFile（）读文件一直提示InputIterator::checkStream.FAILED to read from stream.

**Comment by robertosfield** [comment]
The warning message tells you more than we can given you haven't supplied anything about the data source you are trying to read.  If it says FAILED to read stream then there is something amiss with your data source.

**Comment by xiahai** [comment]
> The warning message tells you more than we can given you haven't supplied anything about the data source you are trying to read. If it says FAILED to read stream then there is something amiss with your data source.

它为啥不终止读数据呢

**Comment by robertosfield** [comment]
YOU need to investigate the problem, we can't tell you why YOUR files fail to read on YOUR system.  You have all the source code to the OSG just compile in debug and figure out what is going on.
