### ISSUE TITLE
Texture2D setResizeNonPowerOfTwoHint break  internal format

### ISSUE THREAD

**Issue by Lishen1** [openscenegraph/OpenSceneGraph#132]
when setResizeNonPowerOfTwoHint is set to true, and if texture internal format type is FLOAT (e.g GL_RGBA32F_ARB) it texture behave as NORMALIZED texture. In other worlds, in shader texture2D() return value in range [0, 1], but if setResizeNonPowerOfTwoHint is set to false, all ok.

**Comment by openscenegraph** [comment]
The ReiseNonPowerOfTwoHint is just a hint, it doesn't do anything except to hint to the Texture::apply() that it should or should not rescale non power of two textures.  From your description it sounds like the you have a non power of two texture and the resize hint is on the Texture::apply() will use use gluScaleImage to resize the image to a power of two. I may well be that gluScaleImage simply doesn't support the image format you are using.  

This type of issue is best resolved by discussing things within the wider OSG community so could you please raise this topic of the osg-users mailing list/forum so others can have a bash at reproducing the issue and find a solution if one is warranted.
