### ISSUE TITLE
osg_Normal binding location ?

### ISSUE THREAD

**Issue by msnh2012** [openscenegraph/OpenSceneGraph#1322]
When I test my code on a Nvidia graphic card, the normal array is correct. But, on an Intel graphic card, the normal array is incorrect. 

![91cdeecc65036d1c5df013de0c59ad01](https://github.com/openscenegraph/OpenSceneGraph/assets/17841334/18417545-6ebe-42da-a2af-7eafc5d4859e)

**Comment by robertosfield** [comment]
Could simply be a buggy/non compliant driver. 

You'll likely find Vulkan more portable/better supported than OpenGL.  You'll get better performance and lower overheads as well as the more consistent support across modern platforms.  I have used Intel integrated GPUs with associated Vulkan drivers under Linux and Windows with great success, both on Laptop and Desktop systems.  

The only reason to use OpenGL/OpenSceneGraph these days is if you have a large existing code-base that constrains you moving to more modern API's like Vulkan/[VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph).
