### ISSUE TITLE
Regarding the color space conversion error when reading with the JPG plugin.

### ISSUE THREAD

**Issue by newpeople123** [openscenegraph/OpenSceneGraph#1324]
The JPG plugin will set the internal format of an image suitable for GL_SRGB8 to GL_RGB.

**Comment by robertosfield** [comment]
The OpenSceneGraph is built around RGB colour space.

If you want to work with sRGB then you'll find [VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph) better suited as it better supports sRGB.

**Comment by newpeople123** [comment]
Thanks
