### ISSUE TITLE
Index overflow in GeometryTechnique::generateGeometry

### ISSUE THREAD

**Issue by hwiesmann** [openscenegraph/OpenSceneGraph#185]
There can be an index overflow for the index array in GeometryTechnique::generateGeometry. The fault code is (line 997 ff):

`    bool smallTile = numVertices <= 16384;

    // OSG_NOTICE<<"smallTile = "<<smallTile<<std::endl;

    osg::ref_ptr<osg::DrawElements> elements = smallTile ?
        static_cast<osg::DrawElements*>(new osg::DrawElementsUShort(GL_TRIANGLES)) :
        static_cast<osg::DrawElements*>(new osg::DrawElementsUInt(GL_TRIANGLES));

    elements->reserveElements((numRows-1) * (numColumns-1) * 6);
`
Obviously the array size can become larger than 65536 (e.g. numRows == numColumns == 128 -> array size: 127*127*6 == 96774). To be on the save side the code can be replaced by:

`bool smallTile = numVertices <= 65536/6;`

Or may DrawElementsUShort only have a total byte size of 65536? Then, the correction would be:

`bool smallTile = numVertices <= 65536/(6*sizeof(GLushort));`

Regards,
Hartwig

**Comment by openscenegraph** [comment]
The code looks correct to me.  The type of DrawElements refers to the internal type of the std::vector<> used to store the index data, so if there are less than 2^16 vertices then it'll fit just fine in a DrawElementsUshort even if the length of the std::vector<ushort> is longer than 2^16.

**Comment by hwiesmann** [comment]
May I ask then what the purpose of the statement
`bool smallTile = numVertices <= 16384`
is? If the selection whether to use DrawElementsUShort or DrawElementsUInt is independent of the number of vertices why is there then a comparison with the number of vertices?

**Comment by openscenegraph** [comment]
I think you've misunderstood the code and my response.  The number of vertices in the *vertex array* is what is important, and why smallTile records whether there less than 2^16 vertices and why the appropriate sized DrawElements is selected.  The number of *indices* in the DrawElement is not important.  You seem to have confused the number of vertices and indices in your original issue entry, I had hoped my brief explanation would have cleared this up.

**Comment by hwiesmann** [comment]
Sorry, I misunderstood your previous answer. Thanks for the clarification.

But then actually 32768 should be OK, too. Because GLushort is according to Khronos a 2 byte integer number. Not that it really matters, I just want to understand it finally.

Probably you used 16384 to get rid of potential bugs related to 16 bit overflow issues?

**Comment by openscenegraph** [comment]
nVertices<=16384 does look like an error, shows how focused on correcting the incorrect parts of your original issue post but didn't spot the original maths was a bit off.  There shouldn't be any overflow issues as long as nVertices is computed correctly.  I will need to do a code review but in principle I can't see why the code isn't:

 bool smallTile = nVertices < 65536

I will do a code review and if the original code does turn out to be wrong will amend it.
