### ISSUE TITLE
Opengl.org SDK and current status of OSG

### ISSUE THREAD

**Issue by oddhack** [openscenegraph/OpenSceneGraph#195]
We're going to be restructuring the SDK area of www.opengl.org and, since
OSG is listed there, wanted to let you know and ask what the current state of the project is and if it should continue to be listed (it looks fairly active, but this is a boilerplate request to all the project owners).

Jon Leech
Khronos

**Comment by openscenegraph** [comment]
We'd like the OSG to be continued to be listed.  Is this reply enough or do we need to contact anyone formally?

**Comment by oddhack** [comment]
That's fine, thanks. I'm as official as it gets :-)
