### ISSUE TITLE
openthread: log spamming on win32

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#209]
Things like below are spamming stdout:

```
setProcessorAffinity() : affinity.activeCPUs.size()=1, numprocessors=4
   setting CPU : 0
affinityMask = 1
```

**Comment by openscenegraph** [comment]
This is just a temporary debug message associated with the trunk and dev versions of the OSG, it will be removed once we start closing in on the stable release.

**Comment by filnet** [comment]
For example, in Win32Thread.cpp:

std::cout << "SetThreadAffinity() : affinity.activeCPUs.size()=" << affinity.activeCPUs.size() << ", numprocessors=" << numprocessors << std::endl;

I don't mind fixing that for 3.5.6 but will need some indication on what to do:
- remove
- comment out
- replace by OSG debugging facility

Note that this logging made it in the 3.5.5 release and I'd like to see it gone in the coming 3.5.6.
