### ISSUE TITLE
Cmake could not find OpenSceneGraph

### ISSUE THREAD

**Issue by mcemilg** [openscenegraph/OpenSceneGraph#212]
I just installed the OpenSceneGraph-3.4.0 with following build reference. And also I added the osg to my environmental variables. All examples works without any errors. I'am trying to create a new project with cmake. But I am getting "cmake could not find OpenSceneGraph" error. Here is the my simple cmake ;

```
cmake_minimum_required(VERSION 2.8.11)
project(example)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)

find_package(OpenSceneGraph REQUIRED COMPONENTS osgDB osgGA osgUtil osgViewer)

include_directories(${OPENSCENEGRAPH_INCLUDE_DIRS})

set(SOURCES
    main.cpp
    )

add_executable(${PROJECT_NAME} ${SOURCES})

target_link_libraries(${PROJECT_NAME}
    ${OPENSCENEGRAPH_LIBRARIES}
    )
```
And here is the full error;

```
-- Could NOT find osgDB (missing:  OSGDB_LIBRARY) 
-- Could NOT find osgGA (missing:  OSGGA_LIBRARY) 
-- Could NOT find osgUtil (missing:  OSGUTIL_LIBRARY) 
-- Could NOT find osgViewer (missing:  OSGVIEWER_LIBRARY) 
-- Could NOT find osg (missing:  OSG_LIBRARY) 
-- Could NOT find OpenThreads (missing:  OPENTHREADS_LIBRARY) 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES
  OSGDB_FOUND OSGGA_FOUND OSGUTIL_FOUND OSGVIEWER_FOUND OSG_FOUND
  OPENTHREADS_FOUND) (found suitable version "3.4.0", minimum required is
  "3.4.0")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenSceneGraph.cmake:187 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
```

I copied the findosg file into my cmake. It works in this way. I searched the internet a lot, but I could not get any solution. My system is Ubuntu 14.04 lts.

**Comment by openscenegraph** [comment]
CMake has it's own find macros for the various OSG components, it shouldn't be necessary to use your own find script. In the OSG master there is now an osgCMakeExample program that illustrates what you need to put in a CMake script to find and link to the OSG.  See:
 https://github.com/openscenegraph/OpenSceneGraph/tree/master/examples/osgCMakeExample

**Comment by Seromonto** [comment]
export LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH"
export OPENTHREADS_INC_DIR="/usr/local/include"
export OPENTHREADS_LIB_DIR="/usr/local/lib64:/usr/local/lib"
export PATH="$OPENTHREADS_LIB_DIR:$PATH"
