### ISSUE TITLE
bug：osgText is very blurry in MFC Frame，help！

### ISSUE THREAD

**Issue by MrRender** [openscenegraph/OpenSceneGraph#217]
I use the osg in MFC Frame and the text is very blurry.help！
![qq 20170312131816](https://cloud.githubusercontent.com/assets/8901500/23829206/a80014aa-0726-11e7-93c1-6a59322b972d.png)

**Comment by openscenegraph** [comment]
You don't say anything about how you have integrated osgText into your application so there isn't any way for others to know what you have done wrong.  The best way to get into these details is to use the osg-users mailing/forum as this is the official avenue for support.
