### ISSUE TITLE
Threading on Windows

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#218]
Not an issue per se, but there recently was some debate and code changes related to CPU affinity.

I came accross this post which might help get further on that topic (on Windows...):

https://blogs.msdn.microsoft.com/oldnewthing/20170309-00/?p=95695

**Comment by openscenegraph** [comment]
Thanks for the link, this type of link would be best posted to the forum/mailing list as it's not a "issue" with the OSG.

FYI, The OpenThreads implementation in master supports CPU sets, for each thread you can set which set of threads it can run on.
