### ISSUE TITLE
osg::BuildShapeGeometryVisitor using GL_QUADS

### ISSUE THREAD

**Issue by tomhog** [openscenegraph/OpenSceneGraph#222]
Some of the shapes built with osg::BuildShapeGeometryVisitor use GL_QUADS to draw their primitives. This isn't supported on GLES platforms so doesn't work out of the box.

The current solution is to use the osgUtil Optimizer with the osgUtil::Optimizer::TRISTRIP_GEOMETRY option to convert the GL_QUADS to tristrips.

**Comment by openscenegraph** [comment]
My plan is to have a look at this tomorrow (22nd March), should have a fix in my UK midday.

**Comment by openscenegraph** [comment]
I have now checked in changes the BuildShapeGeometry to replace GL_QUADS and GL_QUAD_STRIP with indexed GL_TRIANGLES:  https://github.com/openscenegraph/OpenSceneGraph/commit/48aa852f42dc578e610b8ebccf8ea70199f27c48
