### ISSUE TITLE
Image serializer not fully functional

### ISSUE THREAD

**Issue by openscenegraph** [openscenegraph/OpenSceneGraph#226]
The osg::Image serialization isn't working fully, such as inability to inline data.

**Comment by MPursche** [comment]
I made a first attempt to solve this issue: [src/osgWrappers/serializers/osgImage.cpp](https://github.com/MPursche/OpenSceneGraph/blob/07e708a9d8684e49c1719c1fe3e8489c0d1ebadf/src/osgWrappers/serializers/osg/Image.cpp).
For the most part, I copied the code from `readImage()` and `writeImage()` and adapted it. So far it seems to work for the osgb and osgt file format with all write hints. It is also backwards compatible as I left the `readImage()` and `writeImage()` untouched.

The issue I see with this attempt is that there is code duplication between the serializer implementation and the `readImage()` and `writeImage()` methods. I thought about refactoring this methods by extracting the image data serialization into something like `readImageData()` and `writeImageData()`. But I see no obvious way to do this without breaking backwards compatibility.
Additionally, I'm not quiet sure if I used `UPDATE_TO_VERSION_SCOPED` correctly. Would I need to increase the version number to 147?

**Comment by openscenegraph** [comment]
I have got the image serialization working by simply removing the check against binary format when writing our image files.  The change to OutpuStream.cpp is now checked in: https://github.com/openscenegraph/OpenSceneGraph/commit/717cb182cec1454dbab94b1be4a86195f77ad3a7

I have done testing here by modifying osgforest so that it writes out the TextbureBuffer subgraph to .osgt and .osgb and both routes now work fine, you can load.

**Comment by MPursche** [comment]
Is there something missing in the commit? Serializing the image of a TextureBuffer is still not working for me. I extended the osgforest example as suggested and this is the output for the osgt format:
```
 osg::TextureBuffer {
    UniqueID 124849 
    WRAP_S CLAMP 
    WRAP_T CLAMP 
    WRAP_R CLAMP 
    MIN_FILTER LINEAR_MIPMAP_LINEAR 
    MAG_FILTER LINEAR 
    InternalFormatMode USE_USER_DEFINED_FORMAT 
    InternalFormat 34836 
    Swizzle RGBA 
    BufferData TRUE {
        osg::Image {
            UniqueID 124850 
            DataVariance STATIC 
            WriteHint STORE_INLINE 
            InternalTextureFormat GL_RGBA 
            DataType GL_FLOAT 
            PixelFormat GL_RGBA 
            Packing 1 
        }
    }
}
```

I added the `osg::Image::STORE_INLINE` flag to the images and set the write image hint in the `osgDB::Options`:
```C++
osgDB::Options options;
options.setPluginStringData("WriteImageHint", "IncludeData");
```

The `osgDB::Outputstream::writeImage()` method is not called for the serialization of the `osg::TextureBuffer`. I tested this by setting a breakpoint in the method.
