### ISSUE TITLE
AC3D matrices imported in wrong order

### ISSUE THREAD

**Issue by NikolaiVChr** [openscenegraph/OpenSceneGraph#227]
The matrices read from the 'rot' token appears to be read in wrong manner in 3.4.0:

Here is an example line from AC3D file: 

`rot 1 2 3 4 5 6 7 8 9 `

Inivis AC3D interprets that as: 

```
1 4 7 
2 5 8 
3 6 9
``` 

While OpenSceneGraph reads it as: 

```
1 2 3 
4 5 6 
7 8 9 
```

Here is a valid Inivis AC3D file, that demonstrate: 

[AC3D file](https://drive.google.com/open?id=0B49qitQsNy34VGVlb3ZyTGloTGc) 

[Forum thread](http://forum.openscenegraph.org/viewtopic.php?t=16555) about this issue.

**Comment by openscenegraph** [comment]
I have checked in a fix to OSG master, could you test it out?
https://github.com/openscenegraph/OpenSceneGraph/commit/76afbc9bcfa5ed1e86de2865bbec416f55740cef

**Comment by NikolaiVChr** [comment]
I will, trying to convince someone to make me a 3.4.0 build with this fix so I can test it with. I don't have build environment for OSG.
