### ISSUE TITLE
problem with animation ?

### ISSUE THREAD

**Issue by AiNi-KuangBiao** [openscenegraph/OpenSceneGraph#232]
I have a problem with animation .when I use the 3d models with animations in the osganimationviewer example provided in this project,it notified “no animations available“,I am confused;
(you can download the model form this url, https://pan.baidu.com/s/1pKF1xB9)

**Comment by openscenegraph** [comment]
I followed the link but it was broken so can't look into issue.  This is most likely a user issue so the best place to discuss it is via the osg-users mailing list/forum as this official forum for support,
