### ISSUE TITLE
Could not write images created from relative path with export option WriteImageHint=WriteOut

### ISSUE THREAD

**Issue by rhabacker** [openscenegraph/OpenSceneGraph#233]
Writing a scene dump containing images  as osgt file with option WriteImageHint=WriteOut fails to create images because of using invalid pathes.

How to reproduce: 
Add the following lines to osgtexture2D example after the call to viewer.setSceneData( createModel() );

    osg::ref_ptr<osgDB::Options> options = new osgDB::Options("WriteImageHint=WriteOut");
    osgDB::writeNodeFile(*viewer.getSceneData(),"test-write-out.osgt", options.get());

and run with 
cd <openscenegraph-build-root>
OSG_NOTIFY_LEVEL=Info OSG_FILE_PATH=<osgscenegraph-test-data-path> OSG_LIBRARY_PATH=<openscenegraph-build-root>/lib bin/osgtexture2D

Opening the created test-write-out.osgt  with osgviewer does not show any images.

On creating the osgt file the following messages are reported:
OutputStream::writeImage(): Write image data to external file Images/lz.rgb
Error writing file Images/primitives.gif: file not handled
OutputStream::writeImage(): Write image data to external file Images/primitives.gif
OutputStream::writeImage(): Failed to write Images/primitives.gif
OutputStream::writeImage(): Write image data to external file Images/tree0.rgba
Empty Image::FileName resetting to image.dds
Warning: RGB plugin does not supporting writing non contiguous imagery.
Opened DynamicLibrary osgPlugins-3.5.6/osgdb_ddsd.so
WriteDDS, dataType = 0x1401
no mipmaps to write out.
Flipping dds image on write
OutputStream::writeImage(): Write image data to external file image.dds
OutputStream::writeImage(): Write image data to external file Images/lz.rgb
Error writing file Images/primitives.gif: file not handled
OutputStream::writeImage(): Write image data to external file Images/primitives.gif
OutputStream::writeImage(): Failed to write Images/primitives.gif
OutputStream::writeImage(): Write image data to external file Images/tree0.rgba
Empty Image::FileName resetting to image.dds
Warning: RGB plugin does not supporting writing non contiguous imagery.
WriteDDS, dataType = 0x1401
no mipmaps to write out.
Flipping dds image on write
OutputStream::writeImage(): Write image data to external file image.dds

**Comment by openscenegraph** [comment]
This typo of issue is best discussed on osg-uses mailing list/forum as resolving it will likely take some discussion/testing.  Could you start up a thread on osg-users mailing list/forum?  Specifying which version of the OSG and OS will be useful too.

**Comment by openscenegraph** [comment]
I think we need a general discussion about what to do about when/how the OSG should handle cases where the Image FileName suggests writing a file to a directory that doesn't exist.  It essentially the writing code not supporting the usage case where the write file path needs some form of user control.  I'll close this issue here as this isn't something appropriate for discussion here as it's seen regularly be too few community members.
