### ISSUE TITLE
API/ABI changes review for OpenSceneGraph

### ISSUE THREAD

**Issue by lvc** [openscenegraph/OpenSceneGraph#239]
The review of API/ABI changes for OpenSceneGraph since version 3.3.3: https://abi-laboratory.pro/tracker/timeline/openscenegraph/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

The tool checks _all_ API symbols declared in header files, so there may be some false positives.

Thank you.

![openscenegraph-1](https://cloud.githubusercontent.com/assets/1517837/24499390/93a54784-1552-11e7-96bb-7d09f8243516.png)

![openscenegraph-2](https://cloud.githubusercontent.com/assets/1517837/24499409/a6b110ba-1552-11e7-81ba-8cf7a7c8961d.png)

## Environment
* Linux x86_64
* GCC 4.9
* OpenSceneGraph 3.3.3 and higher

**Comment by openscenegraph** [comment]
Hi, 

I appreciate the effort and utility of the ABI tracker and plan to learn more about how to support your efforts - I'm new to abi-tracker so can't just jump in and know exactly what to do and how, so have left this issue open as a place holder for the time being.

For the OSG community I feel that a link to the ABI tracking paging would be appropriate, perhaps in the OpenSceneGraph/README.md and/or on the OSG website.

For the OSG community I think that ABI compatibility between stable point releases (i.e. 3.2.0 -> 3.2.1 -> 3.2.3) which are intended to ABI compatible and developer release (i,e. 3.5.0 -> 3.5.1 etc.) as well as between branches OpenSceneGraph-3.2 -> OpenSceneGraph-3.4.

I'm open to suggestions on how to progress.

Cheers,
Robert Osfield

**Comment by openscenegraph** [comment]
I have added an ABI tracker link in the OpenSceneGraph/README.md  to the above ABI tracker page, so will close this issue.
