### ISSUE TITLE
Generate an iOS XCode Project

### ISSUE THREAD

**Issue by JIabao1** [openscenegraph/OpenSceneGraph#253]
The document "Generating an iOS XCode Project 2017" don't work.

**Comment by robertosfield** [comment]
Could please post the query on the osg-users mailing list/forum so that other OSX users can pitch in and help you.  Also please be specific about what source of the information (i.e filenames/URL's,OSG versions) as even as project lead I don't know what "document" you might be referring to.  Also please be specific about what doesn't work, as "don't work" on it's own isn't helpful in diagnosing what is wrong with what you've done, whether any OSG side documents or software need addressing.

**Comment by JIabao1** [comment]
Thank you for your help! I am a new OSG user and I don't know much about the rules. The document url: [](http://www.openscenegraph.org/index.php/documentation/platform-specifics/ios/216-generating-an-ios-xcode-project-2017). 
# Environment
macOS Sierra 10.12.4
Xcode 8.3.2 (8E2002)
CMake 3.8.0
OSG 3.5.5

What I did and got is here:
MacBook-Pro:osg Jiabao$ cmake ./ -G Xcode -DOSG_BUILD_PLATFORM_IPHONE:BOOL=ON \
> -DIPHONE_SDKVER="10.3" \
> -DIPHONE_VERSION_MIN="8.0" \
> -DOPENGL_PROFILE:STRING=GLES2 \
> -DBUILD_OSG_APPLICATIONS:BOOL=OFF \
> -DBUILD_OSG_EXAMPLES:BOOL=ON \
> -DOSG_WINDOWING_SYSTEM:STRING=IOS \
> -DOSG_DEFAULT_IMAGE_PLUGIN_FOR_OSX="imageio" \
> -DDYNAMIC_OPENSCENEGRAPH:BOOL=OFF \
> -DDYNAMIC_OPENTHREADS:BOOL=OFF \
> -DCURL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/curl-ios-device/include" \
> -DCURL_LIBRARY:PATH="$THIRDPARTY_PATH/curl-ios-device/lib/libcurl.a" \
> -DFREETYPE_INCLUDE_DIR_freetype2:PATH="$THIRDPARTY_PATH/freetype-ios-universal/include/freetype" \
> -DFREETYPE_INCLUDE_DIR_ft2build:PATH="$THIRDPARTY_PATH/freetype-ios-universal/include" \
> -DFREETYPE_LIBRARY:PATH="$THIRDPARTY_PATH/freetype-ios-universal/lib/libFreeType_iphone_universal.a" \
> -DTIFF_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/tiff-ios-device/include" \
> -DTIFF_LIBRARY:PATH="$THIRDPARTY_PATH/tiff-ios-device/lib/libtiff.a" \
> -DGDAL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/gdal-ios-device/include" \
> -DGDAL_LIBRARY:PATH="$THIRDPARTY_PATH/gdal-ios-device/lib/libgdal.a"
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.8/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/Jiabao/osgearth-build/osg/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/xcodebuild" "-project"
  "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_3230b"
  "-configuration" "Debug"

  === BUILD TARGET cmTC_3230b OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION
  Debug ===

  

  Check dependencies

  No architectures to compile for (ARCHS=armv7 armv7s arm64, VALID_ARCHS=i386
  x86_64).

  

  ** BUILD FAILED **

  

  

  The following build commands failed:

  	Check dependencies

  (1 failure)

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:114 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/Jiabao/osgearth-build/osg/CMakeFiles/CMakeOutput.log".
See also "/Users/Jiabao/osgearth-build/osg/CMakeFiles/CMakeError.log".

**Comment by robertosfield** [comment]
Thanks for the details.  @tomhog could you have a look at this?  The OSG webpage looks like it's one authored by you so you might have a better chance at spotting the problem than I.  Thanks.

**Comment by tomhog** [comment]
I think this is an issue with the newest cmake, I just updated and get the same error. 

-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken

That just compiling cmakes on internal test program. I'll see if there any info on it but try down grading.

**Comment by JIabao1** [comment]
@tomhog could you tell me the Environment that can generate an iOS Xcode Project ?If it is possible,could you please send  the specific steps to my email (jiabao.shen@tianjishuju.com), Thanks very much.

**Comment by tomhog** [comment]
I have cmake 3.1.3 installed currently. The environment I used for that guide is written at the top of it.

**Comment by JIabao1** [comment]
Thanks again! I use brew to install cmake, cmake command line is no longer wrong.
