### ISSUE TITLE
The windows view position incorrect with MFC.

### ISSUE THREAD

**Issue by LSongBee** [openscenegraph/OpenSceneGraph#262]
I upgrade my system from OSG 3.2.3 to 3.4.0 (or 3.5.x) and I found the windows view position offset. To check osgviewerMFC example, it has the same problem.

Compare some 3.2.3 and current version I think it might a bug at /osgViewer/GraphicsWindowWin32.cpp. It is a new function, areWindowDimensionsChanged(), be call at init() time. If I remove this function, the result looks like OK.

Please help to check it.

**Comment by openscenegraph** [comment]
I vaguely recall other members raising this issue and don' think it's a case of just reverting changes as the original chances fix bugs with other MFC usage cases. Could you please use the osg-users mailing list/forum for discussing issues like this as gets the widest exposure w.r.t the community who may be able to help resolve the problem you are seeing.

**Comment by Haojia521** [comment]
Maybe modify the codes in function cOSG::InitCameraConfig(void) can solve your problem.

// Set the viewport for the Camera
camera->setViewport(new osg::Viewport(traits->x, traits->y, traits->width, traits->height));
to
camera->setViewport(new osg::Viewport(0, 0, traits->width, traits->height));
