### ISSUE TITLE
Zoom in/out the center

### ISSUE THREAD

**Issue by hushanming** [openscenegraph/OpenSceneGraph#269]
Hello,
 I've been learning osg recently，and thankyou very much for the open source code.I read the TrackballManipulator.cpp and other manipulator such as CameraManipulator.So I want to write my own manipulator to achive the functions:
1. Zoom in/out at the Mouse position  I changed the [_center](https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgGA/OrbitManipulator.cpp#L456-L457)  as  _center = mouseWorld,but it doesn't work.Could you give me  some advice? 
2.How to rotate the scene around the mouse position rather than around the fixed axis?
Thankyou.

**Comment by openscenegraph** [comment]
The best place for support discussions is on the osg-users mailing list/forum.
