### ISSUE TITLE
3.4.1-rc1 StatsHandler shaders failed on macOS GL3 in compatibility profile

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#292]
After commit
**Backported GL2/3, GLES2/3 compatible Text and StatsHandler shaders to…
e6ab01c7c652ab47c3d61980fb5b031c700b4427**

shaders in StatsHandler can't be compiled on macOS.
Shaders are for GL3 and can't be compiled on compatibility profile (OpenGL 2.1 on macOS)

In 3.5.6 we can disable this via DisplaySettings as I remember...
> osg::DisplaySettings::instance()->setShaderHint(osg::DisplaySettings::SHADER_NONE);

But in OSG 3.4 there is no such mechanism.
So, I think there are two options:
1) revert :)
2) add setShaderHint to DisplaySettings with SHADER_NONE by default

No matter what, we need opportunity to disable this shaders without dirty hacks like
anyText->getStateSet()->removeAttribute(...PROGRAM...) in 3.4

KOS

**Comment by openscenegraph** [comment]
I believe the addition of default shaders for GL3 + GLES2+ is a valuable improvement to 3.4 so worth keeping, so I'm not about to revert this improvement.

Adding member variables to DisplaySetting could break the ABI.  Would need to check specs on ABI to clarify if we could get away with it.

Could you explain the your build options that you used, and the specific errors that occurred?  It looks to me like if you've enabled GL3 build then GL3 shaders will be used, but you are then restricting the GL version in somehow but creating a GL2.1 only context.  Why not just build the OSG against GL2 if you want to use it with GL2?

**Comment by valid-ptr** [comment]
I'm agree that OSG should be build with GL_PROFILE=GL2 if a fallback to GL2.1 is possible, then things like _is***Something***Supported_ from _GLExtensions_ will work correctly etc.
I've planned to use GL3 core on any Mac 10.8+ (without fixed function pipeline), so code must be adopted for GL3: GL_RED format instead of GL_LUMINANCE for texture format etc. But! No VAO => no core => switched to 2.1 compatibility. This is my history in brief :) Thanks for the tip.

The main reason to have opportunity to disable shaders in osg::Text is user's programmable pipeline.
I'm developing pipeline with ShaderComposer + #pragma(tic) functionality. Texts can be under light conditions etc.

Maybe some preprocessor define via cmake can help to disable this shaders (option 3)?

PS.

**Comment by mp3butcher** [comment]
I've not mac but believe to remember that on this plateform you should use cor profile only so make a choice between gl2 3 or 4 further the VAO support can be enable either with env variable OSG_VERTEX_BUFFER_HINT=VAO or via the DisplaySetting of your application

**Comment by valid-ptr** [comment]
This is right for OSG 3.5.6, but we are talking here about 3.4.1 release where no VAO presented.
Thanks for your comments

**Comment by openscenegraph** [comment]
OpenSceneGraph-3.4.x won't ever be able to support the Mac GL3 Core profile as it doesn't have VAO support and there is absolutely no way to be able to backport it as the required changes are *massive*. If you want to use GL3 core profile on the Mac then you need to use OSG master or 3.5.x.

Perhaps for OSG-3.4 on Mac perhaps we should just disable the option for doing a GL3 build to avoid users trying to the mix the two.
