### ISSUE TITLE
Problems to read image files

### ISSUE THREAD

**Issue by romulogcerqueira** [openscenegraph/OpenSceneGraph#295]
Hi,

currently I have a problem to load and process image files on OSG. I got the message:

<pre>
Warning: Error in reading to "/home/romulo/textures/gray_texture_d.jpg".
</pre>

This image exists.  What might have been?

**Comment by openscenegraph** [comment]
Check the validity of the file, the error might be one generated by libjpeg that the OSG's jpeg plugin uses to read jpeg files.

To help dig deeper on this type of issue you can enable more verbose debugging messages by setting the env var OSG_NOTIFY_LEVEL to DEBUG i.e.

  export OSG_NOTIFY_LEVEL=DEBUG
  osgviewer --image /home/romulo/textures/gray_texture_d.jpg

As a general note, the right place for user support is via the osg-users mailing list/forum, so please join the community and post your support questions there.
