### ISSUE TITLE
CMake generates package config files containing library names without 'd' suffix in Debug configuration.

### ISSUE THREAD

**Issue by dmitriano** [openscenegraph/OpenSceneGraph#297]
If I [build OSG in debug configuration](https://developernote.com/2017/08/building-osgearth-on-ubuntu-14-04/) with the following commands:

`cmake ../../OpenSceneGraph/ -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/home/dmitry/examples/install`
`make -j3 install`

all the libraries are created with 'd' suffix, so their names are libOpenThreadsd.so, libosgAnimationd.so, ..., but in pkgconfig/*.pc they are listed without 'd' suffix so and my app does not build with them. Adding 'd' manually solves the issue, so I have an impression that *.pc file are generated incorrectly.

**Comment by openscenegraph** [comment]
I have looked into the issue and found that the CMake MATCHES keyword utilized in selecting the build type is case sensitive so doesn't pick up "debug" as being the same as "Debug" that is supported by the code.   If you used -DCMAKE_BUILD_TYPE=Debug everything would have worked.

CMake doesn't look like it has a case intensive string comparison so as I work around I've implemented a specific code block that remaps usage like "debug" or "DEBUG" to the "Debug" that is officially supported. It's not an elegant solution but does at least keep the workaround local to the code that checks the build type.  The commit is:

https://github.com/openscenegraph/OpenSceneGraph/commit/af79ad451ef5b40ee03c9acd98ea340e5755f1ac

This will be part of OSG master, for existing versions of the OSG simply use the correct type for CMAKE_BUILD_TYPE and everything should work.
