### ISSUE TITLE
should be end, not begining

### ISSUE THREAD

**Issue by gedalia** [openscenegraph/OpenSceneGraph#303]
https://github.com/openscenegraph/OpenSceneGraph/blob/34b4e7001522c1b47b4211dac34d2d6a6b994a6f/src/osgUtil/IncrementalCompileOperation.cpp#L335

**Comment by openscenegraph** [comment]
Thanks for spotting the bug, I've checked in a fix to master and OpenSceneGraph-3.4 branch
