### ISSUE TITLE
GL3/gl3.h should be replaced with GL/gl.h on Ubuntu

### ISSUE THREAD

**Issue by dmitriano** [openscenegraph/OpenSceneGraph#305]
[I build OSG with OpenGL3 on Ubuntu 14.04](https://developernote.com/2017/08/building-osgearth-on-ubuntu-14-04/) using the following command:

`cmake ../../OpenSceneGraph/ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/dmitry/examples/install -DOPENGL_PROFILE=GL3`

It generates include file ‘/home/dmitry/examples/build/osg/include/osg/GL’ that includes GL3/gl3.h and subsequent 'make' results in compiler errors, because there is no GL3/gl3.h on my system. If I replace it with GL/gl.h, everything compiles and works fine. Probably I misunderstood something, but I have no idea on where can I get this GL3/gl3.h.

**Comment by openscenegraph** [comment]
If you don't have GL3 headers installed then don't select the GL3 profile, or if you have them they are installed on a different path than CMake is selecting by default using ccmake .. and then edit the header path.

As a general note, please use the osg-users mailing list/forum for support queries like this as it's a support topic rather a technical issue i.e. bug with the software.
