### ISSUE TITLE
underflow in osg::Timer

### ISSUE THREAD

**Issue by PjotrSvetachov** [openscenegraph/OpenSceneGraph#317]
Hi Robert,

the typedef of Timer_t is unsigned on linux (or any non-windows system). This can lead to underflow if you call osg::Timer::delta_s with t1 > t2 which will give you a very big delta value. We stumbled on this because on our system movies stopped playing. (we use a modified version of the ffmpeg plugin but from studying the code in osg this can also happen in the official plugin.)
It happens because of this check: https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgPlugins/ffmpeg/FFmpegImageStream.cpp#L226
This is because of race conditions with the line here:
https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgPlugins/ffmpeg/FFmpegImageStream.cpp#L354

What happens is that in line 228 osg::Timer::instance()->tick() is called and then in another thread _lastUpdateTS is also updated with a new value from osg::Timer::instance()->tick() on line 354. Then on line 228 delta_s is called with the updated _lastUpdateTS  and thus t1 > t2.

I haven't done a pull request as I don't know what the best fix is. Making Timer_t  signed will probably produce a lot of compile warnings and may introduce bugs. Another options are doings casts in delta_s like
`inline double delta_s( Timer_t t1, Timer_t t2 ) const { return (double)((long long)t2 - (long long)t1)*_secsPerTick; }`
or a check like
`inline double delta_s( Timer_t t1, Timer_t t2 ) const { return t2 >= t1? (double)(t2 - t1)*_secsPerTick : -((double)(t1 - t2)*_secsPerTick); }`

Best regards,
Pjotr

**Comment by openscenegraph** [comment]
The best solution is the use the bool check to keep the math as precise as possible for as long as possible.  I have implemented this and check it into master and the OpenSceneGraph-3.4 branch.  Could you test these.
