### ISSUE TITLE
Can I use OSG to display the model that produce by Smart3d?

### ISSUE THREAD

**Issue by wuxiaobo2014** [openscenegraph/OpenSceneGraph#339]
<img width="511" alt="qq20170901-193022 2x" src="https://user-images.githubusercontent.com/21191415/29967969-0988c426-8f4c-11e7-8ce0-4ac1c0da0e64.png">
<img width="594" alt="qq20170901-193839 2x" src="https://user-images.githubusercontent.com/21191415/29968282-840b6c48-8f4d-11e7-9484-e5563b5fe247.png">
<img width="616" alt="qq20170901-194101 2x" src="https://user-images.githubusercontent.com/21191415/29968283-86cdf5ea-8f4d-11e7-88d7-26da04437397.png">

Like images, the production by smart3d  have so much .osgb file, can I loading whole of  production and display by OSG?

I'm very sorry for my poor english.

**Comment by openscenegraph** [comment]
I don't know anything about smart3d so can't answer questions on it, I don't recall others in the community discussing it either but perhaps others might know of it.  Using github issues tracker for asking such questions is inappropriate, we have the osg-users mailing list/forum for discussions like this for general user questions.
