### ISSUE TITLE
Failure to extract textures

### ISSUE THREAD

**Issue by rjj-unr** [openscenegraph/OpenSceneGraph#356]
I am trying to extract textures from a ton of ive files recursively. However, the textures output needs to match the authors files structure. For example some will need "../Texture", some need "../../Textures", and it even goes as far as some needing to have different drives like "K:/Some/Random/Location/." Can we make it so that it just creates a directory in the Output named Textures and have all the images go there? I am guessing that the way it is now is because the materials with the textures assigned to it are pointing to these locations. I'm not familiar with OSG but is there a way to just recursively point the materials to the new location?

**Comment by openscenegraph** [comment]
Could you please use the osg-users maling list or forum for support questions like this as it's a usage case/support problem rather than a bug with the software.

**Comment by rjj-unr** [comment]
I was thinking it could be a considered a bug because as is, it requires the user to create a file structure that exists on another computer that may not even be from the user themselves.
