### ISSUE TITLE
A question about OSG compiled into managed DLL.

### ISSUE THREAD

**Issue by wangbingqian110** [openscenegraph/OpenSceneGraph#362]
HI:
How to compile openscenegraph into a managed DLL that can be invoked directly by c #?

**Comment by openscenegraph** [comment]
This topic has been discussed on the osg-users mailing list/forum, so please check the achives.  
The github issue tracking exist to report bugs, so If you have any support questions then the best place to ask support questions is using the mailing list/forum as this is the official channel for support.
