### ISSUE TITLE
fix for multithreaded dxf reading

### ISSUE THREAD

**Issue by Grimkin** [openscenegraph/OpenSceneGraph#384]
Hi,
we encountered problems when reading dxf-files via multiple threads. Either the the program completely crashed or weird results occured. The crash seemed to be near the trim function. 

The following fixed the problem: 
In "dxfReader.cpp" in the function "readerText::getTrimmedLine" in line 88:
replace `static string line = "";` with `string line = "";`

Best regards,
Grimkin

**Comment by openscenegraph** [comment]
Thanks for the report and suggested fix.  This fix looks sound, I've checked in similar fix into OSG master and the 3.4 branch.
