### ISSUE TITLE
examples/osgdeferred: fails to compile with -DOSG_PROVIDE_READFILE=OFF

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#386]
Those fail too: 
examples/osgmovie/osgmovie.cpp
examples/osgtext3D/osgtext3D.cpp
examples/osgviewerWX/osgviewerWX.cpp

**Comment by openscenegraph** [comment]
I have done a build with OSG_PROVIDE_READFILE to OFF and fixed the problems I could see, i couldn't test some of the issues though.  Could you do an update to master and let me know if there are any more issues left to resolve.

**Comment by filnet** [comment]
A few of them are in Windows specific code or in commented/ifdef 0 code.
I have a full list that I will provide.

**Comment by openscenegraph** [comment]
I have checked in more fixes so do make sure you are up to date with master as you do your test.

**Comment by filnet** [comment]
I pushed a PR with more fixes (some that affected the msys2 build and a few random others).

There are still some read*File calls in examples but they are trickier (for me) to fix.

**Comment by openscenegraph** [comment]
Thanks, PR now merged,
