### ISSUE TITLE
stats generates warning

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#391]
when switching the stats overlay on, the following warnings are displayed:

DBG: [OSG NOTICE] 
WRN: [OSG WARN] Error reading file shaders/text.vert: file not found
WRN: [OSG WARN] Error reading file shaders/text.frag: file not found
WRN: [OSG WARN] Error reading file shaders/text.vert: file not found
WRN: [OSG WARN] Error reading file shaders/text.frag: file not found
WRN: [OSG WARN]

**Comment by mp3butcher** [comment]
update OSGDATA

**Comment by filnet** [comment]
Never realized there was an OSGDATA (https://github.com/openscenegraph/OpenSceneGraph-Data)

The msys2 build of OSG does not come with these. Will need to look into that.

**Comment by mp3butcher** [comment]
could you close the issue?
