### ISSUE TITLE
osgviewer: strange single threaded 

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#405]
This works fine: 
`osgviewer.exe ground/gcs/src/share/models/multi/test_quad/test_quad_x.3ds --SingleThreaded --screen 0`

But the following is strange as the Stats say SingleThreaded but show 2 threads (on a dual screen setup).

`osgviewer.exe ground/gcs/src/share/models/multi/test_quad/test_quad_x.3ds --SingleThreaded`

![image](https://user-images.githubusercontent.com/8101062/33855797-699b220e-dec6-11e7-8904-c8cf0afa4353.png)

**Comment by robertosfield** [comment]
It's not showing two threads, it's just show that there are two cameras, it'll be using one camera per screen.

**Comment by filnet** [comment]
Ok. Makes sense. Sorry for the noise.
