### ISSUE TITLE
Has the repository undergone some major changes since about 2015?

### ISSUE THREAD

**Issue by 10110111** [openscenegraph/OpenSceneGraph#410]
I have a clone of `https://github.com/openscenegraph/osg.git` done somewhere in 2015, on commit 861cf3a50328f31fb736e5f09224692e16900272. After some failures to bring this clone to the state of the clone done these days by another person, I've tried to clone from scratch myself, and noticed that it has _completely_ changed: all the commit IDs changed, some author names and commit dates too, although the commit messages are mostly intact (didn't compare the diffs). In particular, the commit I've mentioned above now has Id cb3396b0e5522ce521ec5fe457db6dab2e4093d3.

Here's what the very first commit summary looks like in my old clone (given by `git log`):
```
commit a52e14ac369881848c5b1e4faaaede9ccc6b5458
Author: Robert OSFIELD <robert.osfield@gmail.com>
Date:   Wed Jan 10 16:32:10 2001 +0000

    New repository initialized by cvs2svn.
```
And here's the current very first commit:
```
commit 7c12eb9361a0727b736ef585dcabe1a048ecfea1
Author: Robert Osfield <robert@openscenegraph.com>
Date:   Wed Jan 10 16:32:10 2001 +0000

    New repository initialized by cvs2svn.
```

So I wonder, what's happened? Has the repo been compromised? Or has there been some major failure resulting in partial recovery?

**Comment by openscenegraph** [comment]
Nothing to worry about, in the very early days of adopting github I did some fixes to history and these unintentionally had a global effect.  I would recommend just doing a clean checkout.
