### ISSUE TITLE
cannot open source file "unistd.h"

### ISSUE THREAD

**Issue by elana1fel** [openscenegraph/OpenSceneGraph#416]
when compiling with visual studio 12

**Comment by openscenegraph** [comment]
The OSG has dozens of releases and hundreds of thousands of lines of code.  Which version of the OSG and which file are you seeing this error? We can't fix problems if you don't provide the details for others to reproduce and track down the issue.

**Comment by mp3butcher** [comment]
unistd.h just doesn't exist under win32 just comment the include line to fix the problem.
However this is a problem so give us information on osg version (from your other post, you seam to use 3.4 release) and error messages (in which file "#include <unistd.h>" is).

**Comment by openscenegraph** [comment]
I'm closing this Issue as there is no actual information that can help track down the issue seen by the user, the reported issue hasn't been seen by others users so it may well just be an issue of dependencies or configuration for the user and not an actual issue with the OSG itself.
