### ISSUE TITLE
nvtt plugin

### ISSUE THREAD

**Issue by elana1fel** [openscenegraph/OpenSceneGraph#417]
there is a problem when compiling osg in visual studio 12 with nvtt plugin.
i used the lib in 3rdparty folder

**Comment by openscenegraph** [comment]
which version of the 3rd party libraries and which version of the OSG are you seeing problems?

**Comment by elana1fel** [comment]
i used OpenSceneGraph 3.4 version...
3rdparty libraries were downloaded from here https://download.osgvisual.org/3rdParty_VS2013.5_v120_x64_V10_full.7z

**Comment by mp3butcher** [comment]
and what are the building errors?

**Comment by openscenegraph** [comment]
Which OSG version?  3.4.0 or 3.4.1?

**Comment by openscenegraph** [comment]
Closing this issue as there is no information that we can make any progress on.  The solution for this particular user will be simply disabling the build the the nvtt plugin via CMake, or just updating to a recent rev of the OSG.

**Comment by mp3butcher** [comment]
@elana1fel
add squish.lib bc7.lib bc6h.lib to the linker
