### ISSUE TITLE
Please label your releases as developer releases when applicable

### ISSUE THREAD

**Issue by yurivict** [openscenegraph/OpenSceneGraph#419]
For example, your website says that 3.5.1 is a developer release, and 3.4.1 is a stable release.
Github just shows all releases up to 3.5.9 as available.

1. You need to label 3.5.9 as developer release on github
2. Why doesn't your website show 3.5.9? Did you forget to update it?

http://www.openscenegraph.org/index.php/download-section/developer-releases

**Comment by openscenegraph** [comment]
The uses the convention of odd point releases for developer releases, so implicitly they are all labelled i.e. all 3,5,x are dev releases, while 3.4.x are all stable releases.  There is no need to delete dev releases and would break things for some end users if we did so.  

As for updating the websites, I'll do this periodically, but for dev releases I don't always do it.  Dev releases are meant to be lightweight tags of the current master.
