### ISSUE TITLE
About the OsgText

### ISSUE THREAD

**Issue by MrRender** [openscenegraph/OpenSceneGraph#420]
Is there a method to solve the OSG text missing in Intel integrated graphics card, such as negative sign and decimal point？think you!

**Comment by openscenegraph** [comment]
I use a Linux+Core i7 with Kubuntu on my Google pixel chromebook without problems with osgText, there isn't anything specific I enable for text.  I have found that I need to enable use of VBO's by default for the present set of Intel drivers.  This is testing with OSG-3.x and OSG master.

There is huge range of hardware, driver and OS combination.  as well a range of OSG versions, the advice that might be appropriate will likely depend upon the particular combinations.  Intel in particular can be harder to get working well as drives have historically be rather poor.

I only have access to one combination, to provide the best advice it may well require a much large number of developers to see the discussion to get an engineer with the same combination, the best way to see get this visibility would be to post a report of the issues you are seeing by posting a message to the osg-users mailing list/forum.  

When writing about the issue please specify as much info as required for others to reproduce the issue themselves, so the OS version, hardware version, developer tools used, OSG version.

**Comment by openscenegraph** [comment]
Closing this issue as it's a driver specific issue on some unspecified combination of OSG/OS and hardware, it's not a technical issue we can do anything about on the OSG side.  Advice to user would be to update intel drivers.
