### ISSUE TITLE
iOS 11 SDK: "system" function is not available anymore

### ISSUE THREAD

**Issue by laptabrok** [openscenegraph/OpenSceneGraph#438]
There is "system" function usage in osgPresentation but this func is not available in iOS 11 sdk.

```
OpenSceneGraph/src/osgPresentation/KeyEventHandler.cpp:122:26: error: call to unavailable function 'system': not available on iOS
            int result = system(_command.c_str());
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: candidate function has been explicitly made unavailable
int system(const char *) __DARWIN_ALIAS_C(system);
```

It's also used in some plugins and examples.

**Comment by openscenegraph** [comment]
Apple move the goal post yet again making life painful for any software and user that might want to support them.  As the system calls are there to provide functionality that can only be achieved through system calls I have to simple say that iOS 11SDK is not supported.

**Comment by openscenegraph** [comment]
I have decided to add the option to manually disabling the use of system, it won't work automatically right now, but you can now toggle on/off the use of system via the CMake option OSG_SYSTEM_SUPPORTED which defaults to ON, but can now be toggle to OFF.  This is checked into master. 

https://github.com/openscenegraph/OpenSceneGraph/commit/ae57f3cd467a742755baab7ea4f46463d16f8674
