### ISSUE TITLE
CMake Can not build OSG/Example/CMakeLists.txt

### ISSUE THREAD

**Issue by 354926089** [openscenegraph/OpenSceneGraph#472]
CMake 3.10.2 OSG3.4.1 .   Error Report is:

CMake Error at osgstaticviewer/CMakeLists.txt:24 (SETUP_EXAMPLE):
  Unknown CMake command "SETUP_EXAMPLE".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as
    cmake_minimum_required(VERSION 3.10)

**Comment by openscenegraph** [comment]
This is not a build issue, but a usage usage.

The only OSG example that is designed to work standalone from the rest of the build system is the osgCMakeExample which is there to reach users who how to build their own standalone applications.  

The rest of the examples are part of the wider OSG CMake build system so need to be setup from the root CMakeLists.txt.  Simple run cmake .. from the the OpenSceneGraph directory and then enable the BUILD_EXAMPLES options, then generate the make files.

**Comment by 354926089** [comment]
Thank you very much.
