### ISSUE TITLE
renderstage: glDrawBuffer related issues

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#486]
Hi,

The new osgEarth rex engine was failing to render anything under Qt and OSX.
Analysis shows that it is due to wrong glDrawBuffer being set.

Please see https://github.com/gwaldron/osgearth/issues/853 for details.

Input for a proper fix is welcome.

**Comment by filnet** [comment]
In a nutshell, what I understood is that the following workaround for a specific opengl driver was added to RenderStage::runCameraSetUp();

```
// If no color attachment make sure to set glDrawBuffer/glReadBuffer to none
// otherwise glCheckFramebufferStatus will fail
// It has to be done after call to glBindFramebuffer (fbo->apply)
// and before call to glCheckFramebufferStatus
if ( !colorAttached )
{
    setDrawBuffer( GL_NONE, true );
    setReadBuffer( GL_NONE, true );
    #if !defined(OSG_GLES1_AVAILABLE) && !defined(OSG_GLES2_AVAILABLE) && !defined(OSG_GLES3_AVAILABLE)
        glDrawBuffer( GL_NONE );
        glReadBuffer( GL_NONE );
    #endif
}
```

And then a lot of setDrawBuffer() calls where sprinkled all over the place to undo its effect.
Unfortunately there are places where this was not done and we end up stuck with GL_NONE as draw buffer.

**Comment by openscenegraph** [comment]
If there is no color buffer attached then it's appropriate for glDrawBuffer to be set to GL_NONE, the above code segment looks OK to me.

The only improvement to it would be to change the setDrawBufers(GL_NONE, true); and setReadBuffer(GL_NONE, true) to setDrawBuffers(GL_NONE, false) etc.  as there isn't any need to call glDrawBuffers with the same value repeatedly.  There won't be any harm in doing this repeatedly, it's just a small waste.

FYI, RenderStage::setDrawBuffer() just sets local RenderStage variables they don't actively do any GL calls, these GL calls are done later when required.

My best guess is that somewhere higher up in the chain isn't setting the draw buffers or colour attachments correctly.   I'm not about to go debugging 3rd party code on a platform that I don't have access to, this ain't my job.

On the OSG side that other problem I see is the need for a minor optimization.  Oh, the above glDrawBuffer() calls is sound, it's not down to a driver issue, it's a requirement for glCheckFramebufferStatus call to do the right thing.

Robert.

**Comment by filnet** [comment]
Apparently the requirement to have at least one color attachment affects OpenGL 4.1 and earlier (see https://open.gl/framebuffers)
