### ISSUE TITLE
The links to the Download and  Dependencies pages are broken.

### ISSUE THREAD

**Issue by zwcloud** [openscenegraph/OpenSceneGraph#496]
http://www.openscenegraph.org/index.php/documentation/platform-specifics/windows/37-visual-studio

> In the OpenSceneGraph directory, see the Downloads page and download the sources for the version you're interested in, or check out the sources from the SVN repository using the SVN client of your choice (for example TortoiseSVN on Windows).

The link to *the Downloads page* is broken: http://www.openscenegraph.org/index.php/downloads .
The link to the *the Dependencies page* is broken: http://www.openscenegraph.org/index.php/downloads/dependencies

**Comment by zwcloud** [comment]
Also http://www.openscenegraph.org/index.php/downloads/stable-releases is broken.

**Comment by zwcloud** [comment]
Another one broken link here:

In http://www.openscenegraph.org/index.php/download-section/dependencies

> The following two packages are compiled with VisualStudio 2017 RTM (VC14) for 64bit only (v141 platform toolset). If you need 32bit (x86), please use this package. Please ensure you have the correct Visual Studio version installed. You can use the ENV variable OSG_3RDPARTY_DIR to auto configure CMake. Package details, content list and sources are available here

The link to *OSG_3RDPARTY_DIR* is broken: http://www.openscenegraph.org/projects/osg/wiki/Support/UserGuides/EnvironmentVariables#a3rdPartyPackageforVS2008Sp1.

![image](https://user-images.githubusercontent.com/6965758/37507400-4238919e-2929-11e8-86e3-499b6035dd16.png)

**Comment by zwcloud** [comment]
Emm.. it seems most links on that website is broken.

**Comment by openscenegraph** [comment]
I have gone through the pages you have spotted link errors on and fixed them.  In many cases it will have been external websites or webpages being deleted.
