### ISSUE TITLE
IntersectVisitor.cpp: checking if floats is EQUAL to something

### ISSUE THREAD

**Issue by hansfilipelo** [openscenegraph/OpenSceneGraph#530]
Currently close to release at work so me myself don't have the time available to fix this right away. Dropping an issue here to see if someone might have the time. 

--------------------

There's issues with floating point comparisons within `operator ()` in the file `osgUtil/IntersectVisitor.cpp`. There are a few comparisons to check if a float is equal to zero (or 1.0 for that matter). These checks are done according to: 

```
float x = SOMETHING;
if (x == 0.0f) return;
else ...
```

Checking if a floating point value is EQUAL to something is not best practice, and could lead to issues with divisions within the function return floating point values that is `nan`. For a non-named application depending on OSG, I see these issues. The code should instead read something like: 

```
float x = SOMETHING;
float epsilon = SOMETHING_SMALL;
if (std::abs(x) < epsilon) return;
else ...
```

**Comment by openscenegraph** [comment]
IntersectVisitor,cpp has long been deprecated (12 years ago) and it's recommend that osgUtil::IntersectionVisitor and the likes of LineSegmentIntersector.cpp is used instead.  You'll find epsilon is used where appropriate in this modern classes.  

IntersectVisitor is just kept around for backwards compatibility and in general I prefer not to touch it as it doesn't get widely used so any regressions that we accidentally introduce we might not spot for a very long time as very few users ever use it.  

So if you are using IntersectVisitor righ tnow, jikes, you shoudln't be, port your code over to IntersectionVisitor and it's associated Intersector classes, they are just far better all-round.

**Comment by openscenegraph** [comment]
A small update.  To avoid confusion in the future I've gone ahead and removed osgUtil::IntersectVisitor from OSG master.  It'll still part of OSG-3.6.x but releases after this won't have osgUtil::IntersectVisitor. 

I'm going to close this Issue as it's now resolved for master, and for the stable releases that still contain it the recommendation is DO NOT USE IntersectVisitor, use IntersectionVisitor/LineSegmentInersector instead.

**Comment by hansfilipelo** [comment]
Thanks for clarification and your effort. Great work.
