### ISSUE TITLE
dynamic loading of a file containing particle effects doesn't work

### ISSUE THREAD

**Issue by ssnakus** [openscenegraph/OpenSceneGraph#539]
hi every one;
i'm used to load  files containing particle effects, within the handle method of GUIEventHandler like this:
class mymethod : public osgGA::GUIEventHandler {
...
 bool handle(...)
    {
        case(osgGA::GUIEventAdapter::PUSH):
        {
         ...
         MatrixTrans->addChild(osgDB::readNodeFile("cessnafire.osg"));//the cessnafire.osg contains a particle effects
         ...
       }
but since i updated to the 3.6 version it don't work any more, there is only the plane model but not the fire, is this a bug or it's not supposed to be done as i do?
thanks

**Comment by openscenegraph** [comment]
There is no way to know whether it's a usage error or an OSG bug from the details provided.

Could you create a small test program that illustrates what you think is the issue?  Once I have a test case I can test it and investigate.

As a general comment, the best place for this type of discussion is on the osg-users mailing list/forum as it really helps to get the wider community involved as others can provide insights from their own experiences.

Thanks,

**Comment by ssnakus** [comment]
Ok thanks, it’s my first post in here, i’ll do as you said for the next ones

**Comment by openscenegraph** [comment]
I have created a test program that reproduces the problem and confirms that it works wiht 3.4 but not master.  Now I have a test case I'll look into what is going on.

**Comment by openscenegraph** [comment]
I have checked in a fix for this bug into OSG master and the OpenSceneGraph-3.6 branch.  This means the up coming 3.6.1 stable point release will include this fix.

https://github.com/openscenegraph/OpenSceneGraph/commit/b9d5e8f505bd6ebf07c5a5ef5aedd533fe3464c6

**Comment by ssnakus** [comment]
Cool, thank you for the remarquable work
