### ISSUE TITLE
'unistd.h' No such file or directory

### ISSUE THREAD

**Issue by knowthyselfcn** [openscenegraph/OpenSceneGraph#547]
OSG repo,  branch:  OpenSceneGraph-3.6 , tag: OpenSceneGraph-3.6.0
3rd party lib : vs2013 v5, x64, small, downloaded from https://download.osgvisual.org/3rdParty_VS2013.5_v120_x64_V10_small.7z.

CMake options:  two deprecated relevant items toggled off;  OSG_GL3_AVAILABLE toggled on; 

This problem could be solved simply by commenting out line 454 of zconf.h on Windows.

**Comment by openscenegraph** [comment]
Could you tell me where the compile error is, I can't find any zconf.h file in the OSG code base so I really don't have anything to go at this point.

**Comment by openscenegraph** [comment]
I have been looking for zconf.h and can only find it in a 3rd party dependency.  This isn't an error in the OpenSceneGraph codebase, so it's not something we can directly resolve.  You need to contact the author of the zconf or the author of the 3rd party dependencies.
