### ISSUE TITLE
License situation unclear

### ISSUE THREAD

**Issue by stoecker** [openscenegraph/OpenSceneGraph#552]
In the process of updating OpenSceneGraph to 3.6.1 package of openSUSE the automatic license check stops release because of massive license mismatch

https://build.opensuse.org/request/show/613082

The license file states that OSG is OpenSceneGraph Public License 0.0, which in SPDX format means LGPL-2.1-only WITH WXwindows:

https://spdx.org/licenses/LGPL-2.1-only
https://spdx.org/licenses/WXwindows

That does not really match and also a new name is not so nice. SPDX would have following valid combination describing your license situation conflict free:

LGPL-2.1-only WITH WxWindows-exception-3.1

https://spdx.org/licenses/LGPL-2.1-only
https://spdx.org/licenses/WxWindows-exception-3.1.html

Beside this most of the source files say this software is GPL-2.0-only.

Could you please clear the license situation and bring source and license together, so they match.

**Comment by openscenegraph** [comment]
The OSG has been successfully used by ten of thousands of users/companies using the OSGPL without problem.  I am not aware of any internal mis-matches with licensing within the OSG code base.

You suggest "massive license mismatch" but your links don't really tell me anything what specifically is wrong where.

I'm not familiar with "SPDX format" and don't have any recollection of any OSG user in the 18 years I've been project lead raising this as a topic.  The OSG is widely distributed by other project/distro's and this is the first time anyone has ever raised any "issue".  This might a topic dear to your heart but it's been an issue for OSG users.

The OSG has core libraries that are all OSGPL, there are plugins that use 3rd party libraries that in some case add license restrictions, there is nothing the OSG project can do about 3rd party libraries, we just have to abide.  The OSG over a hundreds of plugin, none of which I am aware of having licensing issues.

If there is a specific issue somewhere please tell me as I'm not going to waste my time trying to second guess stuff that some automated system isn't happy with.  This really could well just be an issue with the automated system you are using.

**Comment by stoecker** [comment]
Copying contents from the provided link:
@babelworx declined the legal report with the following comment: Large number of GPL files:
   OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPlugins/xine/video_out_rgb.c
   OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPlugins/xine/video_out_rgb.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/Cluster.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/Cluster.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ExportHTML.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ExportHTML.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/PointsEventHandler.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/PointsEventHandler.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ReadShowFile.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ReadShowFile.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/SDLIntegration.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/SDLIntegration.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ShowEventHandler.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/ShowEventHandler.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/SpellChecker.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/SpellChecker.h
    OpenSceneGraph-OpenSceneGraph-3.6.1/applications/present3D/present3D.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/AnimationMaterial
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/CompileSlideCallback
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/KeyEventHandler
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/PickEventHandler
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/PropertyManager
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/SlideEventHandler
    OpenSceneGraph-OpenSceneGraph-3.6.1/include/osgPresentation/SlideShowConstructor
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/AnimationMaterial.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/CompileSlideCallback.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/KeyEventHandler.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/PickEventHandler.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/PropertyManager.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/SlideEventHandler.cpp
    OpenSceneGraph-OpenSceneGraph-3.6.1/src/osgPresentation/SlideShowConstructor.cpp
    [Plugins left out]

As I already said above: "many of the source files say this software is GPL-2.0-only." This is incompatible with an License file saying this is LGPL with exception.

SPDX is the central instance of License information for packaging. Using the suggested "LGPL-2.1-only WITH WxWindows-exception-3.1" instead of your current license file would reduce troubles, as the current file has 3 different sections which are somewhat conflicting. This is only a clearer representation of the same license (and would reduce the need to define another license name).

But the main problem is that the sources say this is GPL software which does not match the LICENSE file. Many sources contain

 * This software is open source and may be redistributed and/or modified under
 * the terms of the GNU General Public License (GPL) version 2.0.
 * The full license is in LICENSE.txt file included with this distribution,.

This is simply untrue in your case, as the LICENSE.txt does not contain GPL-2.0. So either the texts or the license file must be fixed.

Beside that:
If the plugins have different licenses, but are packaged together in a single package, that fact and the relevant licenses should be stated in the LICENSE file, an additional plugin license file or in the directory of each plugin. I found only 2 plugins with a separate LICENSE file.

> I'm not familiar with "SPDX format" and don't have any recollection of any OSG user in the 18 years I've been project lead raising this as a topic. The OSG is widely distributed by other project/distro's and this is the first time anyone has ever raised any "issue". This might a topic dear to your heart but it's been an issue for OSG users.

This is not an issue dear to my heart, but simply a common issue for many projects, that license situation is unclear or unacceptable. Most projects simply don't care and software is nevertheless used, as most often nobody else cares as well. But for distributions unclear license situation is dangerous and does matter and thus the checks for valid licenses get more strict over the time. I had similar requests for my own projects e.g. from Debian and it is not easy to solve it fully. Minimum requirement was to state correct license in all sources and state all the licenses for all parts clearly if there are different licenses.

E.g. for JOSM we have an CONTRIBUTION file which list all external contributions and their license
https://josm.openstreetmap.de/browser/josm/trunk/CONTRIBUTION
The final result is then GPL2 or GPL3 depending on the compilation contents.

**Comment by openscenegraph** [comment]
Thanks for the list.  I am the author of osgPresentation and present3D, this was a separate project under GPL but when I merged it I must have missed changing all the heads to OSGPL.  I will update them, but this will need to go into a 3.6.2 release.

The xine plugin is GLP'd but deprecated and as far as I'm aware not used these days.  To ease things I can remove this in 3.6.2.

Adopting another license, even similar to the OSGPL, could cause problems with members of the community that has officially reviewed and OK'd it internally for their projects, they may need to go back to lawyers to clarify it.  This is something for discussion in the OSG community.

FYI, I have just tagged the 3.6.1 after a great deal of effort and coordination with the OSG community, going for another stable release so soon after 3.6.1 is not something I have personally have the time for or will the community have patience for so you'll need to be patient for us to tackle once the next window for a point release comes about.

**Comment by stoecker** [comment]
> Thanks for the list.

This is probably not complete. I think the licensedigger stops at a certain number of files.

> To ease things I can remove this in 3.6.2.

I don't think removing is necessary in any case. It only must be documented and consistent. Copy the correct LICENSE file to the plugin directory (and if possible collect that information in one file to ease work for other users :-) and everything is fine.

I'm pretty sure if you have a mix of licenses, that you also have some incompatibilities, but I'm no lawyer and don't care soooo much. For me personally the most which could be requested is that all files state the correct license and the documentation is understandable and contains the necessary information without too much work to find it (e.g. a file which states license for each plugin which has not the same as the base software and the license texts are added somewhere).

If I remember right a Jenkins task for JOSM checks if license header in each file is correct, so we recognize if something is missing and don't get a mismatch in future again.

**Comment by openscenegraph** [comment]
I fixed the licensing for osgPresentation and present3D and removed xine:

**Comment by openscenegraph** [comment]
I have updated the OpenSceneGraph/LICENSE.txt so that it now uses the latest text for LGPL-2.1-only and the WxWindows 3.1 exceptions, updating the version to OSGPL-1.0.

With this change I have done what can to resolve the questions that I've been made aware of.  This changes are now part of the master and the OpenScenGraph-3.6 branch so will roll out in 3.6.3 stable release.  If there are any further areas that need tightening up then please open an new Issue here with the specific areas that need to be looked at, or just contact me directly.
