### ISSUE TITLE
Android.bp or Android.mk available ?

### ISSUE THREAD

**Issue by AhmedX6** [openscenegraph/OpenSceneGraph#553]
Hello,

I would like to integrate this library to my aosp directly on the system.img
With an Android.mk or an Android.bp that would be easier.
Is this available ?

**Comment by openscenegraph** [comment]
We don't publish binaries directly, 3rd parties sometimes share binaries they have built.  The best place to ask if any are available for the platform you are looking for is by joining the osg-users mailing list/forum and asking a question there.

**Comment by AhmedX6** [comment]
I'm not asking about binary.
I'm asking about a specific Makefile for Android. (Like Android.bp or Android.mk) instead of CMakeLists Makefile.
