### ISSUE TITLE
Many virtual function-related compiler warnings reported on Mac

### ISSUE THREAD

**Issue by x6herbius** [openscenegraph/OpenSceneGraph#564]
I'm using OpenSceneGraph as a library in my application, and when I compile with Clang on my Mac in C++11 mode, I get many compiler warnings from various OSG headers I'm using. They're mostly to do with aspects of virtual functions, and include:

* Hidden overloaded virtual functions.
  `../submodules/OpenSceneGraph/include/osg/Camera:604:25: warning: 'osg::Camera::DrawCallback::run' hides overloaded virtual function [-Woverloaded-virtual]`
  `../submodules/OpenSceneGraph/include/osg/Callback:80:22: note: hidden overloaded virtual function 'osg::Callback::run' declared here: different number of parameters (2 vs 1)`
* Missing `override` specifiers on functions implemented by the `META_Object()` macro in my own subclasses.
  `../calliper/UI/orthographiccameracontroller.h:13:5: warning: 'cloneType' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]`
  `../submodules/OpenSceneGraph/include/osgGA/GUIEventHandler:59:9: note: overridden virtual function is here`

My only real option is to disable these warnings via global compiler flag, as even if I use a `#pragma clang diagnostic push/pop` around the included headers, some warnings still inexplicably seem to sneak their way in. I also can't do anything about the `META_Object()` macro in my own classes.

Are there plans to eliminate these warnings?

**Comment by openscenegraph** [comment]
The override features isn't compatible with older C++ compilers so there is no way we can adopt it in the current OpenSceneGraph as it would break compatibility with compilers that the user base are presently using.  For the future OpenSceneGraph-4.0 release I plan to make C++11 a minimum and could perhaps look at adding more C++ keywords to help be more specific to the compilers, however this will be year or so off. 

As the warnings aren't actually helpful in this instance, I would recommend just adjusting the cmake build options to quieten down if they are an issue for you.  In your own classes perhaps just implement your own macro or just implement the required methods explicitly - have a look at the implementation of the MET_Object() macros, there isn't too much too them.

**Comment by DieSlower** [comment]
If for OSG 3.4 we are changing the compiler version, can we change it to something newer, like C++ 14 or 17 instead? C++ 11 is already 7 years old! And by the time OSG 3.4 will be out, (lets say a year) C++ 17 will be in every compiler.
