### ISSUE TITLE
bug (3.6.2): resetVertexAttributeAlias not always work with assignTexCoordArrayDispatcher

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#571]
OSG 3.6.2 / Core Profile

resetVertexAttributeAlias creates 8 default aliases in the State constructor:

https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/State.cpp#L97

 But when one use more texture units, then the following will fail:

https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/VertexArrayState.cpp#L658

Because _state->getTexCoordAliasList()[i] is not initialized.

?

**Comment by mp3butcher** [comment]
If you need more than 8 texture coord, why don't you use vertex attribute instead?

**Comment by mp3butcher** [comment]
I'm afraid i don't understand the issue
can you post (and refer here) a osg forum topic with a sample code illustrating the bug?

**Comment by openscenegraph** [comment]
8 was chosen as a default based on historical OpenGL fixed function norms.

What are you using more than 8 texture coord arrays for?

**Comment by remoe** [comment]
osgEarth with a large setup :) It's more conceptional. It should not possible to overrun this limits.

**Comment by gwaldron** [comment]
Remo, does [this fix](https://github.com/gwaldron/osgearth/issues/1098) also address the issue here? If not, can you use the same Realize Operation concept to set a higher limit?

**Comment by remoe** [comment]
Glenn, I will test this next week.

**Comment by remoe** [comment]
this can be solved with state->resetVertexAttribAlias(false) on Realize Operation on GC.
