### ISSUE TITLE
Why can't you give developer the compiled frameworks or static library

### ISSUE THREAD

**Issue by shaojiankui** [openscenegraph/OpenSceneGraph#575]
Why can't you give developer the compiled frameworks or static library。OpenSceneGraph is very hard to compile by ourself。 i try many time,finaly both failure。Official Cmake tutorial configuration is not clear，not list specific items and need removed items。

**Comment by robertosfield** [comment]
There aren't official binaries as I don't personally have the capacity to build Windows binaries, as work under Linux.  Members from community do publish their own binaries.  It's a rather open ended issue though, there are so many platform combinations that you can't cover them all, while the source code does cover all combinations.

If you are seeing issues configuring and building the OpenSceneGraph the best place to ask them is on the osg-users mailing list/forum.  Also if you do spot mistake in the docs then this will be a good place to report them as well.
