### ISSUE TITLE
Build fail because of the "GREATER_EQUAL" comparison in FindCOLLADA.cmake

### ISSUE THREAD

**Issue by roccomartino** [openscenegraph/OpenSceneGraph#580]
Hello, 

the "GREATER_EQUAL" comparison has been introduced in CMake 3.7 (https://cmake.org/cmake/help/v3.7/release/3.7.html#commands), but the minimum version required by OSG is 2.8.0.
That causes cmake to fail for versions in between:

 CMake Error at CMakeModules/FindCOLLADA.cmake:32 (ELSEIF):
  given arguments:

    "MSVC_VERSION" "GREATER_EQUAL" "1900"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:752 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!

[rmartino] local $ cmake --version
cmake version 3.5.2

Thanks for your work

**Comment by sbrkopac** [comment]
Please try the following [fork](https://github.com/sbrkopac/OpenSceneGraph). If it works I'll open a PR.

**Comment by roccomartino** [comment]
Fine, it works. Thanks

**Comment by openscenegraph** [comment]
Now merged thanks Sam,
