### ISSUE TITLE
How to merge all the osgb files which are the same detail level into one, and convert it to obj file or fbx file?

### ISSUE THREAD

**Issue by lhsheild** [openscenegraph/OpenSceneGraph#584]
Sorry, I'm first to OSG and C++. So...I really need help, thanks a lot

**Comment by mp3butcher** [comment]
the forum is here http://forum.openscenegraph.org/
ask question there

**Comment by openscenegraph** [comment]
The OpenSceneGraph Issue tracker is for tracking bugs in the OSG, not general support.  If you want general support please use the osg-users mailing list/forum.
