### ISSUE TITLE
memory leak？

### ISSUE THREAD

**Issue by 360CodeSafe** [openscenegraph/OpenSceneGraph#585]
applications/present3D/ReadShowFile.cpp 165:

in line 159: char* str = strdup(cur->contents.c_str());  //memory is allocated

but at the end of funciton , memory is not freed.

**Comment by openscenegraph** [comment]
Really, do you plan to keep highlight putenv issues?  

I said in my last comment some putenv implementations don't take a copy, some do, and different rev's of putenv on the same platform can behave differently.  The only way to resolve this type of issue is not use putenv at all.  

For present3D putenv is useful for some purposes.  I'm perfectly happy with the small risk of a very small memory leak that may happen on certain platforms.  

Please remember presetn3D is niche application, it's not part of the core OSG library.

I'm close this issue as it's not resolvable and it's competently benign and affects only present3D.
