### ISSUE TITLE
BUG: Don't find osg debug version libraries when be compile osgQt debug version

### ISSUE THREAD

**Issue by KangLin** [openscenegraph/OpenSceneGraph#599]
Don't find osg debug version libraries when be compile osgQt debug version.

The osg debug version libraries is exist in path: /d/source/RabbitIm/ThirdLibrary/build_script/../windows_msvc14_x86_qt5.11.1_Debug 

cmake command:
cmake .. -DCMAKE_INSTALL_PREFIX=/d/source/RabbitIm/ThirdLibrary/build_script/../windows_msvc14_x86_qt5.11.1_Debug -DCMAKE_BUILD_TYPE=Debug -G"Visual Studio 14 2015" -DDYNAMIC_OPENSCENEGRAPH=ON -DWIN32_USE_MP=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_OSG_EXAMPLES=OFF -DQt5_DIR=/c/Qt/Qt5.11.1/5.11.1/msvc2015/lib/cmake/Qt5 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_MODULE_PATH=/d/source/RabbitIm/ThirdLibrary/build_script/../windows_msvc14_x86_qt5.11.1_Debug/lib/cmake -DCMAKE_BUILD_TYPE=Debug

Error information:
-- Could NOT find osgDB (missing: OSGDB_LIBRARY)
-- Could NOT find osgGA (missing: OSGGA_LIBRARY)
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY)
-- Could NOT find osgText (missing: OSGTEXT_LIBRARY)
-- Could NOT find osgViewer (missing: OSGVIEWER_LIBRARY)
-- Could NOT find osgWidget (missing: OSGWIDGET_LIBRARY)
-- Could NOT find osg (missing: OSG_LIBRARY)
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY)
CMake Error at D:/software/cmake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find OpenSceneGraph (missing: OSGDB_FOUND OSGGA_FOUND
OSGUTIL_FOUND OSGTEXT_FOUND OSGVIEWER_FOUND OSGWIDGET_FOUND OSG_FOUND
OPENTHREADS_FOUND) (found suitable version "3.6.2", minimum required is
"3.0.0")
Call Stack (most recent call first):
D:/software/cmake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
D:/software/cmake/share/cmake-3.12/Modules/FindOpenSceneGraph.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:130 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "D:/source/osgQt/build_windows_msvc/CMakeFiles/CMakeOutput.log".

**Comment by openscenegraph** [comment]
I am closing this Issue as it's not directly related to the OpenSceneGraph itself, but an ancillary project.

Could you post this issue to the osgQt Issue tracker rather than the main OpenSceneGraph Issue tracker as the later project no longer has Qt support built in and we have different dev's maintaining osgQt than OpenSceneGraph.
