### ISSUE TITLE
X11: osg::GraphicsContext::createGraphicsContext(traits.get()) seams buggy

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#602]
I tried to run osgtexturecompression but GraphicContext creation fails in some way.

**Comment by openscenegraph** [comment]
I just tested it on my Kubuntu 18.04/NVidia system and everything works fine, the window comes up and all the views are rendered correctly.

On a quick review of the code I can't see any obvious errors.

Can you provide information about the error you are seeing and what hardware/drivers you are using.

**Comment by mp3butcher** [comment]
It can be my branch...but it strange i haven't got any diffs  osgViewer...

**Comment by openscenegraph** [comment]
This is standard features of X11, just ripping out a feature that was worked fine for many years because one OS combination has a driver issue isn't appropriate. 

Do the other OSG examples work OK?

**Comment by mp3butcher** [comment]
I do agree it a Wayland compatibility is gnome only and 
osg can change for such a temporary specificity

I will dig it (seams XOpenDisplay failed)
 but perhaps this bug fix worth to be leave opened to help to end users

**Comment by openscenegraph** [comment]
I don't want to let the Issue tracker fill up with items that aren't direct issues that need fixing in the OSG itself.  

For this particular issue you seeing I still need to know how extensive it is, are the other OSG examples working OK?  It could be that a small refactor of this example to use default OSG window creation will resolve the issue for you without any needs of hacks to to the core.

**Comment by mp3butcher** [comment]
Arg I can't achieve to reproduce the behavior
when I comment back 
WaylandEnable=false
The display stays :0
weird gnome
