### ISSUE TITLE
stdexcept header missing

### ISSUE THREAD

**Issue by proyan** [openscenegraph/OpenSceneGraph#61]
Hello

During installation, I got an error saying std::runtime is not a member of std (at /src/osgPlugins/daedaewriter.cpp line267). Simply including stdexcept solved it. Please include it in the source as well.

Thanks,
Rohan

**Comment by openscenegraph** [comment]
Hi Rohan,

Could you specific which version of the OSG, what OS, build tools and method of installation you used as the error you describe is not one reported in the community before.

Robert.

**Comment by proyan** [comment]
Hi

I am using:
osg version 3.5.1
ubuntu 12.04 32-bit
gcc 4.6.4
cmake 2.8.7

Hope this helps
Rohan

**Comment by openscenegraph** [comment]
Thanks for the clarification.
