### ISSUE TITLE
call many times ref_ptr<GraphicsContext> pbuffer = new osgViewer::PixelBufferWin32(traits); memory leak

### ISSUE THREAD

**Issue by zengjinchong** [openscenegraph/OpenSceneGraph#613]
i wrote my code like this：
for (int i = 0; i < 100000; i++)
	{
		//ref_ptr<osgViewer::Viewer> viewer = new osgViewer::Viewer;

		int width = 1000;
		int height = 1000;

		if (true) {
			ref_ptr<DisplaySettings> ds = DisplaySettings::instance().get();
			ref_ptr<GraphicsContext::Traits> traits = new GraphicsContext::Traits(ds);

			 {
				//viewer would use fullscreen size (unknown here) pbuffer will use 4096 x4096 (or best avaiable)
				traits->width = width;
				traits->height = height;
				traits->pbuffer = true;
			}

			ref_ptr<GraphicsContext> pbuffer = new osgViewer::PixelBufferWin32(traits);
			/*pbuffer->clear();
			pbuffer->close(true);*/
			/*pbuffer->releaseContext();*/
			pbuffer->close(true);
		}
	}

the memory increase fast， it cann't decrease. i wonder it is a bug of osg in create Graphic context.

**Comment by zengjinchong** [comment]
In the function ~TemporaryWindow(), 
  if (_context)
    {
        // mew 2005-05-09 commented out due to crashes.
        // possible causes are unsafe destructor ordering, or context already
        // deleted by window deletion; see:
        // http://openscenegraph.org/pipermail/osg-users/2005-May/052753.html
        //wglDeleteContext(_context);
        _context = 0;
    }
the memory leak is because  of this sentence

**Comment by openscenegraph** [comment]
Why would you ever try to create 100,000 windows?  Let alone pbuffers.  Are you just investigating a possible leak so have gone to extreme lengths to increase the magnitude of the issue?

Looking at the possibly offending code, commenting out the wglDeleteContext() was clearly added address a crash.  If we comment it back in, might it start crashing again?  FYI, MEW -> Mike Weiblen.

As a general recommendation these days you use FBO's instead of PBuffers, the later are now only required for completely off screen rendering.

As there may well be a regression if we change the code the best way to go forward with this is to discuss it openly on the osg-users mailing list/forum and while Mike is no longer an OSG contributor it may well be worth pulling him in to see if he remembers details about the crash.  

If we can get to the bottom of the original crash and understand it, then resolve it then it should be safe to add back in the wglDelteContext(), but we can't do that before this as a crash is far more danagerous to user application than a minor possible leak.

**Comment by zengjinchong** [comment]
i coded to snap thoundsands of photos from model so i need to use PBuffers and need to use thondsand of windows;  thanks for you help.

**Comment by openscenegraph** [comment]
Creating thousands of pbuffers one per photo is a really, really bad way to implement it.  Just create a single pbuffer and reuse it.  It will be so much more efficient.  The graphics hardware and OpenGL are not designed to handle creating and destroying objects in the way you have been using it, they are design for creating of windows and buffers once and then reused many times.

**Comment by zengjinchong** [comment]
if the image size is different, can i do that?

**Comment by toeb** [comment]
I have the same issue.
I wrapped OSG into C# and Created a WPF control which uses a Pixelbuffer to render.  
Everytime I create a OSG WPF Control I create a new Pixelbuffer.  So I am experiencing a 2MB leak every time + some windows handles.

As Khronos writes the pixelbuffers should be deallocated when unused.  
```
    The intent of the pbuffer semantics is to enable implementations to
    allocate pbuffers in non-visible frame buffer memory.  These
    pbuffers are intended to be "static" resources in that a program
    will typically allocate them only once rather than as a part of its
    rendering loop.  (Pbuffers should be deallocated when the program is
    no longer using them -- for example, if the program is iconified.)
```

Also even if the memory leak were not a problem the ensuing Handle leak will crash the process when it reaches 10k which I noticed the hard way when it crashed the production line where it was used to render images in background after working for 60 days and then reached the handle limit :/  

Anyway I Copied the PixelbufferWin32 code into my own library and uncommented the `wglDeleteContext` call and now it works fine for me.  Luckily OSG code is nice and modular so this was the easiest option for me.

I don;t know if you ever want to fix it - but the comment indicates that the crash was never understood.

**Comment by zengjinchong** [comment]
I also uncommented the wglDeleteContext call and now it works in single-thread environment. &nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tobias Becker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上8:37
收件人:&nbsp;"openscenegraph/OpenSceneGraph"<OpenSceneGraph@noreply.github.com&gt;;
抄送:&nbsp;"别忘了￥当个好人"<1252286811@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openscenegraph/OpenSceneGraph] call many times ref_ptr<GraphicsContext&gt; pbuffer = new osgViewer::PixelBufferWin32(traits); memory leak (#613)





 
I have the same issue.
 I wrapped OSG into C# and Created a WPF control which uses a Pixelbuffer to render.
 Everytime I create a OSG WPF Control I create a new Pixelbuffer.  So I am experiencing a 2MB leak every time + some windows handles.
 
As Khronos writes the pixelbuffers should be deallocated when unused.
     The intent of the pbuffer semantics is to enable implementations to     allocate pbuffers in non-visible frame buffer memory.  These     pbuffers are intended to be "static" resources in that a program     will typically allocate them only once rather than as a part of its     rendering loop.  (Pbuffers should be deallocated when the program is     no longer using them -- for example, if the program is iconified.)  
Also even if the memory leak were not a problem the ensuing Handle leak will crash the process when it reaches 10k which I noticed the hard way when it crashed the production line where it was used to render images in background after working for 60 days and then reached the handle limit :/
 
Anyway I Copied the PixelbufferWin32 code into my own library and uncommented the wglDeleteContext call and now it works fine for me.  Luckily OSG code is nice and modular so this was the easiest option for me.
 
I don;t know if you ever want to fix it - but the comment indicates that the crash was never understood.
