### ISSUE TITLE
getWindowingSystemInterface() fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by omaralvarez** [openscenegraph/OpenSceneGraph#615]
```cpp
    osg::GraphicsContext::WindowingSystemInterface* wsi = 
    osg::GraphicsContext::getWindowingSystemInterface();
    if ( !wsi ) {
        std::cout << "ERROR. Could not access the Windowing System Interface" << std::endl;
        throw -1;
    }
  
    std::cout << wsi->getNumScreens() << " screen(s) detected" << std::endl;
    for ( unsigned int screen=0 ; screen < wsi->getNumScreens(); screen++ ) {
        osg::GraphicsContext::ScreenIdentifier screen_id(screen);
        osg::GraphicsContext::ScreenSettings screen_settings;
        wsi->getScreenSettings( screen_id, screen_settings );
        std::cout << "  Screen #" << screen << " : "
                  << screen_settings.width << "x" << screen_settings.height << " "
                  << screen_settings.refreshRate << "Hz "
                  << screen_settings.colorDepth << " bit" << std::endl;
    }
```
This simple code snippet fails for me on Ubuntu 18.04 (OSG 3.6.2 and 3.4.0) with:

```sh
Invalid MIT-MAGIC-COOKIE-1 keyA Unable to open display ":0.0"
Invalid MIT-MAGIC-COOKIE-1 keyA Unable to open display ":0.0"
0 screen(s) detected
Invalid MIT-MAGIC-COOKIE-1 keyA Unable to open display ":0.0"
```
I have a dedicated NVIDIA GPU with latest drivers (396), running ```osgviewer``` works properly. I also checked that ```getWindowingSystemInterface``` is being called at the correct time. I have tested this after creating a viewer and it also fails.

```sh
RegisterWindowingSystemInterfaceProxy()
X11WindowingSystemInterface()
GraphicsContext::setWindowingSystemInterface() 0x55aada1ee9d0   0x7f69e2fc9978
GraphicsContext::getWindowingSystemInterface() 0x55aada1ee9d0   0x7f69e2fc9978
```
Another thing that makes no sense is that my X session is not ```:0.0``` but ```:1.*```, but no matter what ```$DISPLAY``` environment variable has, it is ignored, it is looking for screens in the wrong X session. At this point I don't know what else to try. Am I doing something wrong? Any ideas?

**Comment by omaralvarez** [comment]
Thank you for the quick answer. Yes, I have the standard Ubuntu 18.04 install, using NVIDIA ppa drivers. I will report it there too.

**Comment by LaurensVoerman** [comment]
Hi Omar,
did you try to set the OSG_SCREEN variable? I'm on windows, but the code
suggests
export OSG_SCREEN=1
might fix your problem
Regards, Laurens.

**Comment by omaralvarez** [comment]
I have just tried setting ```OSG_SCREEN=1``` and it's still not working. Thanks for the suggestion!

**Comment by omaralvarez** [comment]
I have created a repo so that you guys can test if the problem occurs easily:

https://github.com/omaralvarez/osgtest

**Comment by mp3butcher** [comment]
https://github.com/openscenegraph/OpenSceneGraph/issues/602

**Comment by omaralvarez** [comment]
Right on the money. I will test and report back.

**Comment by mp3butcher** [comment]
WindowingSystemInterface is an interface implemented in system dependant osgViewer::XXXWindowingSystemInterface
What may be done is to add a system agnotistic windowInterface in osgviewer

```
> #ifdef SYS
> #define osgViewer::WindowingSystemInterface osgViewer::SYSWindowingSystemInterface
> #else...
```

**Comment by openscenegraph** [comment]
The best solution would be to read the DISPLAY env var to set things up rather than manually tie then to 1.0, so the following would be what I'd recommend:

    osg::GraphicsContext::ScreenIdentifier main_screen_id;
    main_screen_id.readDISPLAY();

    std::cout << wsi->getNumScreens(main_screen_id) << " screen(s) detected" << std::endl;

**Comment by omaralvarez** [comment]
Thanks a lot to everybody for the help, here is teh final code that works:

```cpp
osg::GraphicsContext::WindowingSystemInterface* wsi = osg::GraphicsContext::getWindowingSystemInterface();
    if ( !wsi )
    {
        std::cout << "ERROR. Could not access the Windowing System Interface" << std::endl;
        throw -1;
    }

    osg::GraphicsContext::ScreenIdentifier main_screen_id;
    main_screen_id.readDISPLAY();
    main_screen_id.setUndefinedScreenDetailsToDefaultScreen();

    std::cout << wsi->getNumScreens(main_screen_id) << " screen(s) detected" << std::endl;
    for ( unsigned int screen=0 ; screen < wsi->getNumScreens(main_screen_id); screen++ )
    {
        osg::GraphicsContext::ScreenIdentifier screen_id(main_screen_id.hostName, main_screen_id.displayNum, screen);
        osg::GraphicsContext::ScreenSettings screen_settings;
        wsi->getScreenSettings( screen_id, screen_settings );
        std::cout << "  Screen #" << screen << " : "
                  << screen_settings.width << "x" << screen_settings.height << " "
                  << screen_settings.refreshRate << "Hz "
                  << screen_settings.colorDepth << " bit" << std::endl;
    }
```
I'm thinking of contributing fixing this in ```osg::GraphicsContext::WindowingSystemInterface```, anyone thinks it would be a welcome contribution?

**Comment by mp3butcher** [comment]
indeed..
the trick is a bit cryptic without any representation in the sources

**Comment by mp3butcher** [comment]
done
https://github.com/openscenegraph/OpenSceneGraph/pull/621
