### ISSUE TITLE
FindAVFoundation.cmake is broken on OSX 10.11 (and above)

### ISSUE THREAD

**Issue by robertcastleDAQRI** [openscenegraph/OpenSceneGraph#63]
The find script is looking for specific versions of OSX rather than versions above a suitable release:

`IF(${OSG_OSX_SDK_NAME} STREQUAL "macosx10.8" OR ${OSG_OSX_SDK_NAME} STREQUAL "macosx10.9" OR ${OSG_OSX_SDK_NAME} STREQUAL "macosx10.10")`

**Comment by openscenegraph** [comment]
I have added macosx10.11 to the list and checked this into OpenSceneGraph master and 3.4 could you please test (I don't have OSX myself.)
