### ISSUE TITLE
osgDB::findDataFile sometimes succeeds on Windows Server 2016 even though file does not exists

### ISSUE THREAD

**Issue by sanderaernouts** [openscenegraph/OpenSceneGraph#634]
We are seeing some issues in the OSG OpenFlight plugin when we try to read .tga files on Windows Server 2016. The plugin looks for the existence of a .tga.attr file which is optional. This file does not exist for the .tga files but in some (random) cases osgDB::findDataFile reports it found a file even though it does not exist. In this case osgDB::findDataFile returns a `\`. The code interprets a non empty string as "file found" and will try to read a file named `\`.

The error does not always occur in the same place, we have several models that reference the same .tga file and any of those models may or may not fail on each run of the program.

We are using OSG version 3.5.1.
We have run the same program on Windows 10 and Windows 7 before that without issues.

Below is a screenshot of the log file that shows when the error occurs.
![image](https://user-images.githubusercontent.com/6184673/46611757-fe3a1480-cb0e-11e8-85e8-6100074fa946.png)

**Comment by mp3butcher** [comment]
As an advice: try the 3.6.x release

**Comment by robertosfield** [comment]
I don't recall others users reporting this anything like this issue, so it's unlikely there is a specific fix for it, it may not even be an OSG bug...  the only way to confirm the later would be to have a test case that reproduces the problem.

The first step has to be updating to a support version of the OSG i.e. the latest stable release 3.6.3, developer releases like 3.5.1 aren't supported - it's just an old tag in the history of the development towards 3.6.x, that almost no one else will be using it.    The 3.6.x series has undergone lots of testing and refinement, it may be that this bug is fixed already.

If the problem still exits with 3.6.3 then the next step would be to create a test dataset that you can share with others so they the community can reproduce the problem, hunt the issue down and get a fix for it checked in.  Failing the ability to create a test that others can use, just compiling the OSG from source and digging into the debugger yourself will be the most productive approach.

**Comment by sanderaernouts** [comment]
@mp3butcher @robertosfield thanks for the quick replies. I will check with our team(s) if upgrading to 3.6.x solves the issue. If not I will try to come back with a test dataset that reproduces the error on Windows Server 2016 that we can share.

**Comment by sanderaernouts** [comment]
We have done some further investigation but since we are on the verge of a release we cannot update to 3.6.x yet so we did our investigations/testing against 3.5.1. However we found that the code that seems to cause the issue has not been changed between 3.5.1 and the latest version on master here on github so we think it is valuable to share our findings here anyway.

We found that the issue is caused by the fact that the path to the `.tga.attr` file is longer than `MAX_PATH` when it is passed into the `std::string osgDB::getRealPath(const std::string& path)` function in [osgDB\FileNameUtils.cpp (line 292)](https://github.com/openscenegraph/OpenSceneGraph/blob/0e87a86404692eb079ecb0f052efd4523ff0ff59/src/osgDB/FileNameUtils.cpp#L292). So this issue is most likely not Windows Server 2016 specific but Windows specific instead. Maybe it is related to this (StackOverflow question](https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows#1880453).

When this occurs the `std::string osgDB::getRealPath(const std::string& path)` function in [osgDB\FileNameUtils.cpp (line 292)](https://github.com/openscenegraph/OpenSceneGraph/blob/0e87a86404692eb079ecb0f052efd4523ff0ff59/src/osgDB/FileNameUtils.cpp#L292) may return an incorrect value like `\` instead of an empty string. After this the code behaves as if the `.attr` file exists which is not the case. We do not have `OSG_USE_UTF8_FILENAME` defined so we hit the code that starts at [line 333](https://github.com/openscenegraph/OpenSceneGraph/blob/0e87a86404692eb079ecb0f052efd4523ff0ff59/src/osgDB/FileNameUtils.cpp#L333).

We were able to fix the issue by introducing this check before [line 345 in osgDB/FileUtils.cpp](https://github.com/openscenegraph/OpenSceneGraph/blob/0e87a86404692eb079ecb0f052efd4523ff0ff59/src/osgDB/FileUtils.cpp#L345)
```C++
if(path.length()>MAX_PATH) // <-- our extra check
    continue;

path = getRealPath(path); // <-- original code at line 345
```

We were able to sometimes reproduce the issue by passing a filename like `D:\A1\_work\25\s\aaaaaaaaaa\bbb\ccccc\ddddddddd\eeeeeeee\ffffffff gggggggg\hhhhhh iii jjjjjjjj kkkk llllll mmmm\nnnnnnnn\ooooooo_01.tga.attr` into the `std::string Registry::findDataFileImplementation` function in [Registry.cpp line 1026](https://github.com/openscenegraph/OpenSceneGraph/blob/0e87a86404692eb079ecb0f052efd4523ff0ff59/src/osgDB/Registry.cpp#L1026). This sometimes returns an empty string but it may also return a string with a value.

**Comment by openscenegraph** [comment]
I agree with your analysis, it looks to like a WIndows specific issue related to the limit on path lengths.

There isn't any point checking whether an impossible path exists so your suggested addition to FileUtils.cpp looks sensible.  The only thing different I would suggest is that it's a Windows specific issue and fix so should be enclosed in a platform specific #ifdef block.

Could you get this working on your system and then generate a PR for it.  I don't have Windows systems here so can't test personally.

**Comment by openscenegraph** [comment]
I have added the suggested check against MAX_PATH for Windows and checked this into the 3.6 branch:

    https://github.com/openscenegraph/OpenSceneGraph/commit/bf5a88870f55731d341d56d8d05a66c1fbe0d1a1

I'll also check this fix into master.
