### ISSUE TITLE
writer stl : add numeric precision to vertex coordinates

### ISSUE THREAD

**Issue by alavenant** [openscenegraph/OpenSceneGraph#636]
add the bold line at line 362 of ReadeWriterSTL.cpp :

                *m_stream << "outer loop" << std::endl;
		***m_stream << std::fixed << std::setprecision(7);** // add numeric precision
                *m_stream << "vertex " << v1[0] << " " << v1[1] << " " << v1[2] << std::endl;
                *m_stream << "vertex " << v2[0] << " " << v2[1] << " " << v2[2] << std::endl;

**Comment by robertosfield** [comment]
If you want to submit a change then then please use a PR, as code snippets are not at all reliable.  I'm closing this Issue as it's the correct path forward is the PR.

**Comment by openscenegraph** [comment]
Thanks PR merged : https://github.com/openscenegraph/OpenSceneGraph/commit/0e87a86404692eb079ecb0f052efd4523ff0ff59
