### ISSUE TITLE
build fails on macOS Mojave (clang-10.0 & cmake 3.10.3)

### ISSUE THREAD

**Issue by podborski** [openscenegraph/OpenSceneGraph#637]
`cmake .`  using _clang-10.0_ fails with:

> ...
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
> CMake Error at /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
>   The C++ compiler
> 
>     "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"
> 
>   is not able to compile a simple test program
> ...
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
>     ld: library not found for -lstdc++
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     gmake[1]: *** [CMakeFiles/cmTC_cc871.dir/build.make:98: cmTC_cc871] Error 1
>     gmake[1]: Leaving directory '/Users/xxxxxx/projects/OpenSceneGraph/CMakeFiles/CMakeTmp'
>     gmake: *** [Makefile:126: cmTC_cc871/fast] Error 2

**compiler version output:**
> $  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
> Apple LLVM version 10.0.0 (clang-1000.11.45.2)
> Target: x86_64-apple-darwin18.0.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by robertosfield** [comment]
Which version of the OSG are you using?

W.r.t -lstdc++, check where this is being specified in the OSG build, I just did a quick search and can't see any direct reference in the OSG's CMake scripts so this may well be a CMake setting that is pulled in.  If so then it's likely CMake not being up to date with changes to Clang and isn't an OSG issue.

**Comment by podborski** [comment]
@robertosfield thanks for quick reply. I was trying to compile 3.6.3 (but the same problem occurs on master branch too). 
This issue might be related to old "libstdc++" library which is now unsupported in Xcode 10:
https://forums.developer.apple.com/thread/106114

from CMakeLists.txt I see the following (which looks good):
> IF (APPLE)
>             SET(OSG_CXX_LANGUAGE_STANDARD "C++11" CACHE STRING "set the c++ language standard (C++98 / GNU++98 / C++11) for OSG" )
>             MARK_AS_ADVANCED(OSG_CXX_LANGUAGE_STANDARD)
>             # remove existing flags
>             REMOVE_CXX_FLAG(-std=c++98)
>             REMOVE_CXX_FLAG(-std=gnu++98)
>             REMOVE_CXX_FLAG(-std=c++11)
>             REMOVE_CXX_FLAG(-stdlib=libstdc++)
>             REMOVE_CXX_FLAG(-stdlib=libc++)
> 
>             IF(${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "c++98" OR ${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "C++98")
>                 set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++98")
>                 set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libstdc++")
>                 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98 -stdlib=libstdc++")
>             ELSE()
>                 IF(${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "gnu++98" OR ${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "GNU++98")
>                     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "gnu++98")
>                     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libstdc++")
>                     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++98 -stdlib=libstdc++")
>                 ELSE()
>                     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
>                     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
>                     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")
>                 ENDIF()
>             ENDIF()
> 
>             set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-overloaded-virtual -Wno-conversion")
>             set(WARNING_CFLAGS "")
>         ENDIF()

**Comment by podborski** [comment]
ah, seems to be an issue with CMakeLists.txt
if I put `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")` in the beginning of the file I can successfully configure the project.

**Comment by openscenegraph** [comment]
Are the default value for CMAKE_CXX_FLAGS provided by CMake the problem?

It may be possible to do something like:

   cmake -DCMAKE_CXXX_FLAGS="-std=c++11 -stdlib=libc++" .

**Comment by podborski** [comment]
> Are the default value for CMAKE_CXX_FLAGS provided by CMake the problem?
> 
> It may be possible to do something like:
> 
> cmake -DCMAKE_CXXX_FLAGS="-std=c++11 -stdlib=libc++" .

Small typo in your command (tripple X) ` cmake -DCMAKE_CXXX_FLAGS="-std=c++11 -stdlib=libc++" .`

Thank you. It successfully configures with this command. I will now try to compile again and see if the same problem with the linking appears.

**Comment by openscenegraph** [comment]
Looking at OpenSceneGraph/CMakeLists.txt it looks like it should be able to handle the above CMAKE_CXX_FLAGS setting already:

       IF (APPLE)
            SET(OSG_CXX_LANGUAGE_STANDARD "C++11" CACHE STRING "set the c++ language standard (C++98 / GNU++98 / C++11) for OSG" )
            MARK_AS_ADVANCED(OSG_CXX_LANGUAGE_STANDARD)
            # remove existing flags
            REMOVE_CXX_FLAG(-std=c++98)
            REMOVE_CXX_FLAG(-std=gnu++98)
            REMOVE_CXX_FLAG(-std=c++11)
            REMOVE_CXX_FLAG(-stdlib=libstdc++)
            REMOVE_CXX_FLAG(-stdlib=libc++)

            IF(${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "c++98" OR ${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "C++98")
                set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++98")
                set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libstdc++")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98 -stdlib=libstdc++")
            ELSE()
                IF(${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "gnu++98" OR ${OSG_CXX_LANGUAGE_STANDARD} STREQUAL "GNU++98")
                    set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "gnu++98")
                    set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libstdc++")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++98 -stdlib=libstdc++")
                ELSE()
                    set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
                    set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")
                ENDIF()
            ENDIF()

 My reading of the script it looks like by default it should select the final path, so I guess something myst be different on your system that it's not selecting this path.  I would be worth adding MESSSAGE(",,,") usage into this block to see what paths are being taken and what the settings are.

Robert.

**Comment by podborski** [comment]
@openscenegraph Hi Robert,

yes I also saw this and this was the first idea which came into my mind. However without setting this flag on command line the last possible message output is right before the line `PROJECT(OpenSceneGraph)`

however with the command line `cmake -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++" .` it successfully configures and I can see messages from the last else block (in your previous message).

unfortunately the compilation fails now here:

> 
> [ 86%] Building C object src/osgPlugins/lua/CMakeFiles/osgdb_lua.dir/lua-5.2.3/src/linit.c.o
> [ 86%] Linking CXX shared module ../../../lib/osgPlugins-3.6.3/osgdb_lua.so
> [ 86%] Built target osgdb_lua
> Scanning dependencies of target osgdb_sdl
> [ 86%] Building CXX object src/osgPlugins/sdl/CMakeFiles/osgdb_sdl.dir/JoystickDevice.cpp.o
> [ 86%] Building CXX object src/osgPlugins/sdl/CMakeFiles/osgdb_sdl.dir/ReaderWriterSDL.cpp.o
> [ 86%] Linking CXX shared module ../../../lib/osgPlugins-3.6.3/osgdb_sdl.so
> Undefined symbols for architecture x86_64:
>   "_SDL_JoystickNameForIndex", referenced from:
>       JoystickDevice::JoystickDevice() in JoystickDevice.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/osgPlugins-3.6.3/osgdb_sdl.so] Error 1
> make[1]: *** [src/osgPlugins/sdl/CMakeFiles/osgdb_sdl.dir/all] Error 2
> make: *** [all] Error 2

**Comment by podborski** [comment]
This compilation error seems to be related to the previous issue (which is closed now):
https://github.com/openscenegraph/OpenSceneGraph/issues/126

**Comment by podborski** [comment]
Update: without SDL it compiles. I'm not sure why this problem occurs I tried to update SDL Framework etc. didn't work. So I completely uninstalled it since I don't need it anyway.

**Comment by openscenegraph** [comment]
With CMake you can disable plugins by setting the relevant vars, such as SDL_INCLUDE_DIR to empty i.e.

   cmake . -DSDL_INCLUDE_DIR=

As to why SDL doesn't compile, Apple keep moving the goal posts so often that stuff breaks with various dependencies.  If you want to use Apple as a platform you just need to get used to this and become proficient at jumping each time Apple tell you to jump.

On the OSG side the only oddity I don't understand is why you have to explictly set the CMAKE_CXX_FLAGS when the CMakeList.txt script already has support for this setting already.

**Comment by podborski** [comment]
It looks like before this option is set cmake tries to compile some simple test program (without this option) and it fails do check for working CXX compiler. I'm not sure, but this might be related to multiple compilers installed on my system. (gcc, g++, clang, clang++)

**Comment by openscenegraph** [comment]
I have clang and gcc (and C++ equivalents) installed on my Linux box and by default CMake selects gcc, but I can use the CMAKE_CXX_COMPILER env var to for it to select clang.  Perhaps this might help with your system.

I'm going to close this issue now is it looks like you have a resolution.
