### ISSUE TITLE
FindFBX.cmake is broken on OS X

### ISSUE THREAD

**Issue by robertcastleDAQRI** [openscenegraph/OpenSceneGraph#64]
FindFBX does not find the FBX sdk on Mac.

Install path is: /Applications/Autodesk/FBX SDK/2014.1/
Search path in FindFBX is /Applications/Autodesk/FBXSDK20141

But changing it still does not fix it. Not sure where the issue is.

Additionally the ReaderWriterFBX.h states that the plugin "requires the FBX SDK version 2013.3 or 2014.1", but FindFBX is trying to find 2015.1 first then 2014.2, and finally 2014.1 with a comment that searching for 2014.1 is probably a typo?

**Comment by openscenegraph** [comment]
I have added a couple of extra paths to the FindFBX.cmake, updated the .cpp file and checked this into OpenSceneGraph master and 3.4 branch.

Could you please test this.  Ideally report problems on the osg-users mailing list/forum as this is the official route for support.
