### ISSUE TITLE
Master fails to build on VS2017 with C++17 enabled

### ISSUE THREAD

**Issue by sbrkopac** [openscenegraph/OpenSceneGraph#653]
There are currently two functions in the OSG core modules that are preventing proper compilation against the C++17 standard. The following had been deprecated and are now removed in C++17:

`std::unary_function`
`std::binary_function`

There is also a conflict with the definition of the new `std::byte` type and the quick fix is to remove the `using namespace std;` in DatabasePager.

The quick and easy fixes are contained in this [commit](https://github.com/sbrkopac/OpenSceneGraph/commit/59e2ad7abe83064f8ef47361fea534062f1269bb). While polluting the std namespace is an extremely bad practice, this will get OSG to compile. 

It may be possible that this should not be pushed into master and documented somewhere else.

**Comment by robertosfield** [comment]
I really don't like the proposed change.  Could you post the actual warnings/errors and I'll have a look at them.

**Comment by sbrkopac** [comment]
Agreed, Robert. The changes are less than ideal. I've attached the output for the build from [Visual Studio](https://github.com/openscenegraph/OpenSceneGraph/files/2531337/osg.build.errors.txt).

**Comment by openscenegraph** [comment]
I have looked into the std::unary_function and std::binary_function usage and neither are actually required.  So I've just removed them completely, everything still compiles for me :-)

https://github.com/openscenegraph/OpenSceneGraph/commit/7729d38b2b426eee106e63bb1824b31301aa3400

I have checked this fix into master and the OpenSceneGraph-3.6 branch.
