### ISSUE TITLE
osg::ImageStream::setTimeMultiplier behavior

### ISSUE THREAD

**Issue by flashk** [openscenegraph/OpenSceneGraph#657]
I'm working on a fix for gif animation playback speed and noticed an odd behavior with osg::ImageStream::setTimeMultiplier. The multiplier seems to invert the playback speed, so setting it to 2 plays the animation at half the speed. This is the opposite behavior compared to osg::AnimationPathCallback.

Just curious if this is the intended behavior? If not then I can fix that along with the other changes I'm working on.

**Comment by robertosfield** [comment]
It;s a time multiplier rather than a speed multiplier, if you invert this interpretation 3rd party code would fail. If you wanted a speed multiplier interpretation then you could add inline method that does the inverse.
