### ISSUE TITLE
CMake installation could use some modernization

### ISSUE THREAD

**Issue by mxgrey** [openscenegraph/OpenSceneGraph#658]
First of all, thanks for developing and maintaining this incredibly useful open source software. For years now, it's been my favorite scene graph rendering software to work with, bar none.

I have a suggestion that I hope won't come across as too frivolous, because it has a significant impact on my whole workflow as a software library developer: OSG's integration with cmake uses some outdated practices with known weaknesses, and it would be great to modernize the build system, if only a bit.

To add some context, I'm developing on Ubuntu 18.04 which conveniently provides [osg-3.2](https://packages.ubuntu.com/bionic/libopenscenegraph-dev) and [osg-3.4](https://packages.ubuntu.com/bionic/libopenscenegraph-3.4-dev) packages. However, there were some recent developments in OSG that I'd like to take advantage of, but they're not available until after `osg-3.4`.

I'm able to build the master branch of OSG with no problem, so it's easy to get the latest version :+1: , but actually *using* the latest version in a downstream dependent cmake project poses some issues. Ideally I should be able to use `find_package(OpenSceneGraph <version>)` and cmake should automagically find me a version of OSG that matches my version requirement. However, the default way that cmake will do this is to run [this find-module](https://gitlab.kitware.com/cmake/cmake/blob/5e12fad8704e4797ecda3906f3b558775b70539f/Modules/FindOpenSceneGraph.cmake) which will ultimately lead to [this find_library(~)](https://gitlab.kitware.com/cmake/cmake/blob/5e12fad8704e4797ecda3906f3b558775b70539f/Modules/Findosg_functions.cmake#L45) call.

The problem here is that the newest version of OSG will install to `lib64`, but these system-installed find-modules will only look at [lib directories](https://gitlab.kitware.com/cmake/cmake/blob/5e12fad8704e4797ecda3906f3b558775b70539f/Modules/Findosg_functions.cmake#L54), without the `64` suffix. I've noticed that the OSG codebase [provides a find-module](https://github.com/openscenegraph/OpenSceneGraph/blob/85504b45f6229c2695bc109d771045fcb10fc1e0/CMakeModules/FindOSG.cmake#L32) which can handle the `lib64` case, but the only way for a downstream project to use that find-module is to copy/paste it into their own codebase and set up their `CMAKE_MODULE_PATH` to look at this custom find-module instead of using the system-installed one.

While that may be a sufficient solution in some cases, it has some significant shortcomings.

1. For one thing, if my project's dependency on OSG is coming from an upstream third-party library, then I would need to either convince that third party to change their build system to use the custom find-module, or else I need to fork that upstream dependency to modify it, and then risk diverging from it.

2. For another thing, it makes build systems less maintainable, because I'll need to always make sure the find-module that I'm using for OSG is up to date if I want to avoid confusing build issues (in my own case which prompted this post, the build system failure presented itself as an issue with trying to link to undefined symbols).

### The workaround I used

I found that I could work around these cmake issues using [pkg_check_modules(~)](https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html), since OSG does a good job of installing useful `pkg-config` files. But there are two catches with this:

1. If an upstream dependency is depending on OSG, then you still have to modify the build system of that upstream dependency (but at least it's a relatively minor change and doesn't require ongoing upkeep).

2. I needed to use the `PKG_CONFIG_PATH` environment variable in order to point `pkg-config` at the right directory.

This is good enough for me to eke by with what I need to do for now, but it's far from ideal.

### The preferable solution

Ideally, OpenSceneGraph should be able to install cmake config-files instead of relying on find-modules. OSG already uses a cmake build system, so installing a config-file and even exporting targets should be a straightforward addition.

I'd be happy to make these changes and open a pull request, but I wanted to post this first to check with the maintainers to see if it would be a welcome change, since it could be somewhat time consuming for me to do. It wouldn't impact any of the existing functionality of the build system, it would just additionally install some [config-files](https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#config-file-packages) and maybe exported target files.

**Comment by robertosfield** [comment]
By co-incidence I've been experimenting with cmake config generation for the VSG project so understand what you mean.  I hadn't considered backporting this to the OSG as my focus on the OSG side is on maintenance rather than new features.

If adding the cmake config support isn't too intrusive then I'd happy to merge a PR with this support.  The OSG does rather complicate things because it has just so many different libs and plugins so my assumption would be this support is not as straight forward as it was for the VSG project.

The other approach would be to use the OSG_DIR env var setting to point the Find scripts at the OSG version they should use.

**Comment by mxgrey** [comment]
> The other approach would be to use the OSG_DIR env var setting to point the Find scripts at the OSG version they should use.

Right, this was the first approach that I tried, but the system-installed cmake find-module that's provided by default with cmake isn't made to handle the case that the libraries are installed in `lib64` instead of `lib` when built for 64-bit architecture (which happens in the most recent version of OSG). The new version of `FindOSG.cmake` in the OSG codebase looks like it can handle `lib64`, but that doesn't do much good unless I drop that module into my own dependent projects and make sure that I keep them all up to date.

The result of using `OSG_DIR` was that the find-module found the correct headers but the wrong library (it fell back on the system-installed version, 3.4, instead of my custom installation of the latest master branch), causing a linking error when some new symbol definitions were missing from the old library.

> OSG does rather complicate things because it has just so many different libs and plugins so my assumption would be this support is not as straight forward

I have a healthy amount of experience setting up config files for projects with lots of component libraries and plugin libraries, so I recognize that it's not especially straightforward, but it won't be too much trouble for me.

One question I have is: What's the highest version of cmake that would be acceptable for the latest OSG to use? Newer versions of cmake have some really nice features, especially where exporting targets is concerned. I'd like to leverage as many of those features as possible, but I'm happy to respect the limitations of whatever platforms OSG is meant to target.

For reference:

* Windows platforms have effectively no limit for cmake support because Windows users can trivially update their cmake version at any time.

* Homebrew provides 3.12.4, and I believe this is generally kept up to date with the latest version

* Debian Stretch provides cmake 3.7.2

* Ubuntu 16.04 provides 3.5.1

* Ubuntu 18.04 provides 3.10.2

Are there any target platforms for the master branch of OSG that are more restrictive than Ubuntu 16.04?

**Comment by robertosfield** [comment]
The OSG is still used by users on some old RedHat systems, they go quiet for a long while but occasionally pop up complaining about raise a red flag when we use features that aren't available on these old systems, to matters worse they have issues with installing custom versions of tools like cmake. I couldn't guess at how far we back we could safely go back to determine what is safe to use. 

Any requirement on a newer version of CMake I view as risk of breaking the build.  When it comes to make things work more seamlessly as you are wanting vs not building at all I'll always choose the later.

Is it possible to check the Cmake version within the script and only use that feature when you need it?

The other alternative is to just use ccmake to customize where you install your libs, or customize the OSG_* settings in ccmake to point to the correct place.

**Comment by sbrkopac** [comment]
It's great to see this discussion taking place, and it's awesome to see that we will be getting modern CMake coming with VSG. With respect to Robert's comment.

> Any requirement on a newer version of CMake I view as risk of breaking the build.

There is a considerable amount of (now) workarounds that exist in the current implementation of OSG's CMake, and bumping the versions may cause conflicts or flat our break the build system. I agree it would be great to at least get to CMake 3.0 but that may not be feasible.

>The result of using OSG_DIR was that the find-module found the correct headers but the wrong library (it fell back on the system-installed version, 3.4, instead of my custom installation of the latest master branch), causing a linking error when some new symbol definitions were missing from the old library.

Are we able to add a OSG_VERSION environmental variable and modify the provided FindOSG.cmake to incorporate that into the lookup?

>I have a healthy amount of experience setting up config files for projects with lots of component libraries and plugin libraries, so I recognize that it's not especially straightforward, but it won't be too much trouble for me.

I personally would be interested in seeing what this would look like. It may not be able to go back into master but perhaps maintaining a modern-cmake type branch may be an option.

**Comment by robertosfield** [comment]
On Wed, 14 Nov 2018 at 03:28, Michael X. Grey <notifications@github.com>
wrote:

> I think the "right" fix (besides having OSG install config-files) is just
> to add lib64 as a hint to the find_library(~) call, like the FIndOSG.cmake
> <https://github.com/openscenegraph/OpenSceneGraph/blob/85504b45f6229c2695bc109d771045fcb10fc1e0/CMakeModules/FindOSG.cmake#L32>
> module in this codebase has. The problem is that this needs to be done
> either upstream in CMake itself or it needs to be done in each individual
> project that depends on OSG.


You should be able to use a local FindOSG.cmake in your own applications, I
don't recall it but I'm sure there is way of making CMake use your own one.

Robert.

**Comment by mxgrey** [comment]
A finished implementation can be found in #660

**Comment by openscenegraph** [comment]
Now merged :-)
