### ISSUE TITLE
ShaderPipeline disabled in OSG for MacOS

### ISSUE THREAD

**Issue by loening** [openscenegraph/OpenSceneGraph#661]
I have a question about OSG for MacOS. My system is OS X EI Capitan, whose version is 10.11.6. , and the Graphics card is NVIDIA Geforce GTX 680MX.

I have built the OpenSceneGraph 3.7.0 successfully, but I come across a problem of " void StateSet::setGlobalDefaults() ShaderPipeline disabled. " when I run the examples. I don't know what is the OSG bug, or the computer system problem.

I checked the osgViewer code, below bold usage have been deprecated. I don't know this is the reason.

`    attr[i++] = **NSOpenGLPFAPixelBuffer**; // for pbuffer usage
    attr[i++] = NSOpenGLPFAAccelerated;
    attr[i] = static_cast<NSOpenGLPixelFormatAttribute>(0);
    
    // create the context
    NSOpenGLContext* sharedContext = NULL;
    
    GraphicsHandleCocoa* graphicsHandleCocoa = dynamic_cast<GraphicsHandleCocoa*>(_traits->sharedContext.get());
    if (graphicsHandleCocoa) 
    {
        sharedContext = graphicsHandleCocoa->getNSOpenGLContext();
    }
    
    
    NSOpenGLPixelFormat* pixelformat = [[NSOpenGLPixelFormat alloc] initWithAttributes:attr ];
    _context = [[NSOpenGLContext alloc] initWithFormat: pixelformat shareContext: sharedContext];
    **NSOpenGLPixelBuffer*** pbuffer = [[NSOpenGLPixelBuffer alloc] **initWithTextureTarget: _traits->target textureInternalFormat: _traits->format textureMaxMipMapLevel: _traits->level pixelsWide: _traits->width pixelsHigh: _traits->height**];
    
    [_context **setPixelBuffer: pbuffer cubeMapFace: _traits->face mipMapLevel:_traits->level currentVirtualScreen: 0**];
    
    [pool release];

**Comment by vsg-dev** [comment]
The master contains experimental work, the message about ShaderPipeline being disabled is completely benign, it simply means the experimental ShaderPipline functionality isn't enabled.

I recommend using the OpenSceneGraph-3.6 or 3.6.3 stable release for normal development work.

**Comment by loening** [comment]
Thanks a lot.
