### ISSUE TITLE
Forcing windows application as DPI aware

### ISSUE THREAD

**Issue by freza-tm** [openscenegraph/OpenSceneGraph#662]
Change introduced in commit 9fac39c5e09cc6157fe77dca8810b329ad8e43f2 forces whole process to be marked as DPI aware, possibly breaking applications that uses toolkits that are not DPI aware. I noticed this bug when upgrading from OSG 3.4.0 to 3.6.3 and application stops functioning properly on HiDPI screen.

As OSG set application as DPI aware very early on it is not trivial to prevent it. I think this should be either handled by the application itself or at least optional.

**Comment by openscenegraph** [comment]
What toolkits are you using that are not DPI aware?

The best place to hash out the best way to handle this is to raise a discussion topic on osg-users mailing list/forum.

**Comment by openscenegraph** [comment]
I'm closing this issue as this isn't the place for general discussion about default behaviours.  Please bring this topic up on the osg-users ML/forum if you feel that we need to hash out a workaround for your particular usage case.
