### ISSUE TITLE
text depth test error

### ISSUE THREAD

**Issue by ooklasd** [openscenegraph/OpenSceneGraph#667]
the right result is the 
![default](https://user-images.githubusercontent.com/20807125/49074268-4c49d980-f26f-11e8-85bf-1bf3f565e4ad.png)

when is set
`
text->setBoundingBoxColor({ 0.9f,0.9f,0.9f ,0.5f });
text->setDrawMode(osgText::Text::TEXT | osgText::Text::FILLEDBOUNDINGBOX);
text->setBackdropColor(osg::Vec4(1.0, 0.0, 0.0, 1.0));		
`

here is error:
![default](https://user-images.githubusercontent.com/20807125/49074341-77ccc400-f26f-11e8-91e3-b3549a7faf2a.png)

**Comment by robertosfield** [comment]
The "right" result above is has the wrong backdrop colour, the bottom "error" has the correct backdrop colour.  

From the given information there isn't anyway for us to know what might actually be wrong, it could be a usage issue, it may even be an OSG bug, but until we have more information, or better a small test program that illustrates the problem there isn't anything we can do to help you resolve the issue.

In terms of information, it would be useful to know what OSG version you are using, what platform, what the wider OSG usage is.  The best mean for resolving it would be a small test program, such as a modified OSG example.

**Comment by ooklasd** [comment]
i am not change ang about the renderbin ,so the render order will not change,the text can not display behind the mesh in a green line.i don't know how to show the bug what I think

**Comment by openscenegraph** [comment]
I'm closing this Issue as I haven't seen any evidence that there is an OSG bug, it looks like an user error.  Exactly what this error might be is not possible to determine from the information provide.  The place to discuss OSG usage questions is the via the osg-users mailing list/forum, so if you want further assistance then please subscribe and ask the question of how you implement the effect you are looking for.
