### ISSUE TITLE
OSG 3.6.3 fails to create an Xcode 10.X project targeting iOS via CMake

### ISSUE THREAD

**Issue by ccochran** [openscenegraph/OpenSceneGraph#669]
However, /master **does** build the Xcode 10 project properly given the commit from @tomhog 49e9aadbf5cee27a0306b0d26d3a0d53bf3a454a.  Perhaps we can merge his work into a stable 3.6.4 release branch?  I'm not sure master branch is stable enough for a production build.

**Comment by wyfSunflower** [comment]
may be it not suitable for ios, why not use opengles

**Comment by ccochran** [comment]
> may be it not suitable for ios, why not use opengles

OSG has worked wonderfully on iOS for years, and it's based on OpenGL ES.

**Comment by openscenegraph** [comment]
I don't have a Apple system to test against, so could you apply Tom's changes to the 3.6 branch and see how you get on.  If that works then you could generate a PR for the changes.   I can then merge with the 3.6 so the fixes can then be rolled into the future 3.6.4 stable release.

**Comment by ccochran** [comment]
Yes, I'll give that a shot, thx

**Comment by openscenegraph** [comment]
Thanks, merged,
