### ISSUE TITLE
Obsolete Doxygen config files 

### ISSUE THREAD

**Issue by ip** [openscenegraph/OpenSceneGraph#67]
Hi. There are a lot of warnings when generating documentation. See `make` output: https://gist.github.com/ip/46eeb21ac88efb1ab6a0f8691f0eba9c

Also, it would be nice to update Doxygen docs at [site](http://trac.openscenegraph.org/documentation/OpenSceneGraphReferenceDocs/), they are dated July 25 2013 for version 3.2.0. Ideally, they could be generated automatically by continuous integration infrastructure, but I guess these are dreams :smile:

**Comment by ip** [comment]
By the way, I generated docs for version 3.5.2 if anyone needs: https://www.dropbox.com/s/vyapwzp1rd67xb9/osg-doc.zip?dl=0

**Comment by ip** [comment]
It generated by newer version of Doxygen and looks nicer :smile:

**Comment by jtorresfabra** [comment]
This issue can be closed, now the OSG site are up to date to the latest stable version ( OSG-3.4.0 ).

**Comment by ip** [comment]
Did he even read this?

**Comment by openscenegraph** [comment]
All doxgen warnings have now been resolved in OpenSceneGraph master.  Testing with doxygen 1.8.11.

Please note for future reference, the official support channel for the OSG is the osg-users mailing list/forum.  This is the place to report problems as it gets the widest exposure.

**Comment by ip** [comment]
@openscenegraph Ok, thanks.

**Comment by jtorresfabra** [comment]
Hey Robert ( @openscenegraph ), 
just FYI https://help.github.com/articles/disabling-issues/ 

Cheers .

**Comment by ip** [comment]
@openscenegraph And if you disable them, please mention it in the README.md
