### ISSUE TITLE
Why is Matrix_implementation.cpp skipped by build system

### ISSUE THREAD

**Issue by solvingj** [openscenegraph/OpenSceneGraph#678]
Was exploring unit tests, and found this test: 

https://github.com/openscenegraph/OpenSceneGraph/blob/master/examples/osgunittests/osgunittests.cpp#L38

Randomly decided to use the snippit of code for a simple Matrix example: 

```
        osg::Matrix f;

	double left = 5;
	double right = 5;
	double bottom = 5;
	double top = 5;
	double zNear = 5;
	double zFar = 5;
	
	f.makeFrustum(left,right,bottom,top,zNear,zFar);

```
Got this linker error: 

```
   3>test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl osg::Matrixd::~Matrixd(void)" (__imp_??1Matrixd@osg@@QEAA@XZ) r
       eferenced in function main [C:\Users\jerry\git-conan\conan-openscenegraph\test_package\build\70fa761522f83dc39e27737d854e65d5cd23b2cc\test_package.vcxproj]
     3>test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osg::Matrixd::makeIdentity(void)" (__imp_?makeIdentity@Mat
       rixd@osg@@QEAAXXZ) referenced in function main [C:\Users\jerry\git-conan\conan-openscenegraph\test_package\build\70fa761522f83dc39e27737d854e65d5cd23b2cc\test_pack
       age.vcxproj]
     3>test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl osg::Matrixd::getFrustum(double &,double &,double &,double
        &,double &,double &)const " (__imp_?getFrustum@Matrixd@osg@@QEBA_NAEAN00000@Z) referenced in function main [C:\Users\jerry\git-conan\conan-openscenegraph\test_pac
       kage\build\70fa761522f83dc39e27737d854e65d5cd23b2cc\test_package.vcxproj]
     3>C:\Users\jerry\git-conan\conan-openscenegraph\test_package\build\70fa761522f83dc39e27737d854e65d5cd23b2cc\bin\test_package.exe : fatal error LNK1120: 3 unresolved
       externals [C:\Users\jerry\git-conan\conan-openscenegraph\test_package\build\70fa761522f83dc39e27737d854e65d5cd23b2cc\test_package.vcxproj]
```

Found the implementation in this file: 

https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/Matrix_implementation.cpp

But then I found this section in the file, which literally says "We don't compile this file.", but stops short of providing an explanation of "why". 

https://github.com/openscenegraph/OpenSceneGraph/blob/74462c46b97970f03fd26977210a41bb7cb6ab61/src/osg/CMakeLists.txt#L332

I guess I'm just unlucky for having selected a test of an implementation that is commented out.  I guess it begs the question: how does this unit test even pass?

**Comment by mp3butcher** [comment]
this is not proper place for question 
this is not  an issue but a question that should be posed on the forum/ML.
I double someone will answer you

**Comment by solvingj** [comment]
Oh, i see, thank you. Apologies.
