### ISSUE TITLE
[VAO Path] Crash at Program end with MultiThreaded viewer

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#684]
to reproduce

 `OSG_VERTEX_BUFFER_HINT=VAO osgviewer cessna.osgt`

and quit the app 
Cause: VAO released after graphic context death

**Comment by openscenegraph** [comment]
What platform and OSG build combination do you see the crash for?

When I return to work tomorrow I'll have a look at the issue.

**Comment by mp3butcher** [comment]
I'm under Ubuntu 3.0 Mesa 18.0.5 Device: Mesa DRI Intel(R) Haswell Desktop 
but this bug is not platform related...

**Comment by openscenegraph** [comment]
I have just tested out cessna.osgt and cow.osgt and then don't crash on exit, but I get a crash on exit with spaceshit.osgt.

As for the "fixes" PR, this PR is unusable as a guide as there are way too many different changes stuffed into a single PR, there is no way I can figure out what is what.  I can be far more productive just figuring out the cause of the crash and making a fix.

**Comment by openscenegraph** [comment]
A quick update.  I've fixed the crash on exist with osgviewer spaceship.osgt.  I'll check this fix in once I've done more testing.

**Comment by mp3butcher** [comment]
I checkout out and the bug is not reproducible anymore ... One of recent change may have fix this issue

**Comment by openscenegraph** [comment]
In my testing I have uncovered several places where there are issues with clean up of VAO's on exit.  It's more niche features of the OSG, but still in the core OSG so important to address.  I am still working through the fixes will all be as one commit.
