### ISSUE TITLE
 Linux pre packaged dependencies not access

### ISSUE THREAD

**Issue by hughhugh** [openscenegraph/OpenSceneGraph#69]
Hi,
I am trying to install osg for Ubuntu , while the Linux pre packaged dependencies is not accessed from the link. http://www.openscenegraph.org/index.php/download-section/dependencies
Thank you.

**Comment by aluaces** [comment]
Hi, I guess nobody is interested in that anymore since you can also get those dependencies by following the Debian instructions:

    apt-get build-dep openscenegraph

**Comment by openscenegraph** [comment]
I have just removed the broken link, as Alberto says one simply can use apt-get build-dep openscenegraph as mentioned on the dependencies page.
