### ISSUE TITLE
[Fermi/NV390.87 only?] newly generated VAO having same GL name as a deleted one can lead to crash

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#697]
When a vao is deleted and a new one is regenerated, they may have the same name and so pass as the same for the active check in State::bindVertexArrayObject and crashes
**Driver policy dependant: with nv390.87 vao name deleted is reused right away on next glGenVertexArrays**
_On Ubuntu NVIDIA 390.87/GT440 [GT440 apitrace](https://drive.google.com/file/d/16sgWUPlRAYUKcGPZtJ0JZUyEq8IyDZA6/view?usp=sharing)
Crash doesn't happens with Mesa 18.0.5/Intel Chipset ([trace](https://drive.google.com/file/d/1kDaQ5pFnGc23wVBk1Vwi3PTz2aJLL1Vh/view?usp=sharing) : names doesnt seems to be reused right away)

To reproduce use the following code (if you need a sample dataset use my [test sample]( https://drive.google.com/file/d/0BxIH-jcsgYDdTG5ha21HZE1jX1E/view?usp=sharing) )
and run it with such a command line :
`OSG_VERTEX_BUFFER_HINT=VAO exename BIGCITY.ive --remove 2 --add 1 `

NB: with OSG_VERTEX_BUFFER_HINT=VBO it doesn't lead to crash

```
#include <osgUtil/MeshOptimizers>
#include <osgGA/TrackballManipulator>
#include <osgGA/FirstPersonManipulator>

#include <osgViewer/Viewer>
#include <osgViewer/ViewerEventHandlers>

#include <osgDB/ReadFile>

class GeomLoaderCB : public  osg::NodeCallback
{
    int _thresremoval; int _nbaddedatatime;
    std::list<osg::ref_ptr<osg::Geometry> > _geoms;
public:
    GeomLoaderCB(int thresremoval=1, int nbaddedatatime=1):_nbaddedatatime(nbaddedatatime), _thresremoval(thresremoval) {}

    void setGeometryList(const osgUtil::GeometryCollector::GeometryList& geomlist) {
        for(auto geom : geomlist)  _geoms.push_back(geom);
    }

    virtual void operator()(osg::Node* node, osg::NodeVisitor* nv) {
        osg::Group*  gr = node->asGroup();
        if(!gr || _geoms.empty() ) return;

        if(gr->getNumChildren()>_thresremoval)
        {
            osg::Geometry* geom = gr->getChild(0)->asGeometry();
            if(geom) {
                OSG_WARN<<"removing "<< geom.get()<<std::endl;
                gr->removeChildren(0,1);
            }
            return;
        }

        std::list<osg::ref_ptr<osg::Geometry> > ::iterator it= _geoms.begin();
        int cpt=0;
        while(it!=_geoms.end() && cpt++<_nbaddedatatime ) {
            osg::Geometry *newgeom=static_cast<osg::Geometry*>((*it)->clone(osg::CopyOp::DEEP_COPY_ALL));
            gr->addChild(newgeom);
            OSG_WARN<<"add "<< newgeom<<std::endl;
            it=_geoms.erase(it);
        }
        return;
    }

};


/// This examp reproduce a bug with OSG_VERTEX_BUFFER_HINT=VAO:
/// When a vao is deleted and a new one is regenerate, they may have the same name and so pass as the same for the active check in State::bindVertexArrayObject and crash
/// it collects geometries given in arg then add and remove them at runtime
int main(int argc, char **argv)
{
    osg::ArgumentParser args(&argc,argv);
    unsigned int  geomcountaddedatatime=1,geomcountabovewichweremove=2;
    while(args.read("--add",geomcountaddedatatime) ) { }
    while(args.read("--remove",geomcountabovewichweremove) ) { }
    osgUtil::GeometryCollector geomcollector(0,osgUtil::Optimizer::ALL_OPTIMIZATIONS);

    osg::ref_ptr<osg::Node > loaded=osgDB::readNodeFiles(args);
    if(loaded.valid())
    {
        loaded->accept(geomcollector);

        osg::Group * root=new osg::Group;
        GeomLoaderCB * loader=new GeomLoaderCB(geomcountabovewichweremove,geomcountaddedatatime);
        loader->setGeometryList( geomcollector.getGeometryList() );
        loaded=0;
        root->setUpdateCallback(loader);

        osgViewer::Viewer viewer;
        viewer.setThreadingModel(osgViewer::ViewerBase::SingleThreaded);
        viewer.addEventHandler(new osgViewer::StatsHandler);
        viewer.addEventHandler(new osgViewer::WindowSizeHandler);
        viewer.addEventHandler(new osgViewer::ThreadingHandler);

        viewer.setSceneData(root);

        viewer.realize();
        viewer.run();
    }

}
```

**Comment by openscenegraph** [comment]
Do you mean Pointer rather than Name? VAO's don't have names.

Are we simply talking about a dangling pointer ended up referring to a newly object?  That's my best guess given the misleading title.

Please in code never, even do a asGroup() and then not check the whether it's not null or not.  Doing so is really unsafe and shouldn't go anywhere any code even if in "certiain" circumstances it might work.  Treat as a dynamic_cast<>.  This is only one of a number of dubious things about the code.  I know you are trying to reproduce an issue but there is so much bad OSG usage in the example it makes it much harder to distil down to what the actual problem might be.

**Comment by mp3butcher** [comment]
no i speak about opengl name (GLuint)

**Comment by openscenegraph** [comment]
State::setCurrentVertexArrayObject(0) is not a "semantic reset name", it's a pointer reset to null.  

Conflating GL names into this issue is just confusing things when clarity is required. You are looking in the wrong place.

**Comment by mp3butcher** [comment]
I don't understand State::setCurrentVertexArrayObject(GLuint) dont reset any pointer!?

**Comment by openscenegraph** [comment]
Sorry, too many acronyms, the issue as far as I can see it is with the State::CurrentVertexArrayState pointer being a dangling pointer once the associated VAS is deleted, everything else is a symptom and confusing the matter.

**Comment by mp3butcher** [comment]
it doesn't crash with OSG_VERTEX_BUFFER_HINT=VBO so it's not related to VAS

**Comment by openscenegraph** [comment]
The fact it doesn't crash for you doesn't meant it's not an issue with VBO/Display lists as well. VAO usage is what looks to be a symptom, not the cause.

**Comment by mp3butcher** [comment]
@openscenegraph 
I merge your last commit but problem persists...:/
Did your achieve to reproduce the crash with provided code and data?
I crash with NVIDIA 390.87. What driver are you using?

**Comment by openscenegraph** [comment]
Changes all checked into OpenSceneGraph-3.6 and master.  Please test yourself as I have not been able to recreate the crash before or after the changes.  The changes look warranted so happy for them to be in.

**Comment by mp3butcher** [comment]
@openscenegraph
I merged your last commit but problem persists...:/
Did your achieve to reproduce the crash with provided code and data?
I crash with NVIDIA 390.87. (i'll confim tonight with mesa). What driver are you using?
Concerning BIGCITY.ive, i know it's not the best of all scenes, but as I collect geometries and deepcopy them, to rebuild a one level geometies group, it's more a source of lot of differnets geoemetries than anything else...

**Comment by mp3butcher** [comment]
@openscenegraph
I merged your last commit but problem persists...:/
Did your achieve to reproduce the crash with provided code and data?
I crash with NVIDIA 390.87. (i'll confim tonight with mesa). What driver are you using?
Concerning BIGCITY.ive, i know it's not the best of all scenes, but as I collect geometries and deepcopy them, to rebuild a one level geometries group, it's more a source of lot of differents geometries than anything else...

**Comment by mp3butcher** [comment]
Arg crash doesn't happens with Mesa 18.0.5/Intel Chipset!!!?

**Comment by openscenegraph** [comment]
My NVIidia driver version is "OpenGL version string: 4.6.0 NVIDIA 396.54.09" running in Kubuntu 18.04.

Please try a fresh track out of the OpenSceneGraph-3.6 it could be that you have you won changes that are affecting the result.

**Comment by openscenegraph** [comment]
I have spent several days chasing various VAO issues. I can't reproduce the error report by you with your data and example, Despite this I've written what should an appropriate fix that includes a rewrite of VAO id:
   https://github.com/openscenegraph/OpenSceneGraph/commit/aee747885a36c10f95f13aa124238ad27896783c

I have too much other work to get on with to go spending more time chasing this further.

**Comment by openscenegraph** [comment]
I have refactored the State::resetCurrentVertexArrayStateOnMatch(..) to separately check and reset the _currentVAO and the _vas.  This should catch cases where the _vas hasn't been applied as a VAO. 2e290856696a78e2149b0cc88cc87a7443431925

**Comment by mp3butcher** [comment]
the problem is that they never match: 
ex:
state->currentVAS= VAS1 with vao=1
when VAS1 released vao get 0 but driver always is one 1
when another VAS (VAS2) is generated vao=1 (nv390.87 policy) so state::bindVAO(VAS2) is called glBindVertexArray(1) is not called cause currentVAS.vao==VAS2.vao
and then it crashes

**Comment by mp3butcher** [comment]
`  inline void bindVertexArrayObject(GLuint vao) { if (_vas->getVertexArrayObject()!=vao) { _glExtensions->glBindVertexArray(vao); _currentVAO = vao; } }` ?

**Comment by mp3butcher** [comment]
Arf false joy in fact

**Comment by mp3butcher** [comment]
I pr a proposal
but perhaps adding state.resetCurrentVertexArrayStateOnMatch(vas) in  draw and compile might be better

**Comment by mp3butcher** [comment]
So I'll take an example to talk about the bug:
Say we have 1 geom with create VAS (VAS1) whose vao is 1. 
after drawing state.currentVAS=VAS1 and state.vao=1
we remove this geom and add another with VAS2:
VAS1 is released (VAS::deleteVAO is called so vao=0), but vao=1 is not unbound...
VAS2 is then generated, my driver is the only one to reuse vao=1 for VAS2
then state.bindVAO(VAS2) is called but do nothing as 1==1 and then it crashes

**Comment by openscenegraph** [comment]
What should be happening is that VAS::release() gets called on scene graph destruction, this places the VAS into the VertexArrayStateManager in it's _vertexArrayStateList that is a "to delete" list.  On the next frame the VertexArrayStateManager::flushDeletedGLObjects(.) will be called which calls the deleteVertexArrayObject() on all the pending _vertexArrayStateList that can be done in the alloted time, then those that have the deleteVertexArrayObject called will be deleted by the subsequent vertexArrayStateList.erase(..) call.  This should then trigger the destruction of the VAS's which will call the State::resetCurrentVertexArrayStateOnMatch() which should reset the State::_vas and _currentVAO if these match.  The following commit does the reset if matched

https://github.com/openscenegraph/OpenSceneGraph/commit/587c893f84851a9b1d6c6782cc24ba7ef9e779ad

Now what you describe is that for some reason the State values aren't be reset.  Outwardly the code looks fine, but there could be some odd bug lurking in there.  As you are the only person to reproduce this "bug" you are the only one that can check to see why what should be happening isn't happening in your instance.  At this point I can't do anything more.

**Comment by mp3butcher** [comment]
c6eb63d52916741026844abd98bf7bfde46eed1a fixes it
