### ISSUE TITLE
osgautocapture can not captrue in normal when viewer use CullThreadPerCameraDrawThreadPerContext Model

### ISSUE THREAD

**Issue by ooklasd** [openscenegraph/OpenSceneGraph#709]
version osg3.6.3

```
    camera.setFinalDrawCallback(cb);
    auto viewer = dynamic_cast<osgViewer::ViewerBase*>(camera.getView());
    auto oldModel = viewer->getThreadingModel();
    viewer->setThreadingModel(osgViewer::ViewerBase::SingleThreaded);
    viewer->renderingTraversals();
    viewer->setThreadingModel(oldModel);
    camera.setFinalDrawCallback(nullptr);
```

it will success everytime when switch to SingleThreaded

**Comment by openscenegraph** [comment]
You don't provide enough information to investigate this issue, and you include code without any proper explanation.  Is this code you've added to your own application?  To the OSG example?  Whereabouts? What affect does it have?

Could you please explain what steps one has to take to reproduce the problem.

Could you also provide a stack trace?

**Comment by ooklasd** [comment]
i use the codes in my application。it's work。i think it probably have some bug in osg::Image::readPixels when use multithread model.
when i use CullThreadPerCameraDrawThreadPerContext model and try to captrue a image like osgautocapture example ,the image is gray image in qt background color sometimes.

is any one can follow it,or only by myself?

**Comment by openscenegraph** [comment]
When running multi-threaded the next frame can overlap with the one that is still rendering.  If you try to read from an osg::Image that is still being actively written to then it'll cause a problem.  The easiest way to resolve this would probably be to just put a mutex around the Image access.

FYI, Image::readPixels() is not meant to be mutlti-threaded, it's up to the calling code/application to make sure you nothing unsafe is happening.

I'm closing this Issue as it all looks to be bug in your own camera callback and usage, not the OSG itself.  For support issues the avenue to use is the osg-users ML/forum.
