### ISSUE TITLE
osgDB::readNodeFile Error

### ISSUE THREAD

**Issue by zcwbnu** [openscenegraph/OpenSceneGraph#712]
I recently upgraded osg3.3.1 to osg3.6.2 and found that osg3.6.2  always report the error "std::bad_alloc" when reading model.  I use visual studio 2017. I don't know why and can you help me?
void cOSG::InitSceneGraph(void)
{
    // Init the main Root Node/Group
    mRoot  = new osg::Group;

    // Load the Model from the model name
    mModel = osgDB::readNodeFile("D:\\osgearth2.10\\data\\boxman.osg");
    if (!mModel) return;

    // Optimize the model
    osgUtil::Optimizer optimizer;
    optimizer.optimize(mModel.get());
    optimizer.reset();

    // Add the model to the scene
    mRoot->addChild(mModel.get());
}

**Comment by openscenegraph** [comment]
I have tracked down the boxman.osg to the osgearth/data set.  When I run osgviewer boxman.osg it renders and animates just fine with 3.6.4 under Linux, save for the warning:

    Error reading file images\BoxMan_Complete_256.png: file not found

I can't find any such file in osgearth repo so no idea where you'd find it, or whether this missing file may some baring on success of failure.

Please OSG-3.6 banch or one of the 3.6.4 release candidates to see if it works fine.  Failing that try 3.6.3.

If the error still occurs please post a stack trace for the error, also please try to recreate the problem with a standard OSG example/application or provide the full source code so others can attempt to recreate the problem with the same set up as you.

**Comment by zcwbnu** [comment]
@openscenegraph I found the reason ,I mixed debug library and release library. However osgDB::readNodeFile return NULL while I use debug library.

**Comment by zcwbnu** [comment]
I know why osgDB::readNodeFile alwanys return null, because I don't add osgplugin dlls. Thank you!

**Comment by openscenegraph** [comment]
Good to hear you got to the bottom of the issue.
