### ISSUE TITLE
for the member variant of _reuseRenderLeafList in the class Cullvisitor

### ISSUE THREAD

**Issue by zengjinchong** [openscenegraph/OpenSceneGraph#717]
for some reason, i load a lot of shapefiles and then delete them, and then load other shapefiles. I do it again and again.  I found osg is slow and the memory of my program is bigger than the origin.   i think it's because the size of the member variant of _reuseRenderLeafList in the class Cullvisitor is 20000+. the cull stage has been slowed down.  how can i solve the problem.

**Comment by mp3butcher** [comment]
please use ML/forum for these kind of question http://forum.openscenegraph.org/

**Comment by openscenegraph** [comment]
I'm closing this Issue as there is nothing we can do with do anything more to follow up and the original poster is unresponsive to requests for more information.
