### ISSUE TITLE
Undefined behaviour: Increment on empty set (ElevationSlice.cpp)

### ISSUE THREAD

**Issue by Himbeertoni** [openscenegraph/OpenSceneGraph#730]
In ElevationSlice.cpp, line 1097:
`void copyPoints(ElevationSlice::Vec3dList& intersections, ElevationSlice::DistanceHeightList& distanceHeightIntersections)
    {
        SegmentSet::iterator prevItr = _segments.begin();
        SegmentSet::iterator nextItr = prevItr;
++nextItr;`
If _segments is empty, the iterator increment causes undefined behavior, with GCC 3.6.0 it caused the application to freeze:
To fix this, I inserted
`if (_segments.empty()) return;` at the top of copyPoints()
Encountered when using the osgEarth TerrainProfileCalculator.

**Comment by openscenegraph** [comment]
Could you generate a PR for this fix.  Thanks.

**Comment by openscenegraph** [comment]
I have added a check to 3.6 branch and master:

   https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.6
