### ISSUE TITLE
CMake generate Xcode project failed

### ISSUE THREAD

**Issue by EdYao** [openscenegraph/OpenSceneGraph#739]
I'm using those cmd line to generate Xcode project, but `failed:`

`export THIRDPARTY_PATH=/Users/bigemap/Desktop/BigeMap/OSG/3rdParty
`
```
cmake ./ -G Xcode -DOSG_BUILD_PLATFORM_IPHONE:BOOL=ON \
    -DIPHONE_SDKVER="12.1" \
    -DIPHONE_VERSION_MIN="10.0" \
    -DOPENGL_PROFILE:STRING=GLES3 \
    -DBUILD_OSG_APPLICATIONS:BOOL=OFF \
    -DBUILD_OSG_EXAMPLES:BOOL=ON \
    -DOSG_WINDOWING_SYSTEM:STRING=IOS \
    -DOSG_CPP_EXCEPTIONS_AVAILABLE:BOOL=ON \
    -DOSG_DEFAULT_IMAGE_PLUGIN_FOR_OSX="imageio" \
    -DDYNAMIC_OPENSCENEGRAPH:BOOL=OFF \
    -DDYNAMIC_OPENTHREADS:BOOL=OFF \
    -DCURL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/curl-ios-device/include" \
    -DCURL_LIBRARY:PATH="$THIRDPARTY_PATH/curl-ios-device/lib/libcurl.a" \
    -DFREETYPE_INCLUDE_DIR_freetype2:PATH="$THIRDPARTY_PATH/freetype-ios-universal/include/freetype" \
    -DFREETYPE_INCLUDE_DIR_ft2build:PATH="$THIRDPARTY_PATH/freetype-ios-universal/include" \
    -DFREETYPE_LIBRARY:PATH="$THIRDPARTY_PATH/freetype-ios-universal/lib/libFreeType_iphone_universal.a" \
    -DTIFF_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/tiff-ios-device/include" \
    -DTIFF_LIBRARY:PATH="$THIRDPARTY_PATH/tiff-ios-device/lib/libtiff.a" \
    -DGDAL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/gdal-ios-device/include" \
    -DGDAL_LIBRARY:PATH="$THIRDPARTY_PATH/gdal-ios-device/lib/libgdal.a"

```

And the log in the terminal was:

    ```
=== BUILD TARGET cmTC_18d6b OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    No architectures to compile for (ARCHS=armv7 armv7s arm64, VALID_ARCHS=i386 x86_64).
    ** BUILD FAILED **
    The following build commands failed:
    	Check dependencies
    (1 failure)
```

The OSG version: 3.6.1 stable release.
MacOS Version: 10.14.4 (18E2034)
Xcode version: 10.2 (10E125)
CMake version: 3.14.1

**Comment by openscenegraph** [comment]
Could you please post general support questions to the osg-users mailing list/forum as this is the appropriate forum for these type of questions.  The Issue tracker for the OSG is only seen by a small proportion of the community so much less chance of other developers with a similiar setup to you being able to spot the right approach to resolving them.

**Comment by EdYao** [comment]
Thanks for you 

> Could you please post general support questions to the osg-users mailing list/forum as this is the appropriate forum for these type of questions. The Issue tracker for the OSG is only seen by a small proportion of the community so much less chance of other developers with a similiar setup to you being able to spot the right approach to resolving them.

Thanks for your reply:) This issue has been solved by editing  CMakeLists.txt. I changed the CMAKE_OSX_ARCHITECTURES from "armv6;armv7" to "$(ARCHS_STANDARD)", which as same as the latest version.
