### ISSUE TITLE
libgnustl_static.a(functexcept.o): previous definition here

### ISSUE THREAD

**Issue by beasonshu** [openscenegraph/OpenSceneGraph#740]
s/shuxinghu/Downloads/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/thumb/libgnustl_static.a(functexcept.o): previous definition here
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_ive'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg2'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_terrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_rgb'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_OpenFlight'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_dds'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgFX'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgParticle'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgTerrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgText'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgViewer'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgVolume'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgAnimation'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgFX'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgManipulator'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgParticle'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgTerrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgText'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgVolume'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_ive'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg2'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_terrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_rgb'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_OpenFlight'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'osgdb_dds'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgFX'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgParticle'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgTerrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgText'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgViewer'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgVolume'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osg'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgAnimation'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgFX'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgManipulator'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgParticle'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgTerrain'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgText'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/app/src/main/jni/OpenSceneGraph/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgVolume'
collect2: error: ld returned 1 exit status
make: *** [/Users/shuxinghu/Documents/work/osgAndroidExampleGLES2/a

**Comment by mp3butcher** [comment]
copy/pasting built error is NOT a proper way to report an issue:
1/ first investigate to know if error doesn't come from yourself
2/ give us more details (osg version host/target plateform) and precise the spotted error
