### ISSUE TITLE
android build error OpenSceneGraph Library 3.7.0

### ISSUE THREAD

**Issue by beasonshu** [openscenegraph/OpenSceneGraph#742]
: cannot find -lOpenThreads
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_ive'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg2'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_terrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_rgb'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_OpenFlight'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_dds'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgFX'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgParticle'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgTerrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgText'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgViewer'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgVolume'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgAnimation'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgFX'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgManipulator'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgParticle'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgTerrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgText'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgVolume'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osg/Notify:104: error: undefined reference to 'osg::Referenced::~Referenced()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osg/Referenced:201: error: undefined reference to 'osg::Referenced::signalObserversAndDelete(bool, bool) const'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:215: error: undefined reference to 'osg::Timer::instance()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:215: error: undefined reference to 'osg::Timer::instance()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:215: error: undefined reference to 'osg::Timer::tick() const'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:139: error: undefined reference to 'osgGA::EventQueue::mouseButtonPress(float, float, unsigned int, double)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:157: error: undefined reference to 'osgGA::EventQueue::mouseButtonRelease(float, float, unsigned int, double)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:131: error: undefined reference to 'osgGA::EventQueue::mouseMotion(float, float, double)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:165: error: undefined reference to 'osgGA::EventQueue::keyPress(int, double, int)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/EventQueue:172: error: undefined reference to 'osgGA::EventQueue::keyRelease(int, double, int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:211: error: undefined reference to 'osg::notify(osg::NotifySeverity)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:215: error: undefined reference to 'osg::notify(osg::NotifySeverity)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:73: error: undefined reference to 'osg::notify(osg::NotifySeverity)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:78: error: undefined reference to 'osg::notify(osg::NotifySeverity)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/ReadFile:121: error: undefined reference to 'osgDB::Registry::instance(bool)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/ReadFile:121: error: undefined reference to 'osgDB::readRefNodeFile(std::string const&, osgDB::Options const*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:35: error: undefined reference to 'osg::Shader::Shader(osg::Shader::Type, std::string const&)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:36: error: undefined reference to 'osg::Shader::Shader(osg::Shader::Type, std::string const&)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:38: error: undefined reference to 'osg::Program::Program()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:39: error: undefined reference to 'osg::Program::addShader(osg::Shader*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:40: error: undefined reference to 'osg::Program::addShader(osg::Shader*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:42: error: undefined reference to 'osg::Node::getOrCreateStateSet()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:42: error: undefined reference to 'osg::StateSet::setAttribute(osg::StateAttribute*, unsigned int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:52: error: undefined reference to 'osg::State::setUseModelViewAndProjectionUniforms(bool)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:53: error: undefined reference to 'osg::State::setUseVertexAttributeAliasing(bool)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:59: error: undefined reference to 'osgViewer::View::home()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:61: error: undefined reference to 'osgViewer::View::getDatabasePager()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:62: error: undefined reference to 'osgViewer::View::getDatabasePager()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:63: error: undefined reference to 'osgViewer::View::getDatabasePager()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:63: error: undefined reference to 'osgDB::DatabasePager::setUpThreads(unsigned int, unsigned int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:64: error: undefined reference to 'osgViewer::View::getDatabasePager()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osg/Notify:104: error: undefined reference to 'osg::Referenced::Referenced()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:101: error: undefined reference to 'osg::setNotifyHandler(osg::NotifyHandler*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:105: error: undefined reference to 'osgViewer::Viewer::Viewer()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:109: error: undefined reference to 'osg::Group::Group()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:113: error: undefined reference to 'osgViewer::StatsHandler::StatsHandler()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:113: error: undefined reference to 'osgViewer::View::addEventHandler(osgGA::EventHandler*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:114: error: undefined reference to 'osg::Node::getOrCreateStateSet()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:114: error: undefined reference to 'osgGA::StateSetManipulator::StateSetManipulator(osg::StateSet*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:114: error: undefined reference to 'osgViewer::View::addEventHandler(osgGA::EventHandler*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:115: error: undefined reference to 'osgViewer::ThreadingHandler::ThreadingHandler()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:115: error: undefined reference to 'osgViewer::View::addEventHandler(osgGA::EventHandler*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:116: error: undefined reference to 'osgViewer::LODScaleHandler::LODScaleHandler()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:116: error: undefined reference to 'osgViewer::View::addEventHandler(osgGA::EventHandler*)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osg/Object:69: error: undefined reference to 'osg::Referenced::Referenced()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/KeySwitchMatrixManipulator:31: error: undefined reference to 'osgGA::CameraManipulator::CameraManipulator()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/KeySwitchMatrixManipulator:31: error: undefined reference to 'osg::Object::~Object()'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/KeySwitchMatrixManipulator:31: error: undefined reference to 'vtable for osg::Object'
/Users/shuxinghu/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/KeySwitchMatrixManipulator:31: error: undefined reference to 'VTT for osgGA::KeySwitchMatrixManipulator'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgGA/KeySwitchMatrixManipulator:31: error: undefined reference to 'vtable for osgGA::KeySwitchMatrixManipulator'
/Users/shuxinghu/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:120: error: undefined reference to 'osgGA::TrackballManipulator::TrackballManipulator(int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:120: error: undefined reference to 'osgGA::KeySwitchMatrixManipulator::addMatrixManipulator(int, std::string, osgGA::CameraManipulator*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:121: error: undefined reference to 'osgGA::FlightManipulator::FlightManipulator(int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:121: error: undefined reference to 'osgGA::KeySwitchMatrixManipulator::addMatrixManipulator(int, std::string, osgGA::CameraManipulator*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:122: error: undefined reference to 'osgGA::DriveManipulator::DriveManipulator()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:122: error: undefined reference to 'osgGA::KeySwitchMatrixManipulator::addMatrixManipulator(int, std::string, osgGA::CameraManipulator*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:123: error: undefined reference to 'osgGA::TerrainManipulator::TerrainManipulator(int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:123: error: undefined reference to 'osgGA::KeySwitchMatrixManipulator::addMatrixManipulator(int, std::string, osgGA::CameraManipulator*)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:124: error: undefined reference to 'osgGA::OrbitManipulator::OrbitManipulator(int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:125: error: undefined reference to 'osgGA::FirstPersonManipulator::FirstPersonManipulator(int)'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:126: error: undefined reference to 'osgGA::SphericalManipulator::SphericalManipulator()'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/jni/OsgMainApp.cpp:128: error: undefined reference to 'osgViewer::View::setCameraManipulator(osgGA::CameraManipulator*, bool)'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_ive'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_osg2'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_terrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_rgb'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_OpenFlight'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'osgdb_dds'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgFX'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgParticle'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgTerrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgText'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgViewer'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'dotosgwrapper_library_osgVolume'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osg'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgAnimation'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgFX'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgManipulator'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgParticle'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgTerrain'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgText'
/Users/shuxinghu/Desktop/OpenSceneGraph-master/build_android/armeabi-v7a/include/osgDB/Registry:716: error: undefined reference to 'wrapper_serializer_library_osgVolume'
/Users/shuxinghu/Documents/work/osgAndroidExampleGLES3/app/src/main/obj/local/armeabi/objs/osgNativeLib/OsgMainApp.o:OsgMainApp.cpp:typeinfo for osg::NotifyHandler: error: undefined reference to 'typeinfo for osg::Referenced'
collect2: error: ld returned 1 exit status
make: *** [/Users/shuxinghu/Documents/work/osgAndroidExamp

**Comment by openscenegraph** [comment]
Could you please use the osg-users mailing list/forum for support questions like this as it's very like a general configuration issue that requires platform specific insights, this Issue tracker is not seen my enough users regularly to be able to help resolve niche platform issues.

**Comment by openscenegraph** [comment]
Closing this as it's a repeated Issue.
