### ISSUE TITLE
ShaderGen: Macro names starting with "GL_" are reserved

### ISSUE THREAD

**Issue by Hugal31** [openscenegraph/OpenSceneGraph#746]
For now, ShaderGen defines GL_LIGHTING, GL_FOG and GL_TEXTURE_2D macros in GLSL shaders (if theses modes are enabled in the stateset).

However, "GL_" prefixed macros are not permitted by some GLSL compilers. For instance, Mesa throws and error :

```
Compiling C: VERTEX source:
    1: #define GL_LIGHTING
    2: // ShaderGen shader
    3: // new version

...

   43: #if defined(GL_LIGHTING)
   44:     directionalLight(0, gl_Normal, vertexColor);
   45: #endif
   46: 

VERTEX glCompileShader "" FAILED
VERTEX Shader "" infolog:
0:1(9): preprocessor error: Macro names starting with "GL_" are reserved.
```

A possible solution is to prepend all the defines with `SHADERGEN_`, or `OSG_`, for example.

**Comment by openscenegraph** [comment]
Could you provide info on which drivers/hardware/OS and OSG version you are seeing problems with? Could you also provide guidance on how to reproduce the issue.

**Comment by Hugal31** [comment]
I am running Mesa 18.0.5 on a hybrid Intel Integrated / AMD Radeon HD 8730M. My OS is Ubuntu 16.04.

Here is a minimal example, using OSG 3.6.3:

```cpp
#include <osg/ShapeDrawable>
#include <osgGA/TrackballManipulator>
#include <osgUtil/ShaderGen>
#include <osgViewer/Viewer>

int main()
{
    // Create basis scene
    osg::ref_ptr<osg::Group> rootNode = new osg::Group;
    rootNode->addChild(new osg::ShapeDrawable(new osg::Box(osg::Vec3 { 0, 0, 0 }, 1)));

    // Add light to trigger the addition of GL_LIGHTING in ShaderGen
    rootNode->getOrCreateStateSet()->setMode(GL_LIGHTING, osg::StateAttribute::ON);

    // Pass ShaderGen visitor
    osgUtil::ShaderGenVisitor shaderGen;
    shaderGen.assignUberProgram(rootNode->getOrCreateStateSet());
    rootNode->accept(shaderGen);

    // Create viewer
    osgViewer::Viewer viewer;
    viewer.setSceneData(rootNode);
    viewer.setCameraManipulator(new osgGA::TrackballManipulator);

    return viewer.run();
}
```

Note: I use `ShaderGenVisitor::assignUberProgram` for simplicity, but it would trigger the error with any shader containing `#pragma import_defines(GL_LIGHTING)`.

**Comment by openscenegraph** [comment]
This would be potentially breaking change for 3.6 so is really just something that might be applicable to master.  Having to not use GL_LIGHTING etc is a real pain as it's the most logical mapping, the fallback of OSG_LIGHTING or OSG_GL_LIGHTING or MODE_GL_LIGHTING might be OK, but still pretty naff compared to just using what enum we are used to using in our applications.

For you own work I would suggest not using ShaderGen and just write your own shaders and use what ever #define's make sense for you.  ShaderGen is a a pretty old fallback that only supports a subset of the fixed function pipeline so pretty limiting so very soon you'd grow out of it anyway.
