### ISSUE TITLE
mac OSX build error with osg 3.6.4 lib

### ISSUE THREAD

**Issue by AllonJunior** [openscenegraph/OpenSceneGraph#748]
Hello, I encountered an referenced error when building `example_osgstaticviewer` of osg3.6.4 with XCode 10.2.1, the error said as `Undefined symbols for architecture x86_64:
  "_graphicswindow_Carbon", referenced from:
      ___cxx_global_var_init.29 in osgstaticviewer.o
ld: symbol(s) not found for architecture x86_64
`, I searched for this error, the solutions are always setting `OSG_WINDOWING_SYSTEM="Cocoa"`, but it is still there even if I set to Cocoa as suggested.
So, could you please kindly check it? Thanks!
BTW, I use cmake 3.14 command line like 
`
cmake ./ -G Xcode -DBUILD_OSG_EXAMPLES:BOOL=ON \
-DOSGEARTH_BUILD_APPLICATION_BUNDLES:BOOL=OFF \
-DDYNAMIC_OSGEARTH:BOOL=OFF \
-DOSGEARTH_USE_QT:BOOL=OFF \
-DCMAKE_INSTALL_PREFIX=./install \
-DOSG_DEFAULT_IMAGE_PLUGIN_FOR_OSX="imageio" \
-DOSG_WINDOWING_SYSTEM="Cocoa" \
-DDYNAMIC_OPENSCENEGRAPH:BOOL=OFF \
-DDYNAMIC_OPENTHREADS:BOOL=OFF
`

**Comment by mp3butcher** [comment]
Have you tried to purge cmake cache after setting OSG_WINDOWING_SYSTEM?

**Comment by AllonJunior** [comment]
> just an idea: Have you tried to purge cmake cache before setting OSG_WINDOWING_SYSTEM?

Yeah, I purged cmake cache very time before regenerate project, but nothing changed, the error still pop up.

**Comment by openscenegraph** [comment]
The OSGEARTH settings have no relevance to the build of the OSG itself so you can drop these.  In theory one shouldn't need to explicitly select the OSG_WINDOWING_SYSTEM, an appropriate default should be used.

What OSX are you using?  What happens in the normal build?  What value of OSG_WINDOWING_SYSTEM does the CMakeCache.txt have after run cmake on a clean build with the CMakeCache.txt removed so everything works from scratch?

**Comment by openscenegraph** [comment]
I have merged a PR relating to OSG_WINDOWING_SYSTEM, could you please update to master or the 3.6 and see if this resolves your issues.

**Comment by AllonJunior** [comment]
> I have merged a PR relating to OSG_WINDOWING_SYSTEM, could you please update to master or the 3.6 and see if this resolves your issues.

Sorry for reply late, I will update my code and feedback after testing, thanks a lot!

**Comment by AllonJunior** [comment]
> I have merged a PR relating to OSG_WINDOWING_SYSTEM, could you please update to master or the 3.6 and see if this resolves your issues.

Hi, thanks to your work, the issue has been solved now after testing. 😸
