### ISSUE TITLE
arial.ttf : file not handled

### ISSUE THREAD

**Issue by godshow** [openscenegraph/OpenSceneGraph#75]
platform: `OS X`  version:`3.5.2`
code:
```
    osg::ref_ptr<osgText::Font> font = osgText::readRefFontFile("fonts/arial.ttf");
    osgText::Text* text = new  osgText::Text;
    text->setFont(font);
```
error info:
```
bogon:bin retech$ ./osglogo 
Error reading file /Users/retech/Documents/Git/OpenSceneGraph-Data/fonts/arial.ttf: file not handled
```
Why failed to load TTF file(fail to create Font instance)?
and other example have the same problem,does need some plug when load TTF?

**Comment by openscenegraph** [comment]
You need the freetype plugin to load .ttf (true type) fonts.

**Comment by SpaceView** [comment]
I used vcpkg to install 
vcpkg install osg:x64-windows
and I checked that in my system the plugin is there,
D:\vs3D\vcpkg\installed\x64-windows\tools\osg\osgPlugins-3.6.5\osgdb_freetype.dll
I even add this path to env path, but it doesn't work, 
why I still get this problem?
