### ISSUE TITLE
OSG continues to look for dynamic libraries even after multiple failed attempts to load them

### ISSUE THREAD

**Issue by sbrkopac** [openscenegraph/OpenSceneGraph#764]
We recently had to track down a serious slow down after implementing some custom loaders for an animation format. The engine / data we are working with doesn't really care if you pass it data that does or doesn't exist (this is not something we can fix on our side either). 

Looks like after our loaders kick out, OSG has multiple fallback paths to try and find a way to load the file. This causes OSG to spam calls to try and load dynamic libraries. It would be nice to have the ReaderWriter return types have a bit more effect in osgDB, such as ```ReadResult::FILE_NOT_FOUND``` halting OSGs fallback mechanisms for loading. It would also be convenient to be able to set a flag to halt Dynamic Library loading if it fails the first time.

While I agree this should be mostly solved at in the user application by not trying to load bogus data - it would be nice we had a bit more ability to prevent the fallback loading.

**Comment by openscenegraph** [comment]
The way I'd try to catch this would be to write a custom osgDB::ReadFileCallback that checks files requests a black list of failed loads and then just return FILE_NOT_FOUND when a black listed file.

As for pushing changes into the core OSG to catch this particular case, I would guess that different applications would want to handle it in different ways so you might want some kind of callback mechanism for it, however, this is something a custom ReadFileCallback can probably handle so perhaps just providing one such callback if users want to use it would be one way.  I've got plenty of my plate so I'm not going to go writing stuff speculatively that can be written more appropriately be users.
