### ISSUE TITLE
why is glProgramParameteri  rather than glProgramParameteriEXT(osg/Program.cpp)

### ISSUE THREAD

**Issue by hankern** [openscenegraph/OpenSceneGraph#774]
i think there are some problems to use glProgramParameteri  in osg/Program.cpp from line 709-714.
`if (!_loadedBinary && _extensions->isGeometryShader4Supported)
    {
        _extensions->glProgramParameteri( _glProgramHandle, GL_GEOMETRY_VERTICES_OUT_EXT, _program->_geometryVerticesOut );
        _extensions->glProgramParameteri( _glProgramHandle, GL_GEOMETRY_INPUT_TYPE_EXT, _program->_geometryInputType );
        _extensions->glProgramParameteri( _glProgramHandle, GL_GEOMETRY_OUTPUT_TYPE_EXT, _program->_geometryOutputType );
}`
i find many places GL_GEOMETRY_VERTICES_OUT_EXT always is used with glProgramParameteriEXT.just like this
`glProgramParameteriEXT(prgId, GL_GEOMETRY_VERTICES_OUT_EXT, 4);
glProgramParameteriEXT(prgId, GL_GEOMETRY_INPUT_TYPE_EXT, GL_POINTS);
glProgramParameteriEXT(prgId, GL_GEOMETRY_OUTPUT_TYPE_EXT, GL_TRIANGLE_STRIP);`

i see the definition of _extensions->glProgramParameteri is setGLExtensionFuncPtr(glProgramParameteri,  "glProgramParameteri", "glProgramParameteriEXT", validContext);
that means _extensions->glProgramParameteri can be glProgramParameteri or glProgramParameteriEXT,not exactly glProgramParameteriEXT.

**Comment by mp3butcher** [comment]
lookat at how function ptr are defined in osg/GLExtensions.cpp
https://github.com/openscenegraph/OpenSceneGraph/blob/817b999d1f21f7acf1aa09e6adc815564b91c768/src/osg/GLExtensions.cpp#L626

**Comment by hankern** [comment]
i see, thx
