### ISSUE TITLE
generate cubemap from 3D scene

### ISSUE THREAD

**Issue by json87** [openscenegraph/OpenSceneGraph#776]
hi, 
  Thanks for providing the excellent toolkit for 3D scene rendering. Recently, I have downloaded a terrain data (digital elevation model) and generate a 3D terrain model using osgDEM. 

![terrain](https://user-images.githubusercontent.com/17582213/59995854-2d87b600-968b-11e9-9537-0eaddf11691a.jpg)

Now, I want to generate some cubemaps at some specified locations, as illustrated as following.

![cubmap](https://user-images.githubusercontent.com/17582213/59995757-da156800-968a-11e9-9d19-a626cae2f36b.png)

Is there any sample code to achieve the purpose.
thanks!

**Comment by mp3butcher** [comment]
issue report is not a place for question
use the forum http://forum.openscenegraph.org/ for that

**Comment by robertosfield** [comment]
Have a look at the osgprerendercubmemap example. Any further questions please post them to the osg-users mailing list/forum as this is the proper channel for user support.
