### ISSUE TITLE
Incorrect default location for true type fonts on openSUSE

### ISSUE THREAD

**Issue by rhabacker** [openscenegraph/OpenSceneGraph#778]
At https://github.com/openscenegraph/OpenSceneGraph/blob/master/include/osgText/Font#L45 directory paths are listed for True Type fonts used on non-Windows operating systems. At least for openSUSE this does not fit, because the default location /usr/share/fonts/truetype is used.

**Comment by robertosfield** [comment]
I just checked my Kubuntu system and there isn't a /usr/share/fonts/ttf directory either so have to assume that the ones encoded into Font.cpp are out of date.  The ttf files within my /user/share/fonts/truetype look to be no standard so I very much doubt using the same font under Windows will work under Linux when attempting to use the /usr/shader/fonts/truetype directory.

So I can add in /usr/share/fonts/truetype in to the list and it won't break anything, but also I don't think it'll actually fix anything.

**Comment by rhabacker** [comment]
According to **https://stackoverflow.com/questions/4347277/locating-fonts-on-linux-in-c** the correct way to determine a font by raw filename e.g. arial.ttf  seems to be using fontconfig.

```
fc-match --format=%{file} arial.ttf
/usr/share/fonts/truetype/arial.ttf
```
A related api example is located at https://gist.github.com/CallumDev/7c66b3f9cf7a876ef75f#file-fontconfig-c, which looks good for adding to osgText::findFontFile (https://github.com/openscenegraph/OpenSceneGraph/blob/master/src//osgText/Font.cpp#L50)

**Comment by robertosfield** [comment]
We'll need to discuss this futher once 3.6.4 is out as changes will need quite a bit of testing on the various linux distributions to make sure things are working across the various disto and versions of them.

**Comment by openscenegraph** [comment]
The commit looks reasonable to me.  I'd be happy to do review so please go ahead and generate a PR for it.
