### ISSUE TITLE
Deprecated use of wxWidgets_USE_LIBS is broken with CMake 3.14.0

### ISSUE THREAD

**Issue by StefanBruens** [openscenegraph/OpenSceneGraph#779]
Since https://github.com/Kitware/CMake/commit/0813581859bd61a9d30c97aa893030bea85f134e

FIND_PACKAGE(wxWidgets) allows to specify *OPTIONAL" components. Unfortunately,
everything from wxWidgets_USE_LIBS ends up in the OPTIONAL component list, not in the REQUIRED component list.

**Comment by robertosfield** [comment]
Does your commit affect older versions of CMake?  Does it gracefully fails when WxWidgetsi isn't installed.

The OSG only uses WxWdigets for a single example that illustrates integration between OSG and WxWidgets so it's important that WxWidgets remains only an optional dependency.
