### ISSUE TITLE
Links in Reference guides are all mixed up

### ISSUE THREAD

**Issue by ruimaciel** [openscenegraph/OpenSceneGraph#783]
This might not be the best place to post this issue but I've just noticed that [OpenSceneGraph's Reference Guides page](http://www.openscenegraph.org/index.php/documentation/guides/46-reference-guides) has all its links mixed up.  For instance, the "osg" link currently points to the docs on osgUtil's namespace reference, osgUtil's link points to osgFX, osgDB points to osgParticle, etc...

**Comment by openscenegraph** [comment]
Looks like doxygen is changing the names of the various files each time the docs are regenerated, and as this is done automatically now the webpage with the hardwired links are no longer going to be viable.  To avoid this issue I've reworked the problem page with the hardwired links to only use links to pages where the name doesn't change.
