### ISSUE TITLE
linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

### ISSUE THREAD

**Issue by SHIHUAMarryMe** [openscenegraph/OpenSceneGraph#784]
**need create shaders by myself?**

void StateSet::setGlobalDefaults() ShaderPipeline enabled, numTextUnits = 4
void StateSet::setGlobalDefaults() ShaderPipeline enabled, numTextUnits = 4
VERTEX glCompileShader "" FAILED
VERTEX Shader "" infolog:
0:1(9): preprocessor error: Macro names starting with "GL_" are reserved.

0:2(9): preprocessor error: Macro names starting with "GL_" are reserved.

0:3(9): preprocessor error: Macro names starting with "GL_" are reserved.

FRAGMENT glCompileShader "" FAILED
FRAGMENT Shader "" infolog:
0:1(9): preprocessor error: Macro names starting with "GL_" are reserved.

0:2(9): preprocessor error: Macro names starting with "GL_" are reserved.

0:3(9): preprocessor error: Macro names starting with "GL_" are reserved.

glLinkProgram 0x7f6fcc04c600"" FAILED
Program "" infolog:
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

**I use a demo to produce a test.osg file, then use osgviewer to open it.**

**ubuntu 18.4
osg(master)**

**here is the code.**

`#include <osg/ref_ptr>
#include <osgDB/Registry>
#include <osgDB/WriteFile>
#include <osg/Notify>
#include <osg/Geode>
#include <osg/Geometry>

#include <iostream>

int main()
{
    osg::ref_ptr<osg::Geometry> geometry_ptr{new osg::Geometry};
    osg::ref_ptr<osg::Vec3Array> vertex_data_ptr{new osg::Vec3Array};

    vertex_data_ptr->push_back(osg::Vec3(-1.f, 0.f, -1.f));
    vertex_data_ptr->push_back(osg::Vec3(1.f, 0.f, -1.f));
    vertex_data_ptr->push_back(osg::Vec3(1.f, 0.f, 1.f));
    vertex_data_ptr->push_back(osg::Vec3(-1.f, 0.f, 1.f));

    osg::ref_ptr<osg::Vec4Array> color_array{new osg::Vec4Array};
    geometry_ptr->setColorArray(color_array.get());
    geometry_ptr->setColorBinding(osg::Geometry::BIND_PER_VERTEX);
    color_array->push_back(osg::Vec4(1.f, 0.f, 0.f, 1.f));
    color_array->push_back(osg::Vec4(0.f, 1.f, 0.f, 1.f));
    color_array->push_back(osg::Vec4(0.f, 0.f, 1.f, 1.f));
    color_array->push_back(osg::Vec4(1.f, 1.f, 1.f, 1.f));

    osg::ref_ptr<osg::Vec3Array> normal_array{new osg::Vec3Array};
    geometry_ptr->setNormalArray(normal_array.get());
    normal_array->push_back(osg::Vec3{0, 1, 0});

    geometry_ptr->addPrimitiveSet(new osg::DrawArrays{osg::PrimitiveSet::QUADS, 0, 4});

    osg::ref_ptr<osg::Geode> geode_ptr{new osg::Geode};
    geode_ptr->addDrawable(geometry_ptr.get());

    if (!geode_ptr.valid())
    {
        osg::notify(osg::FATAL) << "failed to create a node!" << std::endl;
    }

    bool result{osgDB::writeNodeFile(*(geode_ptr.get()), "./test.osg")};

    if (!result)
    {
        osg::notify(osg::FATAL) << "failed to create a osg file!" << std::endl;
    }

    return 0;
}`

**Comment by mp3butcher** [comment]
I admit ML s not working these days, so i answer
But please , issues is not a place for user problem, use mailing list instead 

your problem should be
`geometry_ptr->setNormalArray(normal_array.get(),osg::Array:BIND_OVERALL);
`

**Comment by SHIHUAMarryMe** [comment]
> I admit forum's not working these days, so i answer
> But please , issues is not a place for user problem, use mailing list instead
> 
> your problem should be
> `geometry_ptr->setNormalArray(normal_array.get(),osg::Array:BIND_OVERALL); `

Sorry about using issue for user problem.
I use your code, also change nothing.

**Comment by mp3butcher** [comment]
what's the targetted plateform please?

**Comment by SHIHUAMarryMe** [comment]
> what's the targetted plateform please?

system: ubutun 18.4

osg_test: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=b2cff37149d0a58548c0c129b4473a129e56b4fb, with debug_info, not stripped


OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

**Comment by robertosfield** [comment]
The OSG by default will not use shaders so will not generate any shader errors. So.... there is a the missing bit in the jigsaw here, how did you build the OSG?  Use GL core profile build option?  If you are doing the later then you should be providing your own shaders.

**Comment by SHIHUAMarryMe** [comment]
> The OSG by default will not use shaders so will not generate any shader errors. So.... there is a the missing bit in the jigsaw here, how did you build the OSG? Use GL core profile build option? If you are doing the later then you should be providing your own shaders.

I just installed opengl through apt-get and I also installed glfw and glm. 
Recently company need osg, so I build by osg's README(also export ev).
**Just clone from this repo,
mkdir build
cmake ..
make all
sudo make install
At last add ev to .bashrc.**  
Then I try to create a demo, this happened.

whether I need rebuild opengl?

**Comment by mp3butcher** [comment]
if you don't use fixed pipeline (default in osg) you'll have to add your own shader program

**Comment by SHIHUAMarryMe** [comment]
> if you don't use fixed pipeline (default in osg) you'll have to add your own shader program

Sorry, I am a new bie.
what should I do to fix the pipeline?

**Comment by openscenegraph** [comment]
I would recommend you just stick with the OpenSceneGraph-3.6 branch and not use experimental functionality like the OSG_SHADER_PIPELINE functionality.

Also please use the osg-users mailing list for support as this is an Issue tracker for bugs rather than general user support.
