### ISSUE TITLE
forum.openscenegraph.org does not respond

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#787]
Is http://forum.openscenegraph.org/ down?

http://www.openscenegraph.org/index.php/support/2012-04-25-09-35-21

**Comment by openscenegraph** [comment]
I'll contact the maintainers of the forum to see what might be up.  It may be that we finally need to change to another forum.

For support in the meantime please use the osg-users mailing list, this is that part that I'm responsible for and can directly address issues with.

   http://lists.openscenegraph.org/listinfo.cgi/osg-users-openscenegraph.org

**Comment by openscenegraph** [comment]
forum is now back up.
