### ISSUE TITLE
VRML plugin does not build due to deprecated_osg usage

### ISSUE THREAD

**Issue by gleng** [openscenegraph/OpenSceneGraph#793]
The VRML plugin fails to build because it is still using deprecated_osg code that was removed a few years ago in commit aea83494c140188afb4b0a7db831e619aedd3e85. It looks like it needs to be updated to either no longer use this code, or to use its own local deprecated_osg implementation, like in the Inventor plugin.

**Comment by openscenegraph** [comment]
I had a quick bash at compiling OpenVRML but couldn't get it compile on my Kubuntu 18.04 system and didn't even get past the configure passing.  The latest version of OpenVRML is 5 years out of date so essentially the project is dead.  Given our plugin is also relying upon deprecated functionality I think it's time to remove the plugin so I've done this for the 3.6 branch and master.

https://github.com/openscenegraph/OpenSceneGraph/commit/b957581342baa2ecdbfcf66f75e52c30f9e51d4b

https://github.com/openscenegraph/OpenSceneGraph/commit/d695ed816bac6240e26bf666980231dac1431fbb
