### ISSUE TITLE
OpenSceneGraph-3.6.4 + FontConfig (unable to disable)

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#801]
FontConfig should be an OPTION for osgText.
There is no real possibility to disable it (for example on macOS with macports etc.)

**Comment by openscenegraph** [comment]
Could you explain specific what issues you are seeing?

I'm guess macports has FontConfig so the OSG is now build with it and using it in osgText, and this is causing a problem for you.  What problems are you seeing?

It's important to figure out in what way we need to adjust things to give users the control they need.

**Comment by valid-ptr** [comment]
I'll create PR in 15 minutes
