### ISSUE TITLE
GL_QUADS with OpenGL Core Profile

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#803]
I've created PR #804 for osgParticle::ParticleSystem but there are many places in OSG-3.6 where GL_QUADS are used, at least:
```
osgVolume::RayTracedTechnique
osgVolume::MutipassTechnique
osgViewer::WoWVxDisplay (Why not to use createTexturedQuadGeometry here?)
```

I think this preprocessor condition will be correct:
```
 #if defined(OSG_GL1_AVAILABLE) || defined(OSG_GL2_AVAILABLE) || defined(OSG_GLES1_AVAILABLE)
// Draw GL_QUADS
#else
// Draw GL_TRIANGLES etc.
#endif
```

**Comment by openscenegraph** [comment]
I have just checked in to master and the 3.6 branch a change the osgVolume to replace the use of GL_QUADS:

https://github.com/openscenegraph/OpenSceneGraph/commit/8fad6bd0391847719fd5bbe3cdbf2bb0781b246c

**Comment by openscenegraph** [comment]
Finally replaced the GL_QUADS in the WoWVxDisplay:

https://github.com/openscenegraph/OpenSceneGraph/commit/92abaca21021d5db729366d8da7e6f5703cb33a4
