### ISSUE TITLE
OSG Plugins Building opencascade plugin fails on windows OSG 3.6.4

### ISSUE THREAD

**Issue by mselim** [openscenegraph/OpenSceneGraph#807]
Building Plugin **opencascade** which is a part of **OSG plugins** fails due to linking error. The TXKCAF lib is missing from the list of linking libraries. The source of this problem is originating from  
CMakeModules\FindOpenCascade.cmake file. This problem can be solved by adding `FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF) `
to the **FindOpenCascade.cmake** file.

**Comment by openscenegraph** [comment]
OpenCascade has turned out to be a pain to keep linking as different versions move the goal posts.

Which version of OpenCascade are you linking against?  Did you build it yourself?  What build platform and build tools and CMake version are you using?

**Comment by mselim** [comment]
Here are the versions involved in the build of OSG
CMAKE 3.13
OpenCascade 7.2.0
OSG 3.6.3/OSG 3.6.4
Visual Studio 2015
Windows 10.
I do confirm the problem is also spotted when building OSG 3.6.3. I know that OpenCascade is a pain, but this time it is not the occ to blame. I believe that a missing cmake find lib is the root cause, just try adding the following to the find library section in file CMakeModules\FindOpenCascade.cmake, would solve the problem:

`FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF)` 

As the rest of the libraries are already set (30 something library file), they are defined including TKXCAF.lib, except that the FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF) is missing, that's why it's not included in the libraries to be linked.

**Comment by openscenegraph** [comment]
Tanks for the details.  I've just looked at the history of the FindOpenCascade.cmake and see that TKXCAF was partially removed by @aluaces back in the commit:

https://github.com/openscenegraph/OpenSceneGraph/commit/958e954b93ff2764d54e63d27dd36d094e983b9a#diff-456a927e5a6873d12268b56f4144aa16

The FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF) was by Alberto, then     add entry ${OPENCASCADE_TKVCAF} was removed from the lib list, but there was a double entry there so one remained.  Could it be that the remaining ${OPENCASCADE_TKVCAF} could no longer be required?

**Comment by aluaces** [comment]
@mselim , can you post the exact linker error so I can look for the missing symbol?

**Comment by mselim** [comment]
@aluaces , here's the linking error when building OpenCascade plugin out of the box.

> 1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: bool __cdecl XCAFDoc_ColorTool::GetColor(class TDF_Label const &,enum XCAFDoc_ColorType,class Quantity_Color &)" (?GetColor@XCAFDoc_ColorTool@@QEAA_NAEBVTDF_Label@@W4XCAFDoc_ColorType@@AEAVQuantity_Color@@@Z) referenced in function "private: void __cdecl ReaderWritterOpenCASCADE::OCCTKReader::_traverse(class TDF_Label const &,class gp_Trsf &)" (?_traverse@OCCTKReader@ReaderWritterOpenCASCADE@@AEAAXAEBVTDF_Label@@AEAVgp_Trsf@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static class TopoDS_Shape __cdecl XCAFDoc_ShapeTool::GetShape(class TDF_Label const &)" (?GetShape@XCAFDoc_ShapeTool@@SA?AVTopoDS_Shape@@AEBVTDF_Label@@@Z) referenced in function "private: void __cdecl ReaderWritterOpenCASCADE::OCCTKReader::_traverse(class TDF_Label const &,class gp_Trsf &)" (?_traverse@OCCTKReader@ReaderWritterOpenCASCADE@@AEAAXAEBVTDF_Label@@AEAVgp_Trsf@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: void __cdecl XCAFDoc_ShapeTool::GetFreeShapes(class NCollection_Sequence<class TDF_Label> &)const " (?GetFreeShapes@XCAFDoc_ShapeTool@@QEBAXAEAV?$NCollection_Sequence@VTDF_Label@@@@@Z) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static bool __cdecl XCAFDoc_ShapeTool::GetReferredShape(class TDF_Label const &,class TDF_Label &)" (?GetReferredShape@XCAFDoc_ShapeTool@@SA_NAEBVTDF_Label@@AEAV2@@Z) referenced in function "private: void __cdecl ReaderWritterOpenCASCADE::OCCTKReader::_traverse(class TDF_Label const &,class gp_Trsf &)" (?_traverse@OCCTKReader@ReaderWritterOpenCASCADE@@AEAAXAEBVTDF_Label@@AEAVgp_Trsf@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static class Standard_GUID const & __cdecl XCAFDoc_Location::GetID(void)" (?GetID@XCAFDoc_Location@@SAAEBVStandard_GUID@@XZ) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: class TopLoc_Location const & __cdecl XCAFDoc_Location::Get(void)const " (?Get@XCAFDoc_Location@@QEBAAEBVTopLoc_Location@@XZ) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static class opencascade::handle<class XCAFDoc_ShapeTool> __cdecl XCAFDoc_DocumentTool::ShapeTool(class TDF_Label const &)" (?ShapeTool@XCAFDoc_DocumentTool@@SA?AV?$handle@VXCAFDoc_ShapeTool@@@opencascade@@AEBVTDF_Label@@@Z) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static class opencascade::handle<class XCAFDoc_ColorTool> __cdecl XCAFDoc_DocumentTool::ColorTool(class TDF_Label const &)" (?ColorTool@XCAFDoc_DocumentTool@@SA?AV?$handle@VXCAFDoc_ColorTool@@@opencascade@@AEBVTDF_Label@@@Z) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ReaderWriterOpenCASCADE.obj : error LNK2019: unresolved external symbol "public: static class opencascade::handle<class XCAFApp_Application> __cdecl XCAFApp_Application::GetApplication(void)" (?GetApplication@XCAFApp_Application@@SA?AV?$handle@VXCAFApp_Application@@@opencascade@@XZ) referenced in function "public: class osg::ref_ptr<class osg::Geode> __cdecl ReaderWritterOpenCASCADE::OCCTKReader::igesToOSGGeode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?igesToOSGGeode@OCCTKReader@ReaderWritterOpenCASCADE@@QEAA?AV?$ref_ptr@VGeode@osg@@@osg@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

> 
All of these external symbols are defined in TKXCAF.lib which is missing from the linking dependencies as I stated above.

**Comment by aluaces** [comment]
I can confirm that on Debian Buster, restoring the `FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF)` line keeps linking everything correctly.

**Comment by openscenegraph** [comment]
I've merged the addition of FIND_OPENCASCADE_LIBRARY(OPENCASCADE_TKXCAF TKXCAF) to master and the 3.6 branch:

https://github.com/openscenegraph/OpenSceneGraph/commit/da40a565bf0689705fe57ffaf12449301cd900b5
