### ISSUE TITLE
osg/TriangleFunctor why not support Vec3d* vertex arrays and so on

### ISSUE THREAD

**Issue by hankern** [openscenegraph/OpenSceneGraph#809]
Has osg/TriangleFunctor file not been finished?

**Comment by openscenegraph** [comment]
It's finished, it's just a design decision to focus on the type of data that 99.9% of data that users will use for geometry.

The OSG does support double Vertex arrays but only in limited ways, it's enough to get data loaded for sources that are in doubles, such as geospatial data, but that data should be transformed to a local origin and vertex data converted to floats in this local origin for rendering purposes as GL/graphics hardware is designed around float vertex data and is cripplingly slow when you pass it double vertex data.

So.. osg::TriangleFunctor not supporting doubles will be only part of your problem, the rest of the problems aren't things the OSG can solve, as it can't change graphics hardware.
