### ISSUE TITLE
OSG 3.6.4 RPM build problem

### ISSUE THREAD

**Issue by DieSlower** [openscenegraph/OpenSceneGraph#812]
It seems an error was introduced into OSG 3.6.4 when  OpenSceneGraph/CMakeModules/FindFontconfig.cmake  was added to the build. Fortunately it is an easy fix, and does not touch actual code. 
It is easy to miss, I have tested this on Windows and Linux (CentOS 7). Visual Studio and GCC build OSG just fine, but when on linux you try to package OSG for product delivery with RPMBuilder v4.11.3 (standard linux RPM building tool) you get an error. 

``
CMake Error: Error in cmake code at:
/home/<username>/rpmbuild/BUILD/OpenSceneGraph-OpenSceneGraph-3.6.4/CMakeModules/FindFontconfig.cmake:6:
Parse error. Expected "(", got newline with text "
".
``
The error comes from using uncommon block comments:
#[============[ and
#]============]

If this block comment is replaced with normal CMake # comments, everything seems to start working again. 

I can submit a PR for this, or if you want, you can just replace the comment code in the file. 

Let me know,
--MS

**Comment by openscenegraph** [comment]
Please change your github handle it's still just plain obnoxious.  You might not care what other people think of you, but I care what people think of the OSG and it's community.
