### ISSUE TITLE
GLES1, GLES2 and GLES3: exceptions on/off ?

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#821]
Is this really correct?:

https://github.com/openscenegraph/OpenSceneGraph/blob/master/CMakeLists.txt#L537

Why one disable exceptions because of GLES1, GLES2 or GLES3?

**Comment by openscenegraph** [comment]
It's just a common default for embedded systems, which is where the GLES* case comes from.

**Comment by remoe** [comment]
But this is not directly related to GLES*. For example when one build with emscripten/wasm it's not necessarily the case.

**Comment by vsg-dev** [comment]
The conditionals were written before enscripten came on the scene.   It's an option so you should be able to override this default.
