### ISSUE TITLE
TGA Plugin won't build with Visual Studio earlier than 2015

### ISSUE THREAD

**Issue by BeagleJoe** [openscenegraph/OpenSceneGraph#824]
Changes to ReaderWriterTGA.cpp for 3.6.4 have broken building OSG on older versions of Visual Studio.
Specifically, Line 328:
    `explicit operator U() { return (U)impl; }`
I believe `explicit operator` requires C++11.
Removing the `explicit` keyword fixes the build.

**Comment by openscenegraph** [comment]
Fixed:

https://github.com/openscenegraph/OpenSceneGraph/commit/bd50af117bed340b14b5bf13da6a8efe893f4ce7
