### ISSUE TITLE
element positions of 3ds model not correctly display

### ISSUE THREAD

**Issue by 1molPotato** [openscenegraph/OpenSceneGraph#829]
I got a 3ds file which is displayed in _**3ds Max 2017**_ as like this:
![image](https://user-images.githubusercontent.com/11970884/63662617-b2a95b80-c7f1-11e9-9ecc-b9c7fd3c5e31.png)
but when I open it with osg (using command line: ./osgviewer.exe <3dsModelPath>) and it's shown like this:
![image](https://user-images.githubusercontent.com/11970884/63662680-f69c6080-c7f1-11e9-8a37-6896b1977f75.png)
so I am wondering if the 3ds importer of osg library has something wrong (maybe when do matrix transformation or because of the poor precision of float data?)
I noticed that you also use _**lib3ds**_ to handle the 3ds importing, so I would appreciate if you could help me investigate this problem, the model file can be downloaded from the link below:
[element_position_issue](https://drive.google.com/open?id=1MIGdcVrYmbqlncoiCt4h60x1NYfUjWXk)

**Comment by openscenegraph** [comment]
I have had a look at the model and reproduce the sizing issues you see.  Our 3ds plugin hasn't been modified much for quite some time so this is unlikely to be a regression.  I haven't personally worked lots of this plugin or with 3ds files, instead have relied upon members of the community who use 3ds files regularly to help refine it. 

The fact that those of the community working on the 3ds haven't flagged this issue suggests to me that there may be some variability in interpretation of how the 3ds transformation data should be interpreted.  I'll add a few of the contributors to the 3ds plugin to see if anything jumps out as a possible cause.

@LaurensVoerman, @aluaces, @marchelbling any of you guys familiar enough with the 3ds plugin to recognize the above issue?

**Comment by LaurensVoerman** [comment]
Hi 1molPotato,
if I import your 3ds file in max2020 and export to 3ds again, most of the problems disappear. While that sounds nice, it also means that I have no way to reduce the model to the problematic parts, and that is really needed to start finding out what goes wrong.
I've checked old osg versions: 3.4.0 & 3.2.2 visually give the same result,
osg 1.0 (2005) seems to have the geometry right (some errors and all color is gone)

In general I would recommend to use fbx to get data from 3dsmax to osg.
Laurens.
