### ISSUE TITLE
Texture2DArray can't store the image of Texture2D of RTT

### ISSUE THREAD

**Issue by loening** [openscenegraph/OpenSceneGraph#830]
Why I can't use Texture2DArray to store the image of Textue2D of RTT? I want to store over 100 RTT textures.
I write a simple sampler below. But the result is the Texture2DArray is empty.
`    osg::ref_ptr<gr::CPass> Pass = new gr::CPass();

	osg::ref_ptr<osg::Texture2DArray> Texture2DArray = new osg::Texture2DArray;
	Texture2DArray->setTextureSize(800, 600, 3);
	Texture2DArray->setInternalFormat(GL_RGBA);
	Texture2DArray->setSourceFormat(GL_RGBA);
	Texture2DArray->setSourceType(GL_FLOAT);
    
	int n = 3;
	std::vector<osg::ref_ptr<osg::Texture2D>> Texture2DList;
	for (int i = 0; i < n; i++)
	{
		osg::ref_ptr<osg::Texture2D> Texture2D = new osg::Texture2D;
		Texture2D->setTextureSize(800, 600);
		Texture2D->setInternalFormat(GL_RGBA);
		Texture2D->setSourceFormat(GL_RGBA);
		Texture2D->setSourceType(GL_FLOAT);
		Texture2DList.push_back(Texture2D.get());
	}
    
    osg::ref_ptr<osg::Vec4Array> ColorArray = new osg::Vec4Array(3);
    (*ColorArray)[0].set(1.0, 0.0, 0.0, 1.0);
    (*ColorArray)[1].set(0.0, 1.0, 0.0, 1.0);
    (*ColorArray)[2].set(0.0, 0.0, 1.0, 1.0);
    
	osg::ref_ptr<gr::CScene> Grid = new gr::CDrawScene("Grid");
	osg::ref_ptr<osg::Group> GridNode = Grid->getScene();
	for (int i = 0; i < n; i++)
    {
		osg::ref_ptr<osg::Camera> Camera = Pass->createGeometryPass(osg::Camera::COLOR_BUFFER, Texture2DList[i].get());
		Camera->addChild(GridNode.get());

        osg::ref_ptr<osg::StateSet> StateSet = Camera->getOrCreateStateSet();
        StateSet->setAttributeAndModes(ShaderInstance::getInstance()->configShader("shaders/SimpleColor.vert", "shaders/SimpleColor.frag"));
        StateSet->addUniform(new osg::Uniform("uColor", (*ColorArray)[i]));
        StateSet->setMode(GL_DEPTH_TEST, osg::StateAttribute::OFF);
        StateSet->setMode(GL_BLEND, osg::StateAttribute::OFF);
        
        addPass(Camera.get());
		Texture2DArray->setImage(i, Texture2DList[i]->getImage());
    }`

**Comment by openscenegraph** [comment]
A texture2DArray and Texture2D both map to specific OpenGL texture object types, you can't nest them within each other, it's simply the way OpenGL works.
