### ISSUE TITLE
osgWidget::Label memory leak

### ISSUE THREAD

**Issue by chengwei920412** [openscenegraph/OpenSceneGraph#840]
osgWidget::Label::setLabel memory leak,
auto label = new osgWidget::Label("", "");
while(true){
    label->setLabel("...............");
}

**Comment by openscenegraph** [comment]
It's not appropriate to use auto in this way as it'll may to a C pointer without any memory management protection, you should use ref_ptr<> for all OSG objects created on the heap.

**Comment by chengwei920412** [comment]
memory leak happen in label->setLabel("....");

this is my test code, modify from example osgwidgetlabel.

// -*-c++-*- osgWidget - Code by: Jeremy Moles (cubicool) 2007-2008
// $Id: osgwidgetlabel.cpp 66 2008-07-14 21:54:09Z cubicool $

#include <osg/io_utils>
#include <osgWidget/Util>
#include <osgWidget/WindowManager>
#include <osgWidget/Box>
#include <osgWidget/Label>
#include <osgViewer/ViewerEventHandlers>
#include <osgWidget/Util>
#include <osgWidget/ViewerEventHandlers>
#include <osgWidget/WindowManager>
#include <osgGA/TrackballManipulator>
#include <osgGA/StateSetManipulator>

const unsigned int MASK_2D = 0xF0000000;

const char* LABEL1 =
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed\n"
    "do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n"
    "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris\n"
    "nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in..."
;

const char* LABEL2 =
    "...reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla\n"
    "pariatur. Excepteur sint occaecat cupidatat non proident, sunt in \n"
    "culpa qui officia deserunt mollit anim id est laborum. BBBBB"
;

osgWidget::Label* createLabel(const std::string& l, unsigned int size=13) {
    osgWidget::Label* label = new osgWidget::Label("", "");

    label->setFont("fonts/Vera.ttf");
    label->setFontSize(size);
    label->setFontColor(1.0f, 1.0f, 1.0f, 1.0f);
    label->setLabel(l);

    return label;
}

int main(int, char**)
{
    osgViewer::Viewer viewer;

    osgWidget::WindowManager* wm = new osgWidget::WindowManager(
        &viewer,
        1280.0f,
        1024.0f,
        MASK_2D,
        // osgWidget::WindowManager::WM_USE_RENDERBINS |
        osgWidget::WindowManager::WM_PICK_DEBUG
    );

    osgWidget::Box*   box    = new osgWidget::Box("HBOX", osgWidget::Box::HORIZONTAL);
    box->setAnchorHorizontal(osgWidget::Window::HorizontalAnchor::HA_LEFT);
    box->setAnchorVertical(osgWidget::Window::VerticalAnchor::VA_TOP);

    osgWidget::Label* label1 = createLabel(LABEL1);
    label1->setPadding(10.0f);
    label1->addSize(21.0f, 22.0f);
    label1->setColor(1.0f, 0.5f, 0.0f, 1.0f);
    box->addWidget(label1);

    wm->addChild(box);

    //return osgWidget::createExample(viewer, wm);
    viewer.setUpViewInWindow(
        50,
        50,
        static_cast<int>(wm->getWidth()),
        static_cast<int>(wm->getHeight())
    );

    osg::Group* group = new osg::Group();
    osg::Camera* camera = wm->createParentOrthoCamera();

    group->addChild(camera);

    viewer.addEventHandler(new osgWidget::MouseHandler(wm));
    viewer.addEventHandler(new osgWidget::KeyboardHandler(wm));
    viewer.addEventHandler(new osgWidget::ResizeHandler(wm, camera));
    viewer.addEventHandler(new osgWidget::CameraSwitchHandler(wm, camera));
    viewer.addEventHandler(new osgViewer::StatsHandler());
    viewer.addEventHandler(new osgViewer::WindowSizeHandler());
    viewer.addEventHandler(new osgGA::StateSetManipulator(viewer.getCamera()->getOrCreateStateSet()));

    wm->resizeAllWindows();

    viewer.setSceneData(group);

    int i = 0;

    while (!viewer.done()) {
        viewer.frame();
        std::ostringstream ostr;
        ostr << ";difj;aidjf;alisdjf;alisdjf;lajg;ia\njfa;sidjf;alisdjf;aisdjf;alsdijfa;oisdjga;sildjfa\na;sldjfaisdjg;alsdkjf;aisjdf;liasdn;gjiasdjf;aie\n" << i++ << "  .";
        //label1->setLabel(ostr.str());
    }
    return 0;
}
