### ISSUE TITLE
DEEP_COPY_USERDATA isn't that deep

### ISSUE THREAD

**Issue by AnyOldName3** [openscenegraph/OpenSceneGraph#845]
As discussed here: http://forum.openscenegraph.org/viewtopic.php?p=76755

`osg::CopyOp::DEEP_COPY_USERDATA` copies the `UserDataContainer`, but doesn't deep-copy the actual things in it unless `osg::CopyOp::DEEP_COPY_OBJECTS` is also enabled. This means that things can be added or removed, but changes to existing things are shared.

I tried making a fix for this, but some of `osg::DefaultUserDataContainer`'s members aren't easily deep-copied:
* `_userData` is an `osg::ref_ptr<osg::Referenced>`, but `Referenced` has no way to deep copy it without knowing which subclass it actually is.
* `_descriptionList` is just a vector of strings, so *is* deep copied already.
* `_objectList` is a vector of `osg::ref_ptr<osg::Object>`, which normally *can* be deep copied. However, we can't use the `osg::CopyOp` we're given as it might be set to shallow-copy `Object`s. We can't change its flags, do the copy, and then change them back as it's a const reference, and casting off the cost is bad. We can't copy it, either, as we don't know if it's a subclass of `CopyOp`v and there's no mechanism to clone a `CopyOp`.

**Comment by openscenegraph** [comment]
HI Chris, I'm back over caching up with OSG support.  The old forum fell off the web so I had to fallback to using the googlegroup mirror for the forum.  This contains all the original posts but unfortunately doesn't have the same link mappings so the above line doesn't work.  Can you recall the topic title or key phrases so I can search for it?

**Comment by AnyOldName3** [comment]
This is at least part of the thread: https://groups.google.com/forum/#!topic/osg-users/ep655XdSSAE

Will you also need me to bump the thread about closing OpenGL contexts not always releasing GL objects in the object cache, too? I don't think there was an open issue for that.

**Comment by openscenegraph** [comment]
I've investigated and believe that the code is correct, if you want to do a deep copy including all the nested objects then you should simply use an OR or the CopyOp::DEEP_COPY_ALL Option.

Discussion topic:
https://groups.google.com/forum/#!searchin/osg-users/DEEP_COPY_USERDATA$20isn$27t$20that$20deep%7Csort:date/osg-users/vq6UEt_m1so/Cw_xgtccCQAJ

**Comment by AnyOldName3** [comment]
I'm trying to find the reply button on the google group but can't. Is it a one-way mirror unlike the old forums? I had (non-specific and long-forgotten) issues the one time I tried using the mailing list as a mailing list.

What are your thoughts on the proposed `DEEP_COPY_USERDATA_AND_CONTENTS` mode mentioned in that thread? I was under the impression that it was only dismissed because you wanted that behaviour to *replace* what OSG does now instead of keeping the old behaviour, so if we've decided the old behaviour *is* doing what it's supposed to, would that put the new mode back on the menu?

In OpenMW, we genuinely do need to deep-copy the user data child objects but not other objects higher up in the tree (except any we set with other flags). I'm not sure of the details any more as it wasn't me running that investigation and it was months ago (if I had to guess, it's because we need to share stuff like statesets and geometries to reduce state switches and that kind of thing, but need the user data to be per-instance). The fix we went for was [this](https://github.com/OpenMW/openmw/pull/2529/files), so if the new mode is off the table, was that the right thing to do.

**Comment by openscenegraph** [comment]
To reply on the osg-users googlegroup you'll need to be a member of the list and logged int. Membership of the osg-users mailing list and old forum aren't registered with the googegroup so you'll need to subscribe to it separately.

I'm open to the DEEP_COPY_USERDATA_AND_CONTENTS change.  Sine we've already updating the SO version for the up coming 3.6.5 release a small tweak to the API like this will be fine for 3.6.5.  Just make the changes to the 3.6 branch and push a PR for it.

**Comment by AnyOldName3** [comment]
So I need to be on the mailing list and in the Google group?

**Comment by openscenegraph** [comment]
On Tue, 17 Dec 2019 at 13:29, Chris Djali <notifications@github.com> wrote:

> So I need to be on the mailing list and in the Google group?
>
Posts to the ML or the Group will be cross posted so you don't need  to
subscribe to both.  My recommendation would be to just register with the
Google group as you can use it via a mail client or via the browser forum
style.  All posts to the forum should appear on the ML.

Robert.

**Comment by AnyOldName3** [comment]
I'm already *in* the Google group, but there's no option to actually post or reply to anything. That's why I asked. I guess you've got something funky going on with permissions.

**Comment by openscenegraph** [comment]
Just had a look over the permissions, it looks like the defaults were for new members to not have posting permission.  I've changed this, you should be able to create topics and post now.
