### ISSUE TITLE
The example osgshadow running on intel card is failed

### ISSUE THREAD

**Issue by locobrain** [openscenegraph/OpenSceneGraph#847]
The example osgshadow running on intel card is failed. No shadow!

Intel HD 530

error message:
glValidateProgram FAILED "" id=1 contextID=0
infolog:
Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit

osgprerender OK

osgprerendercubemap OK

osgcubemap OK

**Comment by openscenegraph** [comment]
I suspect this is an Intel driver bug as that example works fine on other systems, including on an iCore7 I have in my google pixel chromebook.
