### ISSUE TITLE
Useof  FFmpeg plugin makes it so all readImage calls gets processed through it and not other plugins

### ISSUE THREAD

**Issue by mikeucfl** [openscenegraph/OpenSceneGraph#848]
I recently started playing with the FFmpeg plugin and noticed when I loaded a video through it all my successive readImage calls are handled by the FFmpeg plugin and don't allow other plugins to see if the format is for them (e.g. loading a jpeg will stop at ReaderWriterFFmpeg and not go to ReaderWriterJPEG). This seems to be due to this block of code in ReaderWriterFFmpeg.cpp

![image](https://user-images.githubusercontent.com/8254157/66857541-7ecaf680-ef55-11e9-94d1-1a82a5db86c3.png)

With the code now not checking isFormatAvailable, all image formats ffmpeg seem to be supported (regardless of what the plugin set using supportsExtension()). Is this the intended behavior?

**Comment by openscenegraph** [comment]
The follow commit just merged should address this issue (merged to 3.6 branch and master.)

https://github.com/openscenegraph/OpenSceneGraph/commit/4ebac62d05372d14ba8eef1bc652e2d773b375a5
