### ISSUE TITLE
No rule to make target IlmImf.dll, needed by osgPlugins-3.6.4/mingw_osgdb_exr.dll

### ISSUE THREAD

**Issue by Lord-Kamina** [openscenegraph/OpenSceneGraph#849]
I'm cross-compiling for mingw-w64; using the following command:

`cd '/opt/mxe/tmp-openscenegraph-i686-w64-mingw32.shared/OpenSceneGraph-OpenSceneGraph-3.6.4.build_' && 'i686-w64-mingw32.shared-cmake' '/opt/mxe/tmp-openscenegraph-i686-w64-mingw32.shared/OpenSceneGraph-OpenSceneGraph-3.6.4' -DCMAKE_CXX_FLAGS='-D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS' -DOSG_DETERMINE_WIN_VERSION=OFF -DPKG_CONFIG_EXECUTABLE='/opt/mxe/usr/bin/i686-w64-mingw32.shared-pkg-config' -DDYNAMIC_OPENSCENEGRAPH=ON -DBUILD_OSG_APPLICATIONS=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

This ends with the following output:

```
-- The following OPTIONAL packages have been found:

 * OpenGL
 * Freetype
 * ilmbase
 * Jasper
 * OpenEXR
 * LibXml2
 * GDAL
 * GTA
 * CURL
 * FFmpeg
 * GLIB
 * Threads
 * SDL2
 * RSVG
 * GIFLIB
 * JPEG
 * ZLIB
 * PNG
 * TIFF
 * Fontconfig

-- The following OPTIONAL packages have not been found:

 * EGL
 * Inventor
 * OpenCascade
 * COLLADA
 * FBX
 * LibVNCServer
 * DCMTK
 * GStreamer
 * DirectShow
 * SDL
 * Poppler-glib
 * GtkGl
 * DirectInput
 * NVTT
 * ZeroConf
 * LIBLAS
 * QuickTime

-- Configuring done
-- Generating done
```
But then it fails with the following error:

```
/opt/Xcode.app/Contents/Developer/usr/bin/make -f src/osgPlugins/exr/CMakeFiles/osgdb_exr.dir/build.make src/osgPlugins/exr/CMakeFiles/osgdb_exr.dir/build
make[4]: *** No rule to make target `/opt/mxe/usr/i686-w64-mingw32.shared/lib/libIlmImf.dll', needed by `bin/osgPlugins-3.6.4/mingw_osgdb_exr.dll'.  Stop.
```

Now, if I just open that `build.make` or if I run ccmake I can see that IlmImf is obviously pointing to that location; and the file IS there...

```
$ ls -l /opt/mxe/usr/i686-w64-mingw32.shared/lib/libIlmImf.dll
lrwxr-xr-x  1 Koji  admin  17 Oct 19 09:31 /opt/mxe/usr/i686-w64-mingw32.shared/lib/libIlmImf.dll -> libIlmImf-2_4.dll
```

So, what gives?

**Comment by Lord-Kamina** [comment]
I've found the issue; both IlmBase and IlmImf are installing dlls to `bin` and creating (broken) symlinks in `lib`

**Comment by Lord-Kamina** [comment]
I've confirmed this to be the issue and submitted a PR over at the openexr repo, so you can close this.

**Comment by dujinyu** [comment]
hello, how can i install the not found packages on ubuntu18.04? sudo apt install xxx, but i don't know the package name.
