### ISSUE TITLE
drop dependency on gtkglext

### ISSUE THREAD

**Issue by okias** [openscenegraph/OpenSceneGraph#850]
This library is pretty ancient developed for GTK+ 2.x.
I found it today only in CMakeModules/FindGtkGl.cmake , is it required somewhere?

**Comment by openscenegraph** [comment]
The CMakeModules/FindGtkGl.cmake is associated with the OpenSceneGaph/examples/osgviewerGTK example.  This was contributed many years ago, I don't personally use it, so don't know whether it still works.  It's just a compile option so if you have gtk 2.0 installed then there shouldn't be any problem.

I just checked my Kubuntu 18.04 system and libgtk2.0-dev is available so I'd guess that it's still possible to get working.

Have you seen an issue that needs resolving?
