### ISSUE TITLE
A question about the example osgEmscripten 

### ISSUE THREAD

**Issue by For-thewin** [openscenegraph/OpenSceneGraph#863]
I just follow the guide of the emscripten.cmake.

# cmake -DCMAKE_TOOLCHAIN_FILE=<EmscriptenRoot>/cmake/Modules/Platform/Emscripten.cmake
#       -DCMAKE_BUILD_TYPE=<Debug|RelWithDebInfo|Release|MinSizeRel>
#       -G "Unix Makefiles" (Linux and OSX)
#       -G "MinGW Makefiles" (Windows)
#       <path/to/CMakeLists.txt> # Note, pass in here ONLY the path to the file, not the filename 'CMakeLists.txt' itself.

But i get a error which is "error: undefined symbol: pthread_attr_getstacksize". Even though i can add "-s ERROR_ON_UNDEFINED_SYMBOLS = 0" to the CMakeLists.txt which generates a correct .html file, i still want to solve the warning "undefined symbol: pthread_attr_getstacksize". 

Is there something question about the emscripten compiler or our source code in the .cpp file?

**Comment by openscenegraph** [comment]
I don't  have any experience with Emscripten myself by perhaps the author of this work Michael (@kornerr) might have ideas what might be amiss?

**Comment by kornerr** [comment]
@For-thewin, such warnings mean there is code that references such functions, however, in the case of Emscripten we only use single thread, so pthreads related code is still present in OSG, however, is unused. I personally tolerate such warnings.
You might find a way to #undef code paths that reference pthreads, then you will be warning-free.
