### ISSUE TITLE
Support OpenXR for VR

### ISSUE THREAD

**Issue by paju1986** [openscenegraph/OpenSceneGraph#873]
Hello.

Now that we finally have a standar for VR OpenXR https://en.wikipedia.org/wiki/OpenXR it would be a good idea to implement it so we can use VR with any HMD.

**Comment by openscenegraph** [comment]
This is most suited to an 3rd party NodeKit built ontop of the OSG, rather than part of the core OSG.  This is he way that previous VR add-ons have functioned.

The best place to discuss this is on the osg-users, as the github Issue tracker is for bugs rather than feature request.

    https://groups.google.com/forum/#!forum/osg-users
