### ISSUE TITLE
Bug in Text/Text3D while using VAO in the current 3.6.5

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#881]
Please do not make 3.6.5 release.
I will send PR soon!

**Comment by valid-ptr** [comment]
See  #882

**Comment by openscenegraph** [comment]
Could you explain how to reproduce the problem?

**Comment by valid-ptr** [comment]
To reproduce the problem you need to create
osg::Viewer::Viewer with StatsHandler (important!), add osgText::Text to empty scene root.
Force every (important!) Drawable to use VBO and VAO.
You will see broken text (only first triangle visible)

The bug can be reproduced another way...

But the reason is osgText::Text/Text3D "GL initialization".
NOTE: There is no correct **compileGLObjects** function in Text and Text3D like in osg::Geometry.


After applying #882 - the problem disappears.

**Comment by openscenegraph** [comment]
Thanks for the description of how to recreate the problem. Do you have the code you describe?  This would be useful as I might write some code and not reproduce the problem and not know if I recreate the test wrongly or that there is something else going on.

**Comment by valid-ptr** [comment]
No simple example code, sorry.
I've investigated and fixed this problem inside huge program (not only on c++)
Checked gltrace (apitrace) and found the solution.

PS
The best solution will be to write correct **compileGLObjects** functions for Text and Text3D maybe.

**Comment by openscenegraph** [comment]
I have tried to recreate a problem, so far unsuccessful, but then I'm have to guess what you mean.

This is what I've tried so far.

`#include <osg/io_utils>
#include <osgDB/ReadFile>
#include <osgViewer/ViewerEventHandlers>
#include <osgGA/TrackballManipulator>
#include <osgGA/StateSetManipulator>


int main(int argc, char** argv)
{
    osg::ArgumentParser arguments(&argc,argv);

    osgViewer::Viewer viewer;

    // add the stats handler
    viewer.addEventHandler(new osgViewer::StatsHandler);

    osg::ref_ptr<osgText::Text> text = new osgText::Text;
    text->setText("This is my test");
    text->setFont("times.ttf");
    text->setAxisAlignment(osgText::Text::XZ_PLANE);

    if (arguments.read("--vbo"))
    {
        text->setUseVertexBufferObjects(true);
    }

    if (arguments.read("--vao"))
    {
        text->setUseVertexBufferObjects(true);
        text->setUseVertexArrayObject(true);
    }

    if (arguments.read("--no-vbo"))
    {
        text->setUseVertexArrayObject(false);
        text->setUseVertexBufferObjects(false);
    }
    if (arguments.read("--no-vao"))
    {
        text->setUseVertexArrayObject(false);
    }

    OSG_NOTICE<<"VertexBufferObjects "<<text->getUseVertexBufferObjects()<<std::endl;
    OSG_NOTICE<<"VertexArrayObject "<<text->getUseVertexArrayObject()<<std::endl;


    viewer.setSceneData(text);

    return viewer.run();
}
`

**Comment by openscenegraph** [comment]
I can't determine the appropriate fix without knowing exactly what is going wrong,

**Comment by valid-ptr** [comment]
https://github.com/openscenegraph/OpenSceneGraph/blob/8011d9414b7c3b6e8482be50d4b4e85dacea26dc/src/osg/Geometry.cpp#L878
https://github.com/openscenegraph/OpenSceneGraph/blob/8011d9414b7c3b6e8482be50d4b4e85dacea26dc/src/osg/Geometry.cpp#L879

The same must be in Text/Text3D

**Comment by valid-ptr** [comment]
Summing up all, there is a leak of
```
glBindBuffer(GL_ARRAY_BUFFER_ARB, 0);
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER_ARB, 0);
```
(first call etc. when **requiresSetArrays**)
in Text/Text3D when using VBO + VAO on the OpenGL stack

**Comment by openscenegraph** [comment]
On Mon, 6 Jan 2020 at 12:26, Konstantin S. Matveyev <
notifications@github.com> wrote:

> Summing up all, there is a leak of
>
> glBindBuffer(GL_ARRAY_BUFFER_ARB, 0);
> glBindBuffer(GL_ELEMENT_ARRAY_BUFFER_ARB, 0);
>
> (first call etc. when *requiresSetArrays*)
> in Text/Text3D when using VBO + VAO on the OpenGL stack
>
I am starting to understand where you are coming from.  Would like to
reproduce the problem though as right now I'm not able to verify any
problem or fix.

The PR you wrote doesn't explicitly call  glBindBuffer(GL_ARRAY_BUFFER_ARB,
0); etc. but should call these via the vas->unbindVertexBufferObject();
call so happy with your original PR code.  Do you think something else
should be used now?

I looked at TextBase::compileGLObjects() but didn't spot a way relate this
to the Text::drawImplementation() and Text3D::drawImplementation(), I'm
still getting around what is going on though.

Robert.

**Comment by valid-ptr** [comment]
> The PR you wrote doesn't explicitly call glBindBuffer(GL_ARRAY_BUFFER_ARB, 0); etc. but should call these via the vas->unbindVertexBufferObject(); call so happy with your original PR code. Do you think something else should be used now?

No)
**vas->unbindVertexBufferObject() ==  glBindBuffer(GL_ARRAY_BUFFER_ARB, 0);**
**vas->unbindElementBufferObject() ==  glBindBuffer(GL_ELEMENT_ARRAY_BUFFER_ARB, 0);**

What do you think about
**Text**::compileGLObjects()
**Text3D**::compileGLObjects()
? ;)

I'll try to make an example, but it can take time. 

Konstantin.

**Comment by openscenegraph** [comment]
On Mon, 6 Jan 2020 at 13:18, Konstantin S. Matveyev <
notifications@github.com> wrote:

> The PR you wrote doesn't explicitly call glBindBuffer(GL_ARRAY_BUFFER_ARB,
> 0); etc. but should call these via the vas->unbindVertexBufferObject();
> call so happy with your original PR code. Do you think something else
> should be used now?
>
> No)
> *vas->unbindVertexBufferObject() == glBindBuffer(GL_ARRAY_BUFFER_ARB, 0);*
> *vas->unbindElementBufferObject() ==
> glBindBuffer(GL_ELEMENT_ARRAY_BUFFER_ARB, 0);*
>
> What do you think about
> *Text*::compileGLObjects()
> *Text3D*::compileGLObjects()
> ? ;)
>
There is quite a bit of code in the drawImplementation() that one would
need to pick from what parts are appropriate to compile.  If it's not
complete critical to have a dedicated compileGLObjects(), perhaps a
fallback would be to call the drawImplementation() from the
TextBase::compileGLObjects().

> I'll try to make an example, but it can take time.
>
Do you have an idea of what would be required to reproduce the problem?

Robert.

**Comment by valid-ptr** [comment]
Robert!

Try to run your example with
**OSG_VERTEX_BUFFER_HINT=VAO** _./a.out_ **--vao**
You will be surprised)

Just press 's' key

On macos I have (with and without PR) and other strange behaviours like SEGFAULT

`bash-3.2$ ./a.out
Fontconfig warning: ignoring UTF-8: not a valid region tag
VertexBufferObjects 1
VertexArrayObject 0
Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)
Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)
Segmentation fault: 11
`

**Comment by openscenegraph** [comment]
On Mon, 6 Jan 2020 at 13:51, Konstantin S. Matveyev <
notifications@github.com> wrote:

> Try to run your example with
>
> *OSG_VERTEX_BUFFER_HINT=VAO* *./a.out* *--vao*
> You will be surprised)
>
> Just press 's' key
>
> On macos I have (with and without PR) and other strange behaviours like
> SEGFAULT
>
> bash-3.2$ ./a.out Fontconfig warning: ignoring UTF-8: not a valid region
> tag VertexBufferObjects 1 VertexArrayObject 0 Warning: detected OpenGL
> error 'invalid operation' at after RenderBin::draw(..) Warning: detected
> OpenGL error 'invalid operation' at after RenderBin::draw(..) Segmentation
> fault: 11
>
I tried the above suggestion and it still works fine on my Linux system
with the example compiling against OSG-3.6 head.

Robert.

**Comment by valid-ptr** [comment]
I've compiled OSG-3.6 head on Macos 10.14.4 (macbook pro 2017) with the simplest build-options:
only CMAKE_BUILD_TYPE and CMAKE_INSTALL_PREFIX specified.

I've used OSG-3.6 on macos with OPENGL_PROFILE=GL3 only. It was not so bad.

Strange

**Comment by valid-ptr** [comment]
Here is an example (everything working with PR, text broken without PR):

```

#include <osg/io_utils>
#include <osgDB/ReadFile>
#include <osgViewer/ViewerEventHandlers>
#include <osgGA/TrackballManipulator>
#include <osgGA/StateSetManipulator>

namespace {
	class VisitorVAO : public osg::NodeVisitor
	{
	public:
		VisitorVAO()
		:	osg::NodeVisitor(osg::NodeVisitor::TRAVERSE_ALL_CHILDREN)
		{
		}

		void apply(osg::Drawable& aDrawable)
		{
			std::cout << "Applying " << aDrawable.getName() << std::endl;
			aDrawable.setUseVertexBufferObjects(true);
			aDrawable.setUseVertexArrayObject(true);
		}
	};

	class StatsHandlerExt : public osgViewer::StatsHandler
	{
	public:
		StatsHandlerExt(osgViewer::Viewer& aViewer)
		{
			setUpHUDCamera(&aViewer);
			setUpScene(&aViewer);

			VisitorVAO visitor;
			_camera->accept(visitor);	// NOTE: Try to comment out this line (=> will work without patch)
		}
	};
}

int main(int argc, char** argv)
{
	osg::ArgumentParser arguments(&argc,argv);

	osgViewer::Viewer viewer;

	viewer.realize();					// NOTE: can be commented out

	// add the stats handler
	viewer.addEventHandler(new StatsHandlerExt(viewer));

	osg::ref_ptr<osgText::Text> text = new osgText::Text;
	text->setText("This is my test");
	text->setFont("times.ttf");
	text->setAxisAlignment(osgText::Text::XZ_PLANE);

	if (arguments.read("--vbo"))
	{
		text->setUseVertexBufferObjects(true);
	}

	if (arguments.read("--vao"))
	{
		text->setUseVertexBufferObjects(true);
		text->setUseVertexArrayObject(true);
	}

	if (arguments.read("--no-vbo"))
	{
		text->setUseVertexArrayObject(false);
		text->setUseVertexBufferObjects(false);
	}
	if (arguments.read("--no-vao"))
	{
		text->setUseVertexArrayObject(false);
	}

	OSG_NOTICE<<"VertexBufferObjects "<<text->getUseVertexBufferObjects()<<std::endl;
	OSG_NOTICE<<"VertexArrayObject "<<text->getUseVertexArrayObject()<<std::endl;

	viewer.setSceneData(text);

	return viewer.run();
}

```

PS.
There was segfault on Macos with forced VAO on compatibility profile. I think it is normal ;)

**Comment by openscenegraph** [comment]
With the addition of the custom StatsHandler that forces on VAO I now see the the main text rendering incorrectly, no crash, but band rendering is good enough for me to QA bug fixes.

**Comment by openscenegraph** [comment]
I have checked in the following that addresses the glitch I'm see with the latest incarnation of the above test program.  This commit is in OSG-3.6 branch and master.

https://github.com/openscenegraph/OpenSceneGraph/commit/605821e655d97b7ad5ab6098b3ec26e2f9ad2ff7
