### ISSUE TITLE
output texture path problem

### ISSUE THREAD

**Issue by longhuan2018** [openscenegraph/OpenSceneGraph#886]
When using osgconv, the output path of the texture is always relative to the current path, not the output file path.
I don't think this setup is reasonable. I think if the texture name is relative path, then it should be relative to the node file.
Although you can use the setCurrentWorkingDirectory method to set the current directory to the directory where the node file is located, this method will have problems in multi-threaded mode.

**Comment by longhuan2018** [comment]
I searched the whole code where writeImageFile was called,
![image](https://user-images.githubusercontent.com/8551701/71788864-57ba2780-3061-11ea-8127-b454335f1aa8.png)
I found that the formats are mainly osg, osgb, ive, osgjs, obj, and the texture needs to be saved when saving.

**Comment by longhuan2018** [comment]
![image](https://user-images.githubusercontent.com/8551701/71788917-e464e580-3061-11ea-8265-f37f8c0a8f08.png)
These files are needed when exporting to osg format
``
osgWrappers\deprecated-dotosg\osg\Texture1D.cpp
osgWrappers\deprecated-dotosg\osg\Texture2D.cpp
osgWrappers\deprecated-dotosg\osg\Texture2DArray.cpp
osgWrappers\deprecated-dotosg\osg\Texture3D.cpp
osgWrappers\deprecated-dotosg\osg\TextureCubeMap.cpp
osgWrappers\deprecated-dotosg\osg\TextureRectangle.cpp
osgWrappers\deprecated-dotosg\osgTerrain\ImageLayer.cpp
``
They use the same code
``
std::string fileName = texture.getImage()->getFileName();
            if (fw.getOutputTextureFiles())
            {
                if (fileName.empty())
                {
                    fileName = fw.getTextureFileNameForOutput();
                }
                osgDB::writeImageFile(*texture.getImage(), fileName);
            }
``
We can analyze this code to know that if getImage ()-> getFileName () records the relative path, then when calling osgDB :: writeImageFile (* texture.getImage (), fileName), its actual output path is relative With the current working path.
There will be a problem here. If the relative path contains a directory, such as ./test/test.jpg, and the directory named test does not exist in the current path, writeImageFile will fail because the writeImageFile method will not Path to create a nonexistent directory.

**Comment by longhuan2018** [comment]
The osgb format is relatively troublesome because its texture output is written in osgDB :: OutputStream.
```
std::string imageFileName = img->getFileName();
if ( decision==IMAGE_WRITE_OUT || _writeImageHint==WRITE_EXTERNAL_FILE )
{
     if (imageFileName.empty())
     {
          OSG_NOTICE<<"Empty Image::FileName resetting to image.dds"<<std::endl;
          imageFileName = "image.dds";
     }

     bool result = osgDB::writeImageFile( *img, imageFileName );
     OSG_NOTICE << "OutputStream::writeImage(): Write image data to external file " << imageFileName << std::endl;
     if ( !result )
     {
          OSG_WARN << "OutputStream::writeImage(): Failed to write " << img->getFileName() << std::endl;
     }
}
```
Then the question comes, how to get the output node file path from osgDB :: OutputStream.
A member variable _out exists in osgDB :: OutputStream, Its class is osgDB :: OutputIterator, There is also a std :: ostream member variable in osgDB :: OutputIterator. This variable is ultimately used for writing files, so if we can get the save path from it, we can perform subsequent conversions.
```
class OSGDB_EXPORT OutputIterator : public osg::Referenced
{
public:
    OutputIterator() : _out(0), _outputStream(0), _supportBinaryBrackets(false) {}
    virtual ~OutputIterator() {}

    void setStream( std::ostream* ostream ) { _out = ostream; }
    std::ostream* getStream() { return _out; }
```
I do n’t know how to get the file path from std :: ostream. Fortunately, when OpenSceneGraph saves osgb, it calls osgDB :: ofstream, so if we add a method to osgDB :: ofstream to record the file Path, can it be solved?
Some code in ReaderWriterOSG2 :
```
virtual WriteResult writeNode( const osg::Node& node, const std::string& fileName, const Options* options ) const
{
        WriteResult result = WriteResult::FILE_SAVED;
        std::ios::openmode mode = std::ios::out;
        osg::ref_ptr<Options> local_opt = prepareWriting( result, fileName, mode, options );
        if ( !result.success() ) return result;

        osgDB::ofstream fout( fileName.c_str(), mode );
        if ( !fout ) return WriteResult::ERROR_IN_WRITING_FILE;

        result = writeNode( node, fout, local_opt.get() );
        fout.close();
        return result;
}
```
Add a getFileName method to osgDB :: ofstream
```
class ofstream : public std::ofstream
{
public:
    OSGDB_EXPORT ofstream();
    OSGDB_EXPORT explicit ofstream(const char* filename,
        std::ios_base::openmode mode = std::ios_base::out);
    OSGDB_EXPORT ~ofstream();

    void OSGDB_EXPORT open(const char* filename,
        std::ios_base::openmode mode = std::ios_base::out);

	std::string OSGDB_EXPORT getFileName() const;

protected:
	std::string _filename;
};

std::string ofstream::getFileName() const
{
     return _filename;
}
```
In osgDB :: OutputStream, add code that converts texture path to absolute path
```
std::string imageFileName = img->getFileName();
if ( decision==IMAGE_WRITE_OUT || _writeImageHint==WRITE_EXTERNAL_FILE )
{
     if (imageFileName.empty())
     {
          OSG_NOTICE<<"Empty Image::FileName resetting to image.dds"<<std::endl;
          imageFileName = "image.dds";
     }
			
     std::string fullPath = imageFileName;
     if (!osgDB::isAbsolutePath(fullPath))
     {
          ofstream* os = dynamic_cast<ofstream*>(_out->getStream());
          if( os!=NULL && !os->getFileName().empty() )
               fullPath = osgDB::concatPaths(osgDB::getFilePath(os->getFileName()), fullPath);
     }
     osgDB::convertFileNameToNativeStyle(fullPath);
     osgDB::makeDirectoryForFile(fullPath);
     bool result = osgDB::writeImageFile( *img, fullPath);
     OSG_NOTICE << "OutputStream::writeImage(): Write image data to external file " << imageFileName << std::endl;
      if ( !result )
     {
          OSG_WARN << "OutputStream::writeImage(): Failed to write " << img->getFileName() << std::endl;
     }
 }
```

**Comment by longhuan2018** [comment]
All modifications are in PR #884

**Comment by openscenegraph** [comment]
For the .osg related issues, the way to address them is to not use .osg as an output format, it's been deprecated for 9 years, you should not be using it for an output format.

The issues you have with using osgconv and .osgb/.osgt/,osgx is a concern.  How best to resolve it I haven't worked out yet.  Adding code all over the place to support a specific local features is inappropriate, these issues can very likely be resolved without changing multiple files.

Could you provide a test model and osgconv instructions that reproduce the issue you see so we can reproduce it at our end and step through what the most appropriate solution is.  Thanks.

**Comment by longhuan2018** [comment]
Here is a test data and command line parameters.
[cow.zip](https://github.com/openscenegraph/OpenSceneGraph/files/4043435/cow.zip)
```
osgconvd.exe -O WriteImageHint=WriteOut C:\cow.osgb c:\cow.osgt
```
![image](https://user-images.githubusercontent.com/8551701/72117337-44bc9580-3388-11ea-952c-402d2e51a5ee.png)
**Note: Make sure that there is no directory named Images in the current path of the command line**

**Comment by openscenegraph** [comment]
To resolve this Issue I have added automatic directory creation when required for the native serializer and obj plugin:

https://github.com/openscenegraph/OpenSceneGraph/commit/457d12d9b2318abe30c557de91ab90baffec5d9a

**Comment by HappyKuTou** [comment]
I still don't know how to generate jpg and obj in the same directory
