### ISSUE TITLE
DepthPartition

### ISSUE THREAD

**Issue by Realitian** [openscenegraph/OpenSceneGraph#893]
Hi @robertosfield,
I have some problem(I guess it as depth issue) on rendering huge scene(solar system) using osg.
But I found your depth partitioning can resolve it and it uses for rendering huge scene.
I tried to understand your internal implementation of depth partitioning using slave camera, but I was difficult to understand it clearly.
Can you explain how to works depth partitioning shortly?
Or any helpful reference is good for me.
Thank you in advance.
Cheers!

**Comment by openscenegraph** [comment]
The githib Issues for the OSG project is for bug reports.. Could you please post general API/implementation questions on the osg-users googlegroup or ML, this way any discussions can be easily found and contributed to by others.  

    https://groups.google.com/forum/#!forum/osg-users
