### ISSUE TITLE
Nothing is rendered when loading OBJ file using OSG 3.6.4 under linux xubuntu 18.04 gcc 8.3

### ISSUE THREAD

**Issue by mselim** [openscenegraph/OpenSceneGraph#896]
I am trying to load obj file using osg::Node* obj_node = osgDB::readNodeFile("/path/to/objfile");

If I try to add obj_node to my scenegraph , nothing is rendered. Upon further inspection using osg::NodeVisitor and applying it to the obj_node and trying to print info about geodes and geometries, I found that, everything is corresponds to the mesh of the obj file, i.e. I got correct no. of vertices, normals from the several osg::Geometry nodes that are present after loading obj file. That means the hierarchy of nodes geometries and vertices are correct, but for some strange reason it's not being rendered. 

Instead trying to render osgDB::readNodeFile seems to work fine on the same obj file using osg 3.6.4 on Windows 10.

The computer has intel hd 620 Graphics card.

Also it's worth noting that the previous scenario works fine with the exact mesh in STL format on the same linux and hardware.

I've tried many other obj files from https://people.sc.fsu.edu/~jburkardt/data/obj/obj.html
And I got the same result with different OBJ files, nothing is being rendered, but the loading is occurred correctly.

**Comment by openscenegraph** [comment]
This is mostly like a Intel driver bug.  Rather than provide a link to a whole list of different .obj files, could you provide a specific file that doesn't work for you.  

I don't have an Intel card but I do I have Kubuntu 18.04 so can test the general handling of the .obj file.

**Comment by mselim** [comment]
- I've downloaded FreeCAD on the same computer, and I was able to load the obj normally and have it rendered. I know that doesn't deny nor confirm the possibility of an intel driver bug, might be the problem.
- for a certain example to try, cessna.obj  (https://people.sc.fsu.edu/~jburkardt/data/obj/cessna.obj) and it's material file vp.mtl (https://people.sc.fsu.edu/~jburkardt/data/obj/vp.mtl)

**Comment by mp3butcher** [comment]
trye `export LANG=C `

**Comment by openscenegraph** [comment]
I have tried the cessna.obj model you linked too under Kubuntu 18,04 with
the 3.6 branch and it loads and renders without any issues.  I have
converted the cessna.obj to .osgt and inspected the file and it looks valid
as far as I can tell.

It might be that the default way that the OSG is rendering the model (using
VBO's for this ,obj model) is triggering a Intel driver bug, and FreeCAD is
rendering it using a different OpenGL code path. This is only a guess
though.

As the issue you have is something we aren't able to reproduce, you'll need
to take the lead on investigate in what circumstances you are seeing
failures. What I'd recommend doing is:

  1) Test osgviewer with the various models in OpenSceneGraph-Data test
dataset.
  2) Run osg examples like osggeometry and other examples to see whether
basic things are working.
  3) Look at the console for any GL errors reported.
  4) If you have other systems available test the same version of the OSG
and the same test dataset to see whether then issues exist elsewhere or are
present in different ways.

**Comment by openscenegraph** [comment]
@mp3butcher I have just checked the obj plugin and the readNode(filename...) code path doesn't setting the local to classic before parsing for all the relevant code paths in the obj plugin so I've add setting of the local of the MTL and OBJ reading istream. 

https://github.com/openscenegraph/OpenSceneGraph/commit/25afb086ef1012cb26cd4f3b2d1569ddb9d1739d

This fix is checked into master and the 3.6 branch

**Comment by mselim** [comment]
I've just re-checked with this fix (using 3.6.5 or directly pulling from master), unfortunately it's not working, but I've managed to know why it's not reading correctly the obj file, it's because environment variable LC_ALL wasn't set by default, it was (this includes almost all ubuntu distros) to nothing (empty). To overcome this issue you have to export on linux your environment variable LC_ALL = POSIX or en_US.UTF-8. I think because I do use a linux distro ubuntu with local set to a european country which floating point decimal mark (".") is different from US (","). That's why the parsing of obj not able to read the vertices floating points values correctly because they're written in us comma separated style.

**Comment by openscenegraph** [comment]
I surprised you still need to set the the local as there is a setting of
local to classic() in the plugin:

https://github.com/openscenegraph/OpenSceneGraph/commit/b063f510c168a05cede7cd4b1b3243b08e28c7cb

Could you double check that you have this in your OSG version, if so have a
look at the code paths to see if for your usage it's not being set.
