### ISSUE TITLE
3.6.5-rc1 - Lots of tabs mixed with spaces in cmake files

### ISSUE THREAD

**Issue by solvingj** [openscenegraph/OpenSceneGraph#897]
I suggest someone do a replacement of tabs with spaces in all the cmake files.

**Comment by openscenegraph** [comment]
Feel free to do this replacement if you feel bothered by it and generate a PR for it.  Dev wise for the 3.6.5 release work I'll be focusing on actual bugs and build issues rather than window dressing.
