### ISSUE TITLE
Does OSG have a REST API for usage with OSGjs ?

### ISSUE THREAD

**Issue by AaronNGray** [openscenegraph/OpenSceneGraph#90]
I am wondering whether OpenSceneGraph can be used as a REST server over the web for OSGjs.org for the https://github.com/cedricpinson/osgjs project ? Or whether there is a better route for supporting OSGjs over the web from a cloud based or centralized database ?

**Comment by jtorresfabra** [comment]
@AaronNGray OpenSceneGraph is a C++ high performance 3D graphics toolkit. Nothing to do with a REST server. You can probably better do your question in the osgjs users list. 
I'll be glad to answer you there.
