### ISSUE TITLE
occlusion query  api variations across osg version

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#901]
Just to mention that OcclusionQueryNode api have changed 3 times (3.4,3.6,master)
Perhaps recent changes made by @dan-t  to master should be merged with 3.6 ...

**Comment by Capostrophic** [comment]
> Perhaps recent changes made by @dan-t to master should be merged with 3.6 ...

And break backward compatibility with existing 3.6.x applications? So much for bug fix releases.

**Comment by openscenegraph** [comment]
Bug fixes and backwards of API is highly desirable but isn't always possible.

@mp3butcher & @dan-t, if there are changes that are in master and would be appropriate then please generate a PR for them. Thanks.

**Comment by mp3butcher** [comment]
@dan-t @openscenegraph 
https://github.com/openscenegraph/OpenSceneGraph/pull/902

**Comment by openscenegraph** [comment]
Merged, thanks.
