### ISSUE TITLE
Messages of missing functionality when using GL3 profile

### ISSUE THREAD

**Issue by DieSlower** [openscenegraph/OpenSceneGraph#905]
I built OSG3.6.5 rc2 with GL3 profile enabled
When I try to use it for my own projects, or when I run the osgsimplegl3 example every frame I get the following messages in console:
Warning: TexGen::apply(State&) - not supported.
Warning: Material::apply(State&) - not supported.

Since a person should know what is deprecated in the GL3 profile, and since these messages only kill performance, would it be possible to disable them if you specifically enable GL3 profile and disable the fixed function pipeline?

So Material.cpp on line 444 would change from:
```
void Material::apply(State& state) const
{
    OSG_NOTICE<<"Warning: Material::apply(State&) - not supported."<<std::endl;

    state.Color(_diffuseFront.r(), _diffuseFront.g(), _diffuseFront.b(), _diffuseFront.a());
}
```

to:
```
void Material::apply(State& state) const
{
#ifndef OSG_GL3_AVAILABLE
	OSG_NOTICE << "Warning: Material::apply(State&) - not supported." << std::endl;
#endif
	 
    state.Color(_diffuseFront.r(), _diffuseFront.g(), _diffuseFront.b(), _diffuseFront.a());
}
```

and TexGen.cpp on line 128 would go from:
```
#else
    OSG_NOTICE<<"Warning: TexGen::apply(State&) - not supported."<<std::endl;
#endif
```
to:
```
#else
#ifndef OSG_GL3_AVAILABLE
		OSG_NOTICE<<"Warning: TexGen::apply(State&) - not supported."<<std::endl;
#endif
#endif
```

**Comment by openscenegraph** [comment]
The messages are there to tell to you what needs to be removed from your scene graph for it to work properly and efficiently.

**Comment by DieSlower** [comment]
Materials are part of normal geometry file formats, like the OBJ format or the modern FBX. OSG reads these materials, even takes them into the .osgb files but instead of letting the user handle them in a shader tries to still use them in the old glMaterial functions. 
So materials should not be removed from the scenegraph, they should be left for the user to use with shaders if the user wants that. And if the user selects GL3 profile, that is the modern functionality that should be expected. Not the deprecated use of glMaterial. 
In modern shaders the varied part of a material is in the texture that is passed to the shader, and for efficiency, if the data is the same throughout it is passed through a int or float value which saves time on data upload. So materials are still very relevant, they are just used in a different way in GL3 and GL4.

**Comment by openscenegraph** [comment]
osg::Material has to be substituted or adapted to map to OSG provided
uniforms as is done in OSG master. The 3.6 branch won't attempt to tackle
this type of functionality.

**Comment by DieSlower** [comment]
So as of now, there is no way to pass the model material data in OSG 3.6 using modern OpenGL and the OSG GL3 profile?
Is this also a problem with textures? I noticed that osgsimplegl3 does not texture its model. Is that also impossible right now? Does this functionality exist on the master?

**Comment by mp3butcher** [comment]
if you're doing modern GL you shouldn't have osg::Material in your scengraph...I don't understand your issue

**Comment by DieSlower** [comment]
The issue is that materials can still be used in modern OpenGL if you write your shader to take care of them and pass them in as uniforms. In some cases it is more efficient than to use a 2x2 texture, or some other trick. All graphics formats from new to old (OBJ, FBX) still have materials in them. When they are converted to osgb or osgt osg::Material gets created by default in the scene. 

So since osg::Material still gets created, when GL3 profile is enabled, osg::Material should either not be read, giving the user a warning that it is ignored (warning, not a notice at every frame). In this case, it might be better to just fix the osgb/osgt converter and not create osg::Material when the conversion happens(under GL3 profile) or, it should be passed in by a uniform or a bonded buffer so the shader can make use of it if needed. 

In modern OpenGL we obviously don't use glMaterial, that got deprecated, but we still do use materials. They are more custom from case to case some are PBR, some are a bunch of textures and values, some are pure textures, and all are shader based, but the geometry formats, and most modeling programs like Maya and 3Ds Max did not remove those values. The materials just became more complex. So now if you look at "Standard" material in 3Ds Max you will see that both are configured, textures, and colors(old type materials). They are both exported and can be used still, if they are properly passed on to the shader. If for example you make a material with a diffuse color and a diffuse texture, then the correct result on the screen would be the combination of the two. If you set a color but no texture, then the single value will set the diffuse color for the entire model. All of that off course will be shader controlled.

**Comment by mp3butcher** [comment]
> So since osg::Material still gets created, when GL3 profile is enabled, osg::Material should either not be read, giving the user a warning that it is ignored (warning, not a notice at every frame). In this case, it might be better to just fix the osgb/osgt converter and not create osg::Material when the conversion happens(under GL3 profile) or, it should be passed in by a uniform or a bonded buffer so the shader can make use of it if needed.
>
I think both solution are a nono removing Material at loading  or taking a choice on a particular conversion would prevent custom conversion
 
> In modern OpenGL we obviously don't use glMaterial, that got deprecated, but we still do use materials. They are more custom from case to case some are PBR, some are a bunch of textures and values, some are pure textures, and all are shader based, but the geometry formats, and most modeling programs like Maya and 3Ds Max did not remove those values. The materials just became more complex. So now if you look at "Standard" material in 3Ds Max you will see that both are configured, textures, and colors(old type materials). They are both exported and can be used still, if they are properly passed on to the shader. If for example you make a material with a diffuse color and a diffuse texture, then the correct result on the screen would be the combination of the two. If you set a color but no texture, then the single value will set the diffuse color for the entire model. All of that off course will be shader controlled. So in many cases it is more efficient to send up a single float or int instead of a 2x2 texture for color variance.

osg have had a lot of backward compat issues because of taking a choices of implementation that require constant maintenance. 
From my perspective osg is more a meta engine like vulkan than a 3D engine.
3D Engines are shiny blingbling because they implement the last fashion policy.
You can't make one out of osg

**Comment by mp3butcher** [comment]
i fixed my last message :/

**Comment by DieSlower** [comment]
> I think both solution are a nono removing Material at loading or taking a choice on a particular conversion would prevent custom 

What about just silencing the Warning message, or making it log as a warning instead of a notice? Without implementing some kind of a fix, it is basically a guarantee that if OSG is built with GL3 profile, it will not work out of the box without spamming you with warnings. 

> osg have had a lot of backward compat issues because of taking a choices of implementation that require constant maintenance.
> From my perspective osg is more a meta engine like vulkan than a 3D engine.
> 3D Engines are shiny blingbling because they implement the last fashion policy.
> You can't make one out of osg

Sure, OSG is bare-bones, which is why it is fast(to a point), and why I've been using it for over 10 years, but it is still on GL2, while the world is on GL4. A basic engine in its native form should be able to load up a model that has a texture or color. Unless GL3 profile is experimental, and not a truly working profile in OSG, the engine should do this basic thing or allow the user to somehow implement it by giving them all the loaded up data without flooding the screen with notice warnings. 

On the other hand with OGL3 and OGL4 there were a lot of improvements in rendering, but it seems (unless I am misunderstanding something) that when we switch OSG to GL3, OSG is still trying to use outdated GL methods and deprecated gl functions?
One of my teammates extended/modified the draw implementation and camera implementation of OSG and was able to improve performance by more than a magnitude using modern techniques. One of the biggest things is that OSG does not optimize draw calls, resulting in thousands of GPU draws instead of one or two. From what I was told it wasnt a huge change, and did not break any of the OSG functionality, but it did get our VR development from 15fps to over 200fps. Are there any plans to modernize OSG for GL3 profile, or maybe make a GL4 profile with all the current functionality?

**Comment by mp3butcher** [comment]
(I've corrected my last msg : You can make you own out of osg.. typo error)
If you have mod to osg to submit, PR for them, i would be glad to review what i can .
As I'm practicing, i'm doing DC optimisation as a scenegraph transformation  but if you have something else to propose i'm very interested.
GL2 have semantics so there was ffp and semantics
Since GL3,  there's no semantic anymore, the only thing osg (as a meta engine) can do is to preserve old ffp behavior but nothing more

**Comment by openscenegraph** [comment]
The scene graph that you use is the responsibility of the application developer, it's not the OSG's role to go fix problems in the scene graph.  If you build your scene graph correctly then the bottlenecks you are seeing will likely disappear without any modifications required for the OSG.  A 15fps to 200fps change screams that you have a really poorly optimized scene graph.  This Issue is the not the place to teach scene graph optimization so I'll not go into details, please looks to the osg-users archives or post a question.

In the end if you want to really optimize your application OpenGL and the OSG just are not the tool to use, you need to move to Vulkan, this is where the VSG comes in, which is why this is where my main focus is these days.  OpenGL is kinda like flogging a dead horse if you care about optimal performance.

**Comment by DieSlower** [comment]
@mp3butcher 

> If you have mod to osg to submit, PR for them, i would be glad to review what i can .
As I'm practicing, i'm doing DC optimisation as a scenegraph transformation but if you have something else to propose i'm very interested.

Let me see if we can release the changes. They are not OSS , so that might take some doing. 

> GL2 had ffp and semantics
Since GL3, there's no semantic anymore, the only thing osg (as a meta engine) can do is to preserve old ffp behavior but nothing more

Right, but as OSG is developed further, and the GL3 profile seems like the more modern way of doing things, it should still keep its capabilities that it came out of the box with, right? 
There might be an option for the user to overwrite them, but it should not lose capabilities as it gets more modern. 
And if you have a textured model that was loading fine with GL2 profile, it should still be loaded fine with GL3. OSG might use a different technique, but it should still work. The user might not like that technique, and overwrite it, but there should be a default way, no?

> myosgPBR for one guy and the recipe is different when it comes to instance it

That looks really cool! Can that be placed as an example in OSG?

**Comment by DieSlower** [comment]
@openscenegraph 

> OpenGL is kinda like flogging a dead horse if you care about optimal performance

That's only partially true. OpenGL 4+ supports direct memory mapping, buffer mapping, and many other modern techniques that speed up performance without changing your scenegraph. While one should always optimize their scenegraph, at some point you cant do much more because the basics of how things are rendered, read into memory, uploaded to the GPU by the engine are the problem. 
If you load OSG with a simple scene in NVidia NSight, you will see that OSG has a huge overhead with the way it does its setup. Some of it is happening in the camera class, and some in a few other places. Using modern GL, it is possible to eliminate that overhead. 

VSG and Vulkan is the future for sure, but unless you plan to retire OSG after VSG 1.0 comes online, and just put it into maintenance mode, which might be your plan, I dont know, it seems logical to upgrade some features to the latest OpenGL possibilities. 
Vulkan is definitely the future, but OGL4.6 if used properly without deprecated functionality has very good performance, and works great with VR which needs 90fps per eye in most cases.

**Comment by openscenegraph** [comment]
On Wed, 29 Jan 2020 at 16:31, DieSlower <notifications@github.com> wrote:

> @openscenegraph <https://github.com/openscenegraph>
>
> OpenGL is kinda like flogging a dead horse if you care about optimal
> performance
>
> That's only partially true. OpenGL 4+ supports direct memory mapping,
> buffer mapping, and many other modern techniques that speed up performance
> without changing your scenegraph. While one should always optimize their
> scenegraph, at some point you cant do much more because the basics of how
> things are rendered, read into memory, uploaded to the GPU by the engine
> are the problem.
> If you load OSG with a simple scene in NVidia NSight, you will see that
> OSG has a huge overhead with the way it does its setup. Some of it is
> happening in the camera class, and some in a few other places. Using modern
> GL, it is possible to eliminate that overhead.
>
The osg::Camera doesn't do anything itself, it's just a container class for
settings that other parts of the OSG use. So.. huge overhead.. umm... I
can't argue with things that are likely confusion in how the OSG works and
what is how your usage of it falls short of the most efficient way.

VSG and Vulkan is the future for sure, but unless you plan to retire OSG
> after VSG 1.0 comes online, and just put it into maintenance mode, which
> might be your plan, I dont know, it seems logical to upgrade some features
> to the latest OpenGL possibilities.
> Vulkan is definitely the future, but OGL4.6 if used properly without
> deprecated functionality has very good performance, and works great with VR
> which needs 90fps per eye in most cases.
>
The OSG is already in maintenance mode, I made this clear a year and half
ago. If you just want to use GL3/GL4 features with the OSG then just create
a scene graph that contains GL3/GL4 state, job done.

Vulkan has far lower CPU overheads, supports proper multi-threading,
support ray tracing, I could go on, it's just far better than OpenGL except
in ease of use.

The VSG is really lightweight by design specifically for the Vulkan, it's
designed to be smaller and quicker than the OSG, and is often 10x faster
for the same task.  I can't retrofit these improvements to the OSG as it
would fundamentally change the API and break backwards compatibility.

I am not going to bother replying to any of this thread, it's not the right
place, there is the googlegroup/mailing list for support discussions.

Robert.
