### ISSUE TITLE
ON_DEMAND has no difference with CONTINUOUS

### ISSUE THREAD

**Issue by hankern** [openscenegraph/OpenSceneGraph#917]
i find in ON_DEMAND mode frame() will execute every frame,because of `if (_sceneData.valid() && (_sceneData->getUpdateCallback() || (_sceneData->getNumChildrenRequiringUpdateTraversal()>0))) return true;` always return true. critical point is _sceneData->getNumChildrenRequiringUpdateTraversal()>0 always true.

**Comment by openscenegraph** [comment]
This is working correctly, if you have nodes in the scene graph that
automatically update themselves each frame then the scene graph has to be
updated continuous.

If you want a different behaviour then simply roll your own frame loop
rather than use the Viewer::run() convenience method.

Robert.
