### ISSUE TITLE
Build failure with asio-1.14.0

### ISSUE THREAD

**Issue by belegdol** [openscenegraph/OpenSceneGraph#921]
OpenSceneGraph does not build against standalone asio-1.14.0, as reported by gentoo:
https://bugs.gentoo.org/698866
```
/var/tmp/portage/dev-games/openscenegraph-3.5.5/work/OpenSceneGraph-3.5.5/src/osgPlugins/RestHttpDevice/connection.cpp: In member function ‘void http::server::connection::start()’:
/var/tmp/portage/dev-games/openscenegraph-3.5.5/work/OpenSceneGraph-3.5.5/src/osgPlugins/RestHttpDevice/connection.cpp:43:29: error: ‘error’ is not a member of ‘asio::placeholders’; did you mean ‘asio::error’?
   43 |         asio::placeholders::error,
      |                             ^~~~~
In file included from /usr/include/asio/detail/impl/posix_mutex.ipp:24,
```
I was able to reproduce the issue and the fix is to add -DASIO_ENABLE_BOOST to CXXFLAGS. The reason is most likely this commit:

https://github.com/chriskohlhoff/asio/commit/265e75cdbba739b1b1e3a46b283eaee3b9c60fe8

Unfortunately, this is not enough to complete the build. With the extra flag the following error is encountered:
```
/builddir/build/BUILD/OpenSceneGraph-OpenSceneGraph-3.4.1/src/osgPlugins/RestHttpDevice/server.cpp: In constructor 'http::server::server::server(const string&, const string&, const string&, std::size_t)':
/builddir/build/BUILD/OpenSceneGraph-OpenSceneGraph-3.4.1/src/osgPlugins/RestHttpDevice/server.cpp:26:46: error: 'asio::ip::tcp::acceptor' {aka 'class asio::basic_socket_acceptor<asio::ip::tcp>'} has no member named 'get_io_service'
   26 |   asio::ip::tcp::resolver resolver(acceptor_.get_io_service());
      |                                              ^~~~~~~~~~~~~~
```
This is due to removal of get_io_service:

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html

I do not know how to fix the latter issue.

**Comment by vsg-dev** [comment]
Do you actually need to the RestHttpService plugin, it's a pretty niche bit of functionality that very very few people use.  I would suggest simply not building the RestHttpService plugin.

**Comment by JackBoosY** [comment]
Related issue: https://github.com/chriskohlhoff/asio/issues/316

**Comment by reavertm** [comment]
In Gentoo I fixed it with patch from https://github.com/ZeroAbility/vcpkg/commit/e24f7bf258ef9ee5c4cae2f9300f356441564c16 which I had to further modify (alignment to boost::system::error_code, get did of unnecessary shared pointer in temporary array created to synchronize threads in io service pool). As I have no means to test it, please treat just with "compilation fix" authority.

**Comment by robertosfield** [comment]
I have checked in a change the FindAsio.cmake to disable the match if reversion is 1.14.0 or later.

21f5a0adfb57dc4c28b696e93beface45de28194

This is checked into OSG master, 3.6 branch and MeshShaders branch
