### ISSUE TITLE
Incorrect Vertex Position after converted from some .3ds file

### ISSUE THREAD

**Issue by tom62291** [openscenegraph/OpenSceneGraph#922]
Hi,

I tried to use osgconv to convert 3ds to osg but i found the position is incorrect.

OSG file:

        VertexArray Vec3Array 41442
        {
          836491 818460 1.61767
          836480 818450 1.61767
          836480 818450 2.89959
          836493 818462 1.61767
          836495 818463 1.61767
          836496 818465 1.61767
          836498 818466 1.61767
          836504 818472 1.61767
          836507 818472 12.1523
          836482 818436 -15.6576
          836482 818436 -14.8179
          836481 818436 -13.6173
          836479 818432 -42.0687
          836477 818432 -42.0687
          836503 818422 -14.3998
          836503 818422 -15.9045
          836504 818423 -15.6704
          836477 818435 -49.8288
          836476 818434 -41.9828
          836476 818434 -41.8978
          836475 818437 -41.5342
          836475 818437 -41.4968

It is expected that all z coordinate should be >0 and actually the x and y also shifted as well.
Do you know the reason?

**Comment by robertosfield** [comment]
It's perfectly normally for coordinates to be negative.

Without having the original data and whole scene graph to compare against there is no way anyone else can help determine what is going on, whether it's your own misunderstanding what is going or actually an underlying issue in some part of the software. 

For instance the OSG scene graph contains transform nodes that place objects in world coordinates, if there decoate your scene graph then the local coodinates in a subgraph will be a different coordinate frame.

**Comment by tom62291** [comment]
ok, thank you, maybe the lib3ds have some problem as well
