### ISSUE TITLE
Issues when integrating with ImGui

### ISSUE THREAD

**Issue by blackball** [openscenegraph/OpenSceneGraph#924]
Hi, 

I am trying to integrate with ImGui with OSG, but the RenderDrawData function from: https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl2.cpp#L118 will cause issue when I need to dynamically change the scene. 

The UI partis added by adding an event handler. 

I found following lines: 
https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl2.cpp#L187
```
    // Restore modified GL state
    glDisableClientState(GL_COLOR_ARRAY);
    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glDisableClientState(GL_VERTEX_ARRAY);
```
will cause the dynamic added objects disappear. 

I wonder why this issue happened and how can I fix it in a portable way. 

Thanks!

**Comment by mp3butcher** [comment]
If you want to integrate in osg you have to play along with how osg::State manage opengl state without calling directly gl.
At first glance, you may achieve this embedding your imgui stuff in a class derivated from osg::Geometry.
I recommend to seek/post the forum if you have problem doing this.
As it's a client code problem, i think this issue can be closed

**Comment by blackball** [comment]
@mp3butcher I will try your advice. Thanks.
