### ISSUE TITLE
How to compile OSG to a single lib properly ? 

### ISSUE THREAD

**Issue by blackball** [openscenegraph/OpenSceneGraph#932]
Hi, 

I am working on an GUI application and trying to compile the whole OSG lib as a static library which I can link into my application. 

I tried to put all src files together in ./src/CMakeLists.txt to compile into an **osgAll** lib.  But as a result, I can not run any examples because of:
```
void StateSet::setGlobalDefaults() ShaderPipeline disabled.
Warning: GraphicsContext::WindowingSystemInterfaces::getWindowingSystemInterface() failed, no interfaces available.
AcrossAllScreens::configure() : Error, no WindowSystemInterface available, cannot create windows.
Viewer::realize() - failed to set up any windows
```
The CMakeLists.txt files in osg and osgViewer is straightforward, and I tried to keep codes are compiled and linked in the same way, but still I got the errors.

Any idea ? Thanks!

**Comment by mp3butcher** [comment]
Disabling DYNAMIC_OPENSCENEGRAPH  & DYNAMIC_OPENTHREADS variables should be sufficient

**Comment by blackball** [comment]
Thanks!
