### ISSUE TITLE
the website error, 'Missing jat3 framework plugin'

### ISSUE THREAD

**Issue by lcp0578** [openscenegraph/OpenSceneGraph#940]
the website error, 'Missing jat3 framework plugin'

**Comment by dellelce** [comment]
@openscenegraph @robertosfield Should the previous message not be clear: your website is completely down.

**Comment by robertosfield** [comment]
I've asked our website admin to look at it, though it'll be the weekend before can look.  We suspect that Dreamhost have updated the servers in a way that's impacted joomla used for the website.

**Comment by openscenegraph** [comment]
Thanks to @jtorresfabra website is now back up :-)

**Comment by lcp0578** [comment]
great job
