### ISSUE TITLE
No dependencies for VS2019

### ISSUE THREAD

**Issue by KevinSommer04** [openscenegraph/OpenSceneGraph#947]
Hi all, 

as far as I can see there are no dependencies for VS-2019. 
However, i tried to compile with VS2019 (v142) and the existing VS2017 (v141) dependencies and got the following compile errors in the nvtt-plugin : 

6>------ Rebuild All started: Project: Plugins nvtt, Configuration: Release x64 ------
6>Building Custom Rule C:/Users/kevins/Documents/Sandboxes/OpenSceneGraph/Sources/src/osgPlugins/nvtt/CMakeLists.txt
6>NVTTImageProcessor.cpp
6>nvtt.lib(CompressionOptions.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
6>Generating code
6>d:\toolkits\openscenegraph\3rdparty_x86_x64-src_v11\21_nvidia-texture-tools-2.1.0 - kopie\src\nvtt\taskdispatcher.h(57): fatal error C1001: Internal compiler error.
6>(compiler file 'd:\agent\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 182)
6> To work around this problem, try simplifying or changing the program near the locations listed above.
6>If possible please provide a repro here: https://developercommunity.visualstudio.com
6>Please choose the Technical Support command on the Visual C++
6> Help menu, or open the Technical Support help file for more information
6>  link!InvokeCompilerPass()+0x73be2
6>  link!InvokeCompilerPass()+0x73be2
6>  link!InvokeCompilerPass()+0x77b83
6>  link!InvokeCompilerPassW()+0xe8400
6>
6>Done building project "osgdb_nvtt.vcxproj" -- FAILED.

This error just occurs in Release-Mode in Debug-Mode everything is fine! And despite that I´m able to compile each other project. I´m using OSG 3.6
Any suggestions to solve the problem? 

Best regards, 
Kevin

**Comment by neoaurion** [comment]
Hi, you can use vcpkg to install dependencies (and even osg in fact) -> https://github.com/microsoft/vcpkg
