### ISSUE TITLE
Build failed in Ubuntu 18.04

### ISSUE THREAD

**Issue by lianghongzhuo** [openscenegraph/OpenSceneGraph#949]
Hi, I tried to build this at Ubuntu 18.04 but failed.
Steps to reproduce:
clone the master branch of the code
```
mkdir build && cd build
cmake ..
make
```
error message:
```
[ 99%] Built target osgdb_lua
[ 99%] Linking CXX executable ../../bin/osgviewer
[my libpng location]/libpng/lib/libpng16.so.16: undefined reference to `inflateReset2@ZLIB_1.2.3.4'
[my libpng location]/libpng/lib/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
collect2: error: ld returned 1 exit status
applications/osgviewer/CMakeFiles/application_osgviewer.dir/build.make:110: recipe for target 'bin/osgviewer' failed
make[2]: *** [bin/osgviewer] Error 1
CMakeFiles/Makefile2:6483: recipe for target 'applications/osgviewer/CMakeFiles/application_osgviewer.dir/all' failed
make[1]: *** [applications/osgviewer/CMakeFiles/application_osgviewer.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
I tried both the ubuntu default version of libpng (1.6.34) and lastest version (1.6.37) all have the same error message.
Any suggestions?

**Comment by robertosfield** [comment]
What version of the OSG are you trying to build?  What compilers?

FYI, I have a Kubuntu 18.04 system with the 1.6.34 libpng installed and OSG master and 3.6 branch are both working fine.  It's been this same system as I've used for the 3.6.x releases.

**Comment by lianghongzhuo** [comment]
I was building the master branch

**Comment by openscenegraph** [comment]
What compiler are you using?

Which version of Cmake are you using?

**Comment by lianghongzhuo** [comment]
I just run the `git pull` and got some new code updated from 
```
From https://github.com/openscenegraph/OpenSceneGraph
   c29e2e4f4..b8416a7aa  master     -> origin/master
Updating c29e2e4f4..b8416a7aa
```
Maybe my master branch is outdated, I'm compiling it again and report the result afterwards.

**Comment by lianghongzhuo** [comment]
Update: after compiling the `b8416a7aa` coomit.
The error still exists.
My Cmake version is 3.10.2 and gcc version is 7.5.0.

**Comment by openscenegraph** [comment]
I have just compiled OSG master on my Kubuntu 18.04 system.  Cmake 3.10.2,
gcc 7.5.0.

If I compile just the png plugin with VERBOSE hint this is what I get as
output (it's an in source build):

cd OpenSceneGraph/src/osgPlugins/png
make clean
make VERBOSE=1

//
// clipping out lots of prior output that isn't relevant
//
[100%] Linking CXX shared module ../../../lib/osgPlugins-3.7.0/osgdb_png.so
cd /home/robert/Dev/OpenSceneGraph/src/osgPlugins/png && /usr/bin/cmake -E
cmake_link_script CMakeFiles/osgdb_png.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -Wall -Wparentheses -Wno-long-long -Wno-import
-pedantic -Wreturn-type -Wmissing-braces -Wunknown-pragmas -Wunused
-Wmaybe-uninitialized -Wextra -Wshadow -Wno-misleading-indentation -O3
-DNDEBUG  -shared  -o ../../../lib/osgPlugins-3.7.0/osgdb_png.so
CMakeFiles/osgdb_png.dir/ReaderWriterPNG.cpp.o
-Wl,-rpath,/home/robert/Dev/OpenSceneGraph/lib:
../../../lib/libosgDB.so.3.7.0 ../../../lib/libosgUtil.so.3.7.0 -lpng -lz
../../../lib/libosg.so.3.7.0 ../../../lib/libOpenThreads.so.3.3.1 -lpthread
-lm -lrt -ldl -lGL

There is a -lpng -lz

Any chance you are missing ZLIB?

**Comment by openscenegraph** [comment]
I think the issue is probably libpng being installed but libzib not so I've added the ZLIB_FOUND as a pre-requisit: 

https://github.com/openscenegraph/OpenSceneGraph/commit/8437550c2566a6b00a6963eb725377c36bb3f07c

**Comment by lianghongzhuo** [comment]
Is `ZLIB` you said the package name `zlib1g`? If so, I already installed it.

**Comment by lianghongzhuo** [comment]
The new patch also can't work. Probably zlib is not the reason.

**Comment by lianghongzhuo** [comment]
I found the reason when I run `cmake ..` the system detects a wrong `zlib` version. This version `cmake` find is the `zlib` came with my binary build of `hdf5-view` package located at `$HOME/bin$. Now I deleted the hdf5-view package. The build passed.
Thank you for helping me debug this!
