### ISSUE TITLE
osgplanets example not running correctly

### ISSUE THREAD

**Issue by Divoo** [openscenegraph/OpenSceneGraph#96]
When I run **osgplanets** example, it output just this in the terminal without showing any graphics or opening any window:
```
rotateSpeed corrected by factor 0.5
Rorbits corrected by factor 15
Radius corrected by factor 10
```
Note that it didn't crash and stayed running, I kept it for **6 hours** and still nothing changed.

My OS is _Fedora 23._
I built _OSG_ from the latest commit at the time of writing this issue.
All other examples are working fine.

**Comment by openscenegraph** [comment]
The best place to report problems like this is via the osg-users mailing list/forum as this will get the issue seen by the most developers/users and thus maximise the chance that someone else will have a similar set up or have seen a similar problem before.

As for the particle issue you are seeing. I haven't seen any reports of problems with osgplanets before, it's a very simple example that just creates standard scene graph elements with standard way of creating the viewer/windows. Given this if I would expect to see problems running other examples and OSG applications not just osgplanets.

From the description it sounds like the window creation has failed for some reason.  Normally this should result in an OSG example exiting straight away.  Perhaps the Window manager is playing games.

With so little information about what system/OSG you are testing there is nothing we can do to investigate further,

What version of the OSG are you using?  Do you build it yourself?  Do you have the OpenSceneGraph-Data installed? What hardware and OpenGL driver are you using?

**Comment by Divoo** [comment]
I build OSG myself from the source (latest commit 7a63538fb9dadfe6bcb4bdd7da82dad2c7f4ddea)
I have OpenSceneGraph-Data installed and all other examples are working.
[glxinfo](https://github.com/openscenegraph/OpenSceneGraph/files/344534/glxinfo.txt) command output.
I have hybrid hardware (Intel and AMD). lspci command [output](https://github.com/openscenegraph/OpenSceneGraph/files/344548/lspci_output.txt).

I will post this also to osg-users mailing list/forum, thank you.

**Comment by openscenegraph** [comment]
The osgplanets example does nothing different in viewer/window setup than the majority of OSG examples so I can only presume that it's just a co-incidence that it happened on this particular example.  Given your OS/Driver/Hardware setup I would suspect the driver/window manager/compositor is not robustly handling the creation of an GLX/OpenGL window.  

There isn't much the OSG can do to resolve these problems, and certainly not anything that osgplanets example so I'll close this issue.  If there is anything we can do to resolve problems with the window manager/OpenGL driver will be on hints passed by the osgViewer library.  This is a best though, mostly like the problem will need to be resolved by fixes to the window manager/driver.
