### ISSUE TITLE
No CMake config (i.e. cannot use find_package in config mode)

### ISSUE THREAD

**Issue by lesurp** [openscenegraph/OpenSceneGraph#963]
Trying to use CMake as given in the example [here](https://github.com/openscenegraph/OpenSceneGraph/blob/master/examples/osgCMakeExampleModern/CMakeLists.txt) does not work:
```
CMake Error at cmake/find_dependencies.cmake:49 (find_package):
  Could not find a package configuration file provided by "OpenSceneGraph"
  (requested version 3.6.5) with any of the following names:

    OpenSceneGraphConfig.cmake
    openscenegraph-config.cmake

  Add the installation prefix of "OpenSceneGraph" to CMAKE_PREFIX_PATH or set
  "OpenSceneGraph_DIR" to a directory containing one of the above files.  If
  "OpenSceneGraph" provides a separate development package or SDK, be sure it
  has been installed.
```

It seems there are simply no generated package configuration file in OSG. While the older method of using OSG with CMake works, this example is very confusing since it doesn't work.

There are two solutions to this problem, adding a `OpenSceneGraphConfig.cmake.in` or... simply removing this example to avoid any confusion and waste of time.

**Comment by robertosfield** [comment]
Which version of the OSG are you building?  The config support only exists in master.
