### ISSUE TITLE
Pick coordinate wrong in MFC

### ISSUE THREAD

**Issue by Shen001** [openscenegraph/OpenSceneGraph#966]
I have a box model,and click on model face in MFC framework,but sometime i will get wrong coordinate（most of click position are near side）,and i do the same operate only in viewer ,it works well！ ！！
For Example，sometime i should get 2 coordinates in a perspective view because of picking overlap part of two faces,if my pick return just 2 coodinates,the result is good,but sometime return only 1 ,and the one is wrong coordinate!
I really confused about this case！Hope your reply~

**Comment by openscenegraph** [comment]
Please use the osg-users google group for general support questions like this.  The Issue tracker is for bug reports relating to the OpensceneGraph itself.

**Comment by Shen001** [comment]
> osg-users google group

ok，thanks~
