### ISSUE TITLE
OSG Version 3.0 errors during make

### ISSUE THREAD

**Issue by jimmyboyle2** [openscenegraph/OpenSceneGraph#971]
OSG Version 3.0 does not get through the Make process.  Environment:  Windows 10, MinGW, 32 bit.

After downloading the OSG 3.0 software, and using CMake to build the Makefiles (again, using MinGW option), I enter "mingw32-make" on the Windows DOS Command Line, and the make process errors at the 8% complete point.

Here are the errors: 
In constructor 'osg::State::State()':
OpenSceneGraph-OpenSceneGraph-3.0\src\osg\State.cpp:112:26: error: cannot convert 'bool' to 'bool*' in assignment
112 |     _abortRenderingPtr = false;

In member function 'const osg::StateAttribute* osg::State::getLastAppliedTextureAttribute(unsigned int, osg::StateAttribute::Type, unsigned int) const':
src\osg\State.cpp:692:55: error: cannot convert 'bool' to 'const osg::StateAttribute*' in return
692 |     if (unit>=_textureAttributeMapList.size()) return false;

osg.dir\build.make:1622: recipe for target 'src/osg/CMakeFiles/osg.dir/State.obj' failed
mingw32-make[2]: *** [src/osg/CMakeFiles/osg.dir/State.obj] Error 1
Makefile2:2459: recipe for target 'src/osg/CMakeFiles/osg.dir/all' failed
mingw32-make[1]: *** [src/osg/CMakeFiles/osg.dir/all] Error 2
Makefile:148: recipe for target 'all' failed

Thank you very much for any help you can provide.  I was able to install version 3.4.1, but I need version 3.0 or 3.2

**Comment by robertosfield** [comment]
You want to use an ancient version of the OSG with a niche build system, many years after it was last worked upon.... 9 years ago...  If you want to use such an old and no longer actively supported version then you'll need to pick your build tools that work with it, from the era when it was written  Or just upgrade to a supported version of the OSG.  The best version to use is 3.6.5.

**Comment by jimmyboyle2** [comment]
Excellent point!  Thank you very much for the quick reply!
