### ISSUE TITLE
Possible memory leak in JP2 Plugin

### ISSUE THREAD

**Issue by mikedig** [openscenegraph/OpenSceneGraph#972]
I noticed a memory leak in my application when reading JP2 images and trying to free up the objects. After profiling I saw there were a bunch of osg::Images left in memory after cleanup and noticed the JP2 plugin has set the Image's allocation to NO_DELETE. Not sure if this was intended or not, but when I change it to USE_NEW_DELETE after retrieving the Image object and then free up my scenegraph my memory issue went away.

Line in question: https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgPlugins/jp2/ReaderWriterJP2.cpp#L271

**Comment by robertosfield** [comment]
I've done a code review and it's a bit perplexing why the code was tweaked in the submission that changed.  I've changed the code to USE_NEW_DELETE and checked it into the 3.6 branch and master.
