### ISSUE TITLE
dont build on big endian

### ISSUE THREAD

**Issue by tlosm** [openscenegraph/OpenSceneGraph#98]
attched log

**Comment by tlosm** [comment]
[log.txt](https://github.com/openscenegraph/OpenSceneGraph/files/344504/log.txt)
Freescale NXP P5020 e5500

**Comment by openscenegraph** [comment]
This build error has *nothing* to do with endian.  It's a mismatch between the version of ffmpeg you have installed and the OSG's ffmpeg plugin.  

You have completely failed to mention anything about the version of the OSG or FFmpeg, so it's kinda hard to know what the exact fix is in your case.  FFmpeg API moves the goal posts regularily so even if we get the OSG stable release building against the current FFmpeg's available at the time of our stable release and month or two later the latest FFmpeg will break the API and the build of already released software.

It'll either be upgrade to git master or a recent dev release or change your ffmpeg version.  The latest git master has fixes to enable the OSG to build with recent rev's of ffmpeg.  I'm closing this issue as it's almost certainly down to you mixing incompatible versions of the OSG/FFmpeg that have already been resolved.

In future can you please post issues that you have with building on the osg-users mailing list/forum as this is the avenue for support questions/discussions.
