### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [openscenegraph/OpenSceneGraph#988]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by openscenegraph** [comment]
Is there a problem with the current github repository?  What motivation is
there for changing?

**Comment by Neustradamus** [comment]
It will be better and openscenegraph is a project, not a person :)
More options... always free.

**Comment by openscenegraph** [comment]
On Thu, 8 Oct 2020 at 15:34, Neustradamus <notifications@github.com> wrote:

> It will be better and openscenegraph is a project, not a person :)
>
In what way would it be better?

I'm not about invest time into something that is not going to functionally
make any difference to anyone.

**Comment by Neustradamus** [comment]
It will be done quickly.

Look (for example) : http://github.com/gnome vs https://github.com/openscenegraph

For all Free options: https://github.com/pricing.

**Comment by openscenegraph** [comment]
I'm still lost as to the value add.  Folk just need access to the source
code and commit PR's.

**Comment by Neustradamus** [comment]
@openscenegraph: I think that the best solution is (in few minutes):
- Change your username to openscenegraphaccount (or other): https://github.com/settings/admin
- Create openscenegraph organization: https://github.com/organizations/new

And:
- Transfer OpenSceneGraph into openscenegraph org: https://github.com/openscenegraph/OpenSceneGraph/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

**Comment by robertosfield** [comment]
Still no reason why.

What value does this change have for the project?

Why should I spend time doing this rather than fixing bugs and reviewing
submissions?

**Comment by Neustradamus** [comment]
@robertosfield: Better management and publish with a real personal account.

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams
