### ISSUE TITLE
show point cloud data exceptions

### ISSUE THREAD

**Issue by zhanyiaini** [openscenegraph/OpenSceneGraph#993]
Here is the code：

`#include <lasreader.hpp>
#include <osg/Point>
void Widget3D::initData()
{
    QString name = "F:\\projects\\PowerLineCheckV2\\project\\test4\\spc\\T1-T2.las";
    LASreadOpener opener;
    opener.set_file_name(name.toLocal8Bit().data());
    LASreader* reader = opener.open();
    if (!reader)
    {
        return;
    }
    const LASheader& h = reader->header;

    qDebug("scale(%f,%f,%f)", h.x_scale_factor, h.y_scale_factor, h.z_scale_factor);
    qDebug("offset(%f,%f,%f)", h.x_offset, h.y_offset, h.z_offset);
    qDebug("min(%f,%f,%f)", h.min_x, h.min_y, h.min_z);
    qDebug("max(%f,%f,%f)", h.max_x, h.max_y, h.max_z);

    float maxz = (h.max_z - h.z_offset) / h.z_scale_factor;
    float minz = (h.min_z - h.z_offset) / h.z_scale_factor;
    float deltaz = (maxz - minz) / 3.0f;
    float greenz = minz + deltaz;
    osg::Vec3d p;
    osg::Vec4 c(1.0f, 1.0f, 1.0f, 1.0f);
    float z = 0;

    osg::Vec3dArray* points = new osg::Vec3dArray();
    osg::Vec4Array* colors = new osg::Vec4Array();
    osg::ref_ptr<osg::Geometry> geo = new osg::Geometry();

    while (reader->read_point())
    {
        LASpoint& point = reader->point;

        p.set(point.get_X(),
              point.get_Y(),
              point.get_Z());
        points->push_back(p);

        z = point.get_Z();
        if (z > greenz)
        {
            c.r() = (z - greenz) / deltaz;
            c.b() = 0.0;
            c.g() = 1 - c.r();
        }
        else
        {
            c.r() = 0.0;
            c.b() = (greenz - z) / deltaz;
            c.g() = 1 - c.b();
        }
        colors->push_back(c);
    }

    geo->setVertexArray(points);
    geo->addPrimitiveSet(new osg::DrawArrays(GL_POINTS, 0, GLsizei(points->size())));
    geo->setColorArray(colors);
    geo->setColorBinding(osg::Geometry::BIND_PER_VERTEX);
    geo->setUseDisplayList(false);
    geo->setUseVertexBufferObjects(true);
    geo->setUpdateCallback(new osg::DrawableUpdateCallback);

    osg::ref_ptr<osg::Geode> geode = new osg::Geode();
    geode->addDrawable(geo);

    osg::Matrixd matrix = osg::Matrixd::scale(h.x_scale_factor, h.y_scale_factor, h.z_scale_factor)
        * osg::Matrixd::translate(h.x_offset, h.y_offset, h.z_offset);
    osg::MatrixTransform* mt = new osg::MatrixTransform();
    mt->addChild(geode);
    mt->setMatrix(matrix);
    mt->getOrCreateStateSet()->setAttributeAndModes(new osg::Point(2));
    mt->getOrCreateStateSet()->setMode(GL_LIGHTING, osg::StateAttribute::OFF);

    reader->close();
    delete reader;

    m_pRoot->addChild(mt);
}`

Here is the output log:

scale(0.010000,0.010000,0.010000)
offset(0.000000,0.000000,0.000000)
min(228861.700000,3372712.310000,1.710000)
max(229017.400000,3373070.360000,51.200000)

An anomaly occurs when the camera zooms in and rotates.

The following is a screenshot of the exception：

![image](https://user-images.githubusercontent.com/16935148/98210137-0c232380-1f7b-11eb-9576-0a192e71974f.png)

The following is a normal screenshot：

![image](https://user-images.githubusercontent.com/16935148/98210342-6328f880-1f7b-11eb-953f-8093eddb63be.png)

**Comment by openscenegraph** [comment]
The word exception has a specific meaning in C++.  I can't see how it fits
in what you are describing.  If you are getting an exception then only you
can trace it back to code that threw it.

If you mean that something odd happens visually what do you specifically
mean.  You've posted two different images saying one is wrong/one is
correct.  Is it that points are missing?

With the OSG if you have a single osg::Geometry then it'll be passed to
OpenGL in one block, the OSG itself won't be causing some points to
disappear/appear - the OSG will either cull the geometry so none of it's
seen, or pass view frustum culling tests and the whole geometry will be
sent to be render.  So if you are seeing odd effects of some points not
appearing it won't be an OSG issue.

What it might be is something we can't say from the information given.  You
attach an update callback, is this messing up?  Could you hardware be
messing up when handling very large amounts of data?  Try different machine
+ hardware + OS to see if any differences emerge.

For the types of problem you are seeing they are really things that others
are well placed to help with.  You have your data+hardware+application and
the problem in front of you.

Robert.

**Comment by zhanyiaini** [comment]
> messing up

To Robert:

I've tried different machine + hardware + OS,But the problem of points disappearing when zooming and rotating the camera remains.
It is found that the point will disappear/appear if the coordinate value of the point is too high(Does not exceed the maximum value of the double data type).

Here is the output log:

scale(0.010000,0.010000,0.010000)
offset(0.000000,0.000000,0.000000)
min(228859.750000,3372703.350000,1.710000)
max(229020.270000,3373079.980000,51.200000)
p1(22891247.000000,337271882.000000,1266.000000)
p2(22891218.000000,337271875.000000,1292.000000)
p3(22891210.000000,337271868.000000,1268.000000)
p4(22891182.000000,337271855.000000,1250.000000)
p5(22891175.000000,337271847.000000,1224.000000)
p6(22891309.000000,337271848.000000,888.000000)
p7(22891172.000000,337271841.000000,1185.000000)
p8(22891290.000000,337271841.000000,891.000000)
p9(22891140.000000,337271833.000000,1222.000000)
p10(22891269.000000,337271834.000000,898.000000)
...

ZhanYi.

**Comment by openscenegraph** [comment]
Hi ZhanYi,

If you are having precision issues then the only way to address it is to
move your data to a local origin and use a MatrixTransform above the
subgraph to place it in world coordinates.  This approach is used widely by
the OSG and in the community, it's standard approach that is used widely
and has been discussed in depth dozens of times in the osg-users community
over the years so please have a look through the archives.

Robert.

**Comment by zhanyiaini** [comment]
I see. Thanks a lot！
